### ISSUE TITLE
Support for Android Firefox

### ISSUE THREAD

**Issue by elmodor** [sissbruecker/linkding#105]
Hello,

is it planned to support firefox on Android? 
Currently the firefox extension cannot be used on firefox Android (unable to install it with the newest version, with an older firefox version I'm able to isntall it but the settings seem not to be saved so whenever I click the addon it redirects me to the "getting started" website).
The bookmarklet does not work on firefox Android either (which is probably a bug in firefox).

**Comment by sissbruecker** [comment]
@elmodor For the extension, please report issues to the repo of the extension itself: https://github.com/sissbruecker/linkding-extension. Please add an issue there and close this one if you want support specifically for the extension, or clarify this issue if it's about the bookmarklet.

Not using Android, so my motivation for working on this would be extremely low. However we have now have a [how-to](https://github.com/sissbruecker/linkding/blob/master/docs/how-to.md) describing how to get the bookmarklet working on Android/Chrome, maybe something similar can be achieved with Firefox? Also check the iOS workaround in the same doc, there might be a similar app for Android that allows to create share actions that could then open the add bookmark form with the URL from the browser tab.

**Comment by elmodor** [comment]
I have opened https://github.com/sissbruecker/linkding-extension/issues/6 there. Not sure if it is fixable with a low effort, I just know that firefox changed something a while ago regarding their addons and that broke all "old" plugins that did not got updated.

Anyways, the bookmarklet used not to work on android firefox. However, while checking and giving you the official link to the bug ticket, 9 days ago someone said that it is working now with the latest firefox version that just got released. So I tried it as well, and voilá! It works. Awesome.
It is described there how it works:
https://github.com/mozilla-mobile/fenix/issues/2871#issuecomment-831852154

I think it is really similar (if not identical) to the solution posted in the how-to for chrome.
So maybe you can remove the
``` Note that this only works with Chrome and not with other browsers on Android. ```
and mention that it should work on Android Firefox as well with the latest Android Firefox version (>88.1.2)

**Comment by sissbruecker** [comment]
Closing as issue has been moved.
