### ISSUE TITLE
relative names use the wrong "today" after day change

### ISSUE THREAD

**Issue by fs111** [sissbruecker/linkding#107]
The function https://github.com/sissbruecker/linkding/commit/7a68a4abed92711beb41351c856fcbc76960d687#diff-af6e19b019439b7b4f3a493fe1ae0c0d177b5ddab5e0bf1d66c733341f2301adR39 when called with only one parameter will cache the date from the moment in time when the service was last restarted. That leads to the strange effect that a bookmark added on the day it was started, is marked as **Today**, yet that is not today. It is just the day the process was started. See screenshot below.

<img width="687" alt="Screenshot 2021-04-06 at 22 36 57" src="https://user-images.githubusercontent.com/33631/113775790-7f4ae480-9729-11eb-8992-ff47fc604b04.png">

**Comment by sissbruecker** [comment]
Thanks for debugging this, it might have taken me some time to identify that behaviour, did not expect default parameters to work like that. Fixed it and currently running a release.

**Comment by fs111** [comment]
Yeah, those are resolved at parse/startup time and it is indeed surprising.

Did you push the latest release to docker hub? I am not seeing it there: https://hub.docker.com/r/sissbruecker/linkding/tags?page=1&ordering=last_updated

**Comment by sissbruecker** [comment]
Latest image is up now.
