### ISSUE TITLE
query with multiple hashtags very slow

### ISSUE THREAD

**Issue by ahheckel** [sissbruecker/linkding#112]
I am running linkding in a docker container (following the instructions on this page) on a  Raspberry4 under  a current RaspianOS 32bit with ~500 bookmarks which works very well so far.
The response is quick when searching for a single hashtag, however it can be very long (up to a minute) when combining multiple hashtags in a query (#tag1 #tag2). This is particularly true when that query yields more than just a few results. 
I was wonderung whether the database query can be optimized for speed.
Kind regards, 
(PS great project).

**Comment by sissbruecker** [comment]
I tested this a bit and can confirm that query performance degrades when using multiple tags. However in my tests (also on a RPie 4) I would need to add a lot more than 2 tags and even then the query would resolve in a few seconds (which is still too slow IMO, but far better than what you are experiencing).

Specifically for the use-case described here - for 500 bookmarks and 2 tags in the query 1 minute would be extremely bad. I see two possible issues here:
- You might have a lot of tag assignments in general - if you could check how many rows you have in your `bookmarks_bookmark_tags` table in the database that might help solving this
- Or there is just some other reason why your installation performs to poorly. However if regular searches perform well that seems unlikey.

**Comment by ulixxe** [comment]
Hi,
I closed #141 and use this issue from now on to signal that I search for only 1 tag, and I have to restart the docker container after several minutes of 100% CPU utilization.
In my bookmarks_bookmark_tags table, I have about 2.5k rows.

**Comment by ulixxe** [comment]
I found that the search speed is ok if I comment the below lines 98-101 from bookmarks/queries.py. Can some optimization be done on those lines?

    for tag_name in query['tag_names']:
        query_set = query_set.filter(
            bookmark__tags__name__iexact=tag_name
        )

**Comment by ahheckel** [comment]
ulixxe's suggestion solves the problem in my case, too.
