### ISSUE TITLE
[Feature Request] Notes

### ISSUE THREAD

**Issue by excodex** [sissbruecker/linkding#113]
Hi,

Awesome project, I absolutely love it!
Can you implement notes section where user can write notes for links? That will be great! :)

Thank you for your hard work!
Cheers!

**Comment by sissbruecker** [comment]
Mhh, I always thought that the description is the field where you can add any additional info for a bookmark if you want to. Any specific reason why you are not using that?

While it's not a difficult change, I would prefer to keep the bookmark form as minimal as possible, adding another multi-line text area would probably hurt more users than it benefits.

**Comment by sissbruecker** [comment]
Closing as stale.
