### ISSUE TITLE
[Feature Request] Link image

### ISSUE THREAD

**Issue by taich001** [sissbruecker/linkding#114]
I think it would be great to see an image of every link as an overview. 
It would be much easier to find a specific link if you could see a small image of the target of this link.

**Comment by sissbruecker** [comment]
This is something I'll most likely will never add. My goal with linkding is to keep the UI minimal and very easy to read, which means compact and text-based. From the feedback that I get from the community that is what users like about it as well. 

As such I'll close this issue.

Note that there are lots of other self-hostable bookmark managers which support this so you might try one of those.
