### ISSUE TITLE
Feature request: different color of chrome extension button indicating current website added or not

### ISSUE THREAD

**Issue by vindevil** [sissbruecker/linkding#120]
I think it would be very helpful by providing this information, just like the chrome built-in bookmarks manager does.

**Comment by sissbruecker** [comment]
@vindevil The linkding extension has its own repository, please report related issue there: https://github.com/sissbruecker/linkding-extension

Also please provide some more information of what you are trying to achieve if possible. From what I understand you want the extension to inform you if you already added a bookmark for that URL? That feature exists in the linkding UI, but not yet in the extension.

Closing as unrelated.
