### ISSUE TITLE
How to disable login or set guest?

### ISSUE THREAD

**Issue by dnldp55** [sissbruecker/linkding#123]
We want to turn off the login service
Because We need this is for company public use.

How to change disable login service?

**Comment by spouradrix** [comment]
I have the same question. Some self hosted let you have a switch in the config like --no-password and in config file authentication: false. I love the app but can't use it until this function is implemented (if it isn't already).

**Comment by flinthamm** [comment]
+1

**Comment by sdresen** [comment]
+1

**Comment by prastamaha** [comment]
+1

**Comment by sissbruecker** [comment]
I'm not quite sure if people are voting for disabling login, or being able to share bookmarks publicly / with other people. For now I'll interpret this as disabling login. Sharing bookmarks with other users is possible as of `1.12.0`.

For disabling login it would be good to describe some use-cases, I can only imagine something around using an auth proxy with linkding.

**Comment by pascaliske** [comment]
> I'm not quite sure if people are voting for disabling login, or being able to share bookmarks publicly / with other people. For now I'll interpret this as disabling login. Sharing bookmarks with other users is possible as of `1.12.0`.
> 
> For disabling login it would be good to describe some use-cases, I can only imagine something around using an auth proxy with linkding.

Yes, for me it would be exactly this: Disabling auth and integrate it with authelia auth proxy...

**Comment by sissbruecker** [comment]
For auth proxy support I would probably structure this a bit differently:
- have an option to enable auth proxy support
- have an option for configuring the request header that contains the username
- probably have an option to configure a logout redirect URL

Users would still have to be created in advance with matching username.

**Comment by pascaliske** [comment]
> Users would still have to be created in advance with matching username.

Seems reasonable. I can even think of a feature to "provision" an initial admin user with a pair of environment variables. This would be a perfect fit! But lets keep this for another feature request... 😁

**Comment by sissbruecker** [comment]
Added support for authentication proxies in https://github.com/sissbruecker/linkding/pull/321

Closing this for now, as I don't see any other reasonable use-cases for simply disabling the login. I'll consider reopening this if someone can provide a use-case.

**Comment by ahheckel** [comment]
Another use case would simply be a self hosted single user scenario, where authentication is pointless and wouldn`t add to security; having to login repeatedly is tedious... alternatively a "keep me logged in" feature wouldbe nice. THX for your great project.

**Comment by ahheckel** [comment]
i should specify: single user self-hosted intranet-only scenario

**Comment by cbeauhilton** [comment]
Similar theme: I use tailscale for self hosting, so disabling internal authentication in an app is helpful. The tailnet itself is providing auth, such that the IP of the service is not connectable unless the device is connected to the tailnet.

**Comment by sissbruecker** [comment]
I think a workaround could be to:
- enable authentication proxy support in linkding
- add a proxy (nginx) in front of linkding
- set a static request header with the username in the proxy

**Comment by sissbruecker** [comment]
Yeah, the use-case seems reasonable, feel free to open a new issue for it.
