### ISSUE TITLE
Option to show URL at all times in default view

### ISSUE THREAD

**Issue by onjour** [sissbruecker/linkding#132]
I'd love to be able to see the full URL of the bookmarks in the default view.

Sometimes the web title isn't informative enough and having the URL as well helps to find the information. 

Thanks

**Comment by soundneedle** [comment]
OMG…esp. in the list of search result. I have no idea what a title is as its “source” without seeing a URL. LinkAce shows that info. Very helpful.

**Comment by gingerbeardman** [comment]
+1 for this

**Comment by gingerbeardman** [comment]
by no means a permanent solution, or the best approach, but I edited a file on my own installation to add this...

https://github.com/sissbruecker/linkding/blob/b93a9fadb637bfb132583836c046887e3f70dd87/bookmarks/templates/bookmarks/bookmark_list.html#L11-L15

becomes:
```
            <div class="title truncate">
                <a href="{{ bookmark.url }}" target="{{ link_target }}" rel="noopener">{{ bookmark.resolved_title }}</a>
            </div>
            <div class="description truncate">
                <span>                                                                                                                          
                <a href="{{ bookmark.url }}" target="{{ link_target }}" rel="noopener">{{ bookmark.url }}</a><br>                               
                </span>                                                                                                                         
                {% if bookmark.tag_names %}
```

and looks like this:
<img width="653" alt="Screenshot 2022-02-22 at 13 26 44" src="https://user-images.githubusercontent.com/49612/155141987-aecf9f70-f402-4199-86cc-0d9800c2a1ff.png">

**Comment by sebw** [comment]
was there ever a merge request for this @gingerbeardman @clach04 @sissbruecker ?

**Comment by clach04** [comment]
> was there ever a merge request for this @gingerbeardman @clach04 @sissbruecker ?

https://github.com/sissbruecker/linkding/pull/219

**Comment by sissbruecker** [comment]
Solved as part of https://github.com/sissbruecker/linkding/pull/365
