### ISSUE TITLE
Adding bookmarks is slow sometimes

### ISSUE THREAD

**Issue by rahul003** [sissbruecker/linkding#137]
```
today at 10:06:49 AM [pid: 18|app: 0|req: 44/162] 172.28.0.2 () {52 vars in 1359 bytes} [Mon Jul 26 14:06:49 2021] GET /api/tags/?limit=1000&offset=0 => generated 3297 bytes in 24 msecs (HTTP/1.1 200) 6 headers in 196 bytes (1 switches on core 0)
today at 10:06:53 AM [pid: 16|app: 0|req: 40/163] 172.28.0.2 () {52 vars in 2053 bytes} [Mon Jul 26 14:06:49 2021] GET /api/bookmarks/check/?url=https%3A%2F%2Fwww.amazon.com%2Ffcx%2Fshop-by-age%2Fstore%2Fref%3Ds9_acss_bw_cg_SBATG_2b1_w%3Fref_%3Dfly_sa_hom_rwt_stet_r_2y4y_nvs_165793011%26age%3D2y_4y%26st%3D165793011%26pf_rd_m%3DATVPDKIKX0DER%26pf_rd_s%3Dmerchandised-search-4%26pf_rd_r%3DBYJW4WZYJTNV4B2BKXT5%26pf_rd_t%3D101%26pf_rd_p%3Dcf12e233-413e-4cec-875c-d3d603da0684%26pf_rd_i%3D165793011 => generated 395 bytes in 3541 msecs (HTTP/1.1 200) 6 headers in 189 bytes (1 switches on core 0)
today at 10:06:57 AM [pid: 16|app: 0|req: 41/164] 172.28.0.2 () {60 vars in 1551 bytes} [Mon Jul 26 14:06:54 2021] POST /bookmarks/new => generated 0 bytes in 3614 msecs (HTTP/1.1 302) 6 headers in 191 bytes (1 switches on core 1)
```

Sometimes such check calls finish in 20-50msec, but some other times it takes such a long time. Why could this be happening? How can I fix it?

**Comment by rahul003** [comment]
My database is on SD card, server running on raspberry pi. I wonder if SD card performance is an issue? It's a class 10 Sandisk SD card.

**Comment by sissbruecker** [comment]
When saving a bookmark the application will fetch the website to get the website's title and description. So saving a bookmark takes longer if the page takes longer to load. 

There is currently no way to influence this. There is an open PR (https://github.com/sissbruecker/linkding/pull/126) to apply a timeout to the website request, but it still needs some work.

**Comment by sissbruecker** [comment]
Closing this as an explanation was given and the PR for adding a timeout was merged.
