### ISSUE TITLE
thank you and a chrome extension

### ISSUE THREAD

**Issue by jeroenpardon** [sissbruecker/linkding#14]
Hello @sissbruecker, wanted to let you know I love linkding and I use it every day.

I put together a little [Chromium extension](https://github.com/jeroenpardon/linkding-extension) for my preferred way of using Linkding, thought you'd might like to know about it. And possibly it will be of use to someone besides me :)

Keep up the great work!

**Comment by sissbruecker** [comment]
Thanks for the kind words @jeroenpardon . I like the extension, that's actually more convenient than the link that I had in my bookmark bar. I tested it with Brave and it works there too. I also added a link to the extension to the repos README.md.
