### ISSUE TITLE
Search by tag is very slow

### ISSUE THREAD

**Issue by ulixxe** [sissbruecker/linkding#141]
Hi,
linkding is a very nice tool for managing bookmarks.
But I find the search by tag so slow that it makes linkding unusable.
I have about 1300 bookmarks and 48 tags. Some tags refer to a large number of bookmarks. For example, the first three most used tags refer to 674, 395, and 255 bookmarks, respectively.
When I search for the first tag (674 bookmarks), linkding hogs with 100% CPU utilization, and after several minutes, I have to restart the docker container to use it again.
I think the search algorithm has some O(n^2) or worst time complexity.
Can it be improved?
Thanks

**Comment by sissbruecker** [comment]
@ulixxe Can you please add your comment to this issue #112 and close this one? Very likely that they are related.

**Comment by ulixxe** [comment]
ok, I will use #112 issue for this problem
