### ISSUE TITLE
Why is linkding running as user:group 33?

### ISSUE THREAD

**Issue by MPowerData** [sissbruecker/linkding#145]
Hi,

Just wondering why linkding is running as user and group 33? 

This prevents me from setting more generic file permissions on my docker folders.

Would it be possible to configure a user:group which is available on the system?

**Comment by sissbruecker** [comment]
This is the PR that introduced the change: https://github.com/sissbruecker/linkding/pull/8

I'm not really motivated to support a configuration option for this. As a workaround you could mount your own files into the Docker container. The relevant files that reference the user + group are:
- https://github.com/sissbruecker/linkding/blob/master/bootstrap.sh
- https://github.com/sissbruecker/linkding/blob/master/uwsgi.ini

**Comment by MPowerData** [comment]
Ok, thank you!
