### ISSUE TITLE
umlaut/non-ascii characters broken when using bookmarklet (firefox)

### ISSUE THREAD

**Issue by fs111** [sissbruecker/linkding#148]
When I bookmark a page via the bookmarklet I get broken umlauts/other characters (like é) in the title as well as in the description. As an example:

Bookmarking https://emmikochteinfach.de/pasta-mit-kuerbis-schnell-und-einfach via the bookmarklet produces the title

> "Pasta mit KÃ¼rbis - schnell und einfach gemacht - emmikochteinfach"

and description 

> Das einfache Rezept fÃ¼r Pasta mit KÃ¼rbis. Die schnellen Nudeln mit KÃ¼r...

This does not happen when using the browser plugin (for firefox).

P.S.: That pasta recipe is pretty tasty :-)

**Comment by sissbruecker** [comment]
Thanks for reporting this, it seems to be the same issue that is addressed in #126 . See this comment specifically: https://github.com/sissbruecker/linkding/pull/126#issuecomment-905284718. The issue applied to all bookmarks, regardless if they were saved through the create bookmark form, the extension, or the bookmarklet. The extension just works a bit differently, in that it uses the browser tab API to show a preview for the page title.

The recipe looks tasty indeed, Guten Appetit 🙂.
