### ISSUE TITLE
Leaving description field empty when creating a bookmark

### ISSUE THREAD

**Issue by ajeetdsouza** [sissbruecker/linkding#15]
How does one leave the description field empty when creating a new bookmark? Currently, leaving it empty just fills it up using the website's content.

**Comment by sissbruecker** [comment]
Hmm, that's not really a use case I considered. I thought that having more data is always useful, for example for searching where it also looks at the description. The input was only for cases where you want to override the default content or provide your own description.

I tried with space, but that is ignored. The only thing you can do right now is to enter a single non-space character into the field like `-`. Could you elaborate on your use-case?

**Comment by ajeetdsouza** [comment]
The auto-retrieved description is not always a good one, and I do keep my titles descriptive enough, so I don't really need the description field except in very specific scenarios.

While I am currently using a `-` in place of the description, this does feel like a less-than-ideal solution. It would be great if you could handle the `-` case separately to blank out the field!

**Comment by Gatada** [comment]
I prefer short titles and good descriptions.

On Pinboard.in I sometimes leave description empty, but only when I check off "read later" (a collection I keep short, and update often).

Here I would replace the checkbox with a #readlater tag.

If the description is always auto-populated, never left empty by default, then I'm fine with it being required.

But if I have to spend time to fill in something helpful and succinct, then I would prefer the description field to be optional (left blank).

**Comment by joel72265** [comment]
When saving a Linkding bookmark, if we don't enter a description the description is automatically populated in the bookmark. Please create a checkbox to disable the description from being auto populated.
