### ISSUE TITLE
Add a setting to open clicked bookmark in new tab (target="_blank") vs. same tab

### ISSUE THREAD

**Issue by vladstudio** [sissbruecker/linkding#160]
Hi! First of all, great app, thanks for working on it. 
I'm considering using Linkding as a "new tab" page in Chrome. For this use case, opening a clicked bookmark in new tab is overkill. I have to return to Linkding tab and close it every time. 
Thanks.

**Comment by sissbruecker** [comment]
Closing as duplicate of: https://github.com/sissbruecker/linkding/issues/27

Please follow that for updates.
