### ISSUE TITLE
Show installed version 

### ISSUE THREAD

**Issue by mattofr** [sissbruecker/linkding#169]
Hi Sascha,

Could you show the currently installed version (like "v1.8.3") somewhere? Perhaps in the General Settings Page?
So one can see which version is currently installed?

**Comment by virtadpt** [comment]
Always a handy thing.

**Comment by sissbruecker** [comment]
Hey Matto, there is an about section in the settings which shows the installed version:

![Bildschirmfoto 2021-10-17 um 18 23 07](https://user-images.githubusercontent.com/357820/137636059-50b8f394-75a8-45f7-b276-fa5e3cc4e7e8.png)

You probably just need to upgrade.
