### ISSUE TITLE
Proper implementation of Archive.org + opting-out from Archive.org with Docker

### ISSUE THREAD

**Issue by onjour** [sissbruecker/linkding#171]
I like this tool a lot, however, I ran on some issues that have to be mentioned.

I use the website https://rateyourmusic.com/ a lot and I've been the victim of IP ban preventing me to access the website because of 'automated requests'. 

I have the issue since months and it was extremely difficult for me to troubleshoot what went wrong. Website owner pointed out so many possible causes that it was hard to pinpoint one (especially given my non technical background). 

In one recent conversation, the owner told me that my IP was banned because of "dozens of requests from archive.org-owned servers" occurring in a very short amount of time — thus triggering the IP ban **everytime** I tried to bookmark a chart of artist page from this website.

Archiving the web is a great goal but I believe the implementation of automatic archive.org archiving should be more polished. 

Moreover, I don't have any clue on how to opt-out of this service? Please provide information so I can disable it until this issue is fixed. I use linkding with Docker. 

> EDIT: So apparently we're expected to add / create to the .env file a `LD_DISABLE_BACKGROUND_TASKS=True` in order to prevent pages from being archive.org-ed. Is that correct?

Besides, there's also a lot of privacy concerns with forcing every user to use the archive.org service.

Thank you.

**Comment by sissbruecker** [comment]
Sorry to hear that, that is certainly unfortunate. `LD_DISABLE_BACKGROUND_TASKS` is the correct option to use for now. The .env file is only used in combination with docker-compose, if you are just using Docker, then this section explains how to apply an option: https://github.com/sissbruecker/linkding/blob/master/docs/Options.md#docker

Furthermore, can you please add a copy of your comment to #157 and close this issue? I think we are talking about the same problem here (opt-in vs opt-out), with different side-effects / symptoms.

**Comment by onjour** [comment]
Thank you for your reply. I'm indeed using Docker Compose. 

I thought this was solved because when I added new bookmarks there wasn't any reference to archive.org in the date field but when I accessed the service a while later I noticed that it was **still** putting it in archive.org !

Kindly provide proper instructions on how to disable this.

My docker-compose is 

⋊> ~/d/linkding cat .env                                                                                                                                    09:43:31LD_DISABLE_BACKGROUND_TASKS=True
⋊> ~/d/linkding cat docker-compose.yml                                                                                                                      09:43:33version: '3'

```
services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    restart: unless-stopped
```

And I added a basic .env to try to settle the issue

`LD_DISABLE_BACKGROUND_TASKS=True`

I'll refer as suggested when you clarify the procedure on how to opt-out of automatic archiving to archive.org.

Thank you

**Comment by onjour** [comment]
> Sorry to hear that, that is certainly unfortunate. `LD_DISABLE_BACKGROUND_TASKS` is the correct option to use for now. The .env file is only used in combination with docker-compose, if you are just using Docker, then this section explains how to apply an option: https://github.com/sissbruecker/linkding/blob/master/docs/Options.md#docker
> 
> Furthermore, can you please add a copy of your comment to #157 and close this issue? I think we are talking about the same problem here (opt-in vs opt-out), with different side-effects / symptoms.

Thank you for your reply. I'm indeed using Docker Compose.

I thought this was solved because when I added new bookmarks there wasn't any reference to archive.org in the date field but when I accessed the service a while later I noticed that it was still putting it in archive.org !

Kindly @sissbruecker provide proper instructions on how to disable this.

My docker-compose is

version: '3'

services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    restart: unless-stopped

And I added a basic .env to try to settle the issue

LD_DISABLE_BACKGROUND_TASKS=True

I'll refer as suggested when you clarify the procedure on how to opt-out of automatic archiving to archive.org.

Thank you

**Comment by onjour** [comment]
After a few days of use, I can confirm that adding
`
LD_DISABLE_BACKGROUND_TASKS=True`

**DOES NOT** prevent linkding from archiving automatically the bookmarks the archive.org 

Again, I'd like @sissbruecker to clarify how to opt out from this service

**Comment by sissbruecker** [comment]
Looks like the `docker-compose.yaml` configuration does not import the variables from `.env`. I updated the template here: https://github.com/sissbruecker/linkding/blob/master/docker-compose.yml#L11-L12. Also remember to create a new container.

**Comment by onjour** [comment]
Finally it seems to be working. 

I believe this feature should be a bit more streamlined if possible, that said it's a great tool!
