### ISSUE TITLE
demo site account delete

### ISSUE THREAD

**Issue by twonethree** [sissbruecker/linkding#172]
I created an account in https://demo.linkding.link/ How do I delete it?
If I can't delete it, I request to delete the lhw213 account. Thank you.

**Comment by sissbruecker** [comment]
Done

**Comment by twonethree** [comment]
> 완료

Thank you.

**Comment by dennmuel** [comment]
Sorry for necrobumping this, but I have the exact same request for my account ("dennmuel").
An option to delete one's own account would generally seem handy to me.
Best regards and thanks in advance!

**Comment by sissbruecker** [comment]
@dennmuel Done
