### ISSUE TITLE
Docker image does not respect filesystem hierarchy

### ISSUE THREAD

**Issue by benpro** [sissbruecker/linkding#173]
I was wondering why the application configuration, system and data are stored inside `/etc`?

It would be ideal to respect [hier(7)](https://manpages.debian.org/bullseye/manpages/hier.7.en.html) and use `/etc` for configuration files only.

> /etc
> Contains configuration files which are local to the machine. Some larger software packages, like X11, can have their own subdirectories below /etc. Site-wide configuration files may be placed here or in /usr/etc. Nevertheless, programs should always look for these files in /etc and you may have links for these files to /usr/etc.

Please consider moving files to something like this:

- /etc/linkding/{*.py,assets,static,bookmarks} to /usr/local/share/linkding
- /etc/linkding/{*.sh} to /usr/local/bin/linkding
- /etc/linkding/{data,secretkey.txt} to /var/lib/linkding

**Comment by sissbruecker** [comment]
No specific reason, apart from me not being very familiar with Unix conventions.

However I don't see any argument for what this would improve? Do you see any potential issues from the current approach that might prevent the application from working or harming the user? From my perspective the Docker image is a black-box, and the user doesn't really care how it's structured internally as long as it works. It's not like linkding has an installation script that dumps files into the wrong places on your host system.

Also, moving the data folder would break every single installation, as everyone would need to update the mounted data directory. There would need to be a really good reason to do so.

**Comment by sissbruecker** [comment]
Closing as stale.
