### ISSUE TITLE
secretkey.txt should be in data directory

### ISSUE THREAD

**Issue by benpro** [sissbruecker/linkding#175]
This file should be stored in the Docker volume directory mapped to `/etc/linkding/data`.

**Comment by sissbruecker** [comment]
What would be the benefit for the user? It should be possible to mount a custom secret key into the container if you want to reuse it for some reason. Apart from that exposing the secret key to the mounted data folder could result in leaking it to other parties.

**Comment by sissbruecker** [comment]
Closing as stale.

**Comment by steakhutzeee** [comment]
Actually the file is exposed in secretkey.txt . Also, what's it for? It get recreated when deleted.
