### ISSUE TITLE
Timezone does not change when changing a variable "TZ" in docker

### ISSUE THREAD

**Issue by molejado** [sissbruecker/linkding#179]
Really like the image, but I have the problem of changing the time zone. When i change the variable tz = Europe/Moscow, server ignores timezone plus 3 and all bookmarks saves with a timezone minus 3 hours. Please tell how to fix this bug. 
Sorry if I presented the problem incorrectly, thank you for linkding.

![123](https://user-images.githubusercontent.com/95546757/144723256-a7541ae1-ace0-42b3-b6a5-2ebbe8c13322.png)

**Comment by sissbruecker** [comment]
Not sure where you got the `tz` variable from, but it's not something that is supported. linkding uses Django, which has a `TIME_ZONE` variable that can be set in the settings. By default, that variable is set to UTC: https://github.com/sissbruecker/linkding/blob/master/siteroot/settings/base.py#L118

You can change that by mounting a [custom settings file](https://github.com/sissbruecker/linkding/blob/master/siteroot/settings/custom.py) into the container at `/etc/linkding/siteroot/settings/custom.py`, and then setting the `TIME_ZONE` variable to something else:
```python
TIME_ZONE = 'Europe/Moscow'
```

Setting the timezone per user is not supported ATM.

**Comment by molejado** [comment]
Thank you, now the time zone is working correctly, I am very grateful to your project, I have a cup of coffee for you)

**Comment by FunctionDJ** [comment]
It would be awesome if setting the time zone was supported via Docker enrivonment (e.g. docker compose)

**Comment by wxyShine** [comment]
> 如果通过 Docker 环境支持设置时区（例如 docker compose），那就太棒了

Do you support setting time zone now?
