### ISSUE TITLE
[Feature Request] Displaying tags in mobile browser

### ISSUE THREAD

**Issue by molejado** [sissbruecker/linkding#180]
The tag cloud is not displayed in the mobile version of the browser:

![Screenshot_20211206_093609_com android chrome 1 of 1](https://user-images.githubusercontent.com/95546757/144808483-eac4860e-0274-485d-8f1d-279b69b2f9d4.png)

If switch to display for PC, the tag cloud is not hidden:

![Screenshot_20211206_093616_com android chrome 1 of 1](https://user-images.githubusercontent.com/95546757/144809201-becfbf52-b3ac-43a7-85e7-dd58d0fa833a.png)

Can you add tag cloud link to hamburger menu?

![Screenshot_20211206_104238_com android chrome копия 1 of 1](https://user-images.githubusercontent.com/95546757/144809403-940b92ab-38de-4628-bd5e-a5b785bc1bc6.png)

Search by tags solves the problem, but with a large number of tags it can be difficult to remember, in this case the visual tag cloud helps a lot. Thanks for your project.

**Comment by sissbruecker** [comment]
The tags are intentionally hidden for smaller screen sizes ATM. Providing an option to display the tag list for smaller screen sizes as well would be a nice improvement.

Adding a menu item to the burger menu does not make sense for me, these items are all links that lead to another page. For the tags you rather want a solution that allows you to stay on the same page, and that allows you to add multiple tags to the search query.

**Comment by gingerbeardman** [comment]
maybe they could come after all the bookmarks?

thoughts
- need an easy way to jump down to the tags
- need an alphabet at the top of the tag list to jump within it
- tag search?

**Comment by BeecherNetworks** [comment]
I'd prefer it in the menu on a separate page, as per OP.

**Comment by dahamsta** [comment]
I'd prefer it in the menu on a separate page, as per OP.

**Comment by bleomycin** [comment]
Loving linkding, this would be a valuable addition. I'm unable to remember all of my tags to be able to search for them, browsing is critical.

**Comment by ItsNoted** [comment]
Hoping tags can be added to mobile browsers soon. When I found out they were hidden today it was a big disappointment as most of my traffic uses mobile devices.

**Comment by gingerbeardman** [comment]
If you are handy editing the contents of the docker container you can override the style.

Alternatively, you can use the URL: https://example.com/bookmarks/partials/tag-cloud/active

**Comment by ItsNoted** [comment]
> If you are handy editing the contents of the docker container you can override the style.
> 
> Alternatively, you can use the URL: https://example.com/bookmarks/partials/tag-cloud/active

Hmmm. Well, 2 things.

1. It's an unstyled pile of links on the page.
2. It cannot be seen publicly.
The main thing is I need the tags to be seen by public viewing guests.

This is a good start though :)
