### ISSUE TITLE
Case-insensitive search does not work with non-ASCII characters

### ISSUE THREAD

**Issue by molejado** [sissbruecker/linkding#181]
Is it possible to search with ignoring uppercase / lowercase characters, not in tags, in description and title search?

![Безымянный](https://user-images.githubusercontent.com/95546757/144919404-b91436f0-6a76-49bb-aaf9-1c5d7f1941d9.png)

![Безымянный2](https://user-images.githubusercontent.com/95546757/144919406-88c40208-cbeb-4931-89e4-f78404eef0a3.png)

**Comment by sissbruecker** [comment]
Case insensitive search works with ASCII characters, but not with Unicode characters. That seems to be a limitation of Sqlite, out of the box it only supports case-insensitive string comparisons for ASCII characters: https://sqlite.org/faq.html#q18

Fixing this would apparently require compiling a custom build of Sqlite to include the ICU extension, which provides support for Unicode string comparisons, as well as implementing a custom Django database backend to make use of the custom Sqlite build. I'm afraid that's a bit out of my experise, and even if someone could contribute a solution, I'm not sure if I'm comfortable with maintaining this (for example keeping the custom Sqlite build in sync with the latest patches etc).

The only other solution I can think of is to use a different database like Postgres, however I'm not sure if linkding will work with other databases, and I do not provide support for for that use-case. Maybe someone can give it a try to make linkding work with Postgres, or even contribute a docker-compose setup.
