### ISSUE TITLE
[question] Automated description injection?

### ISSUE THREAD

**Issue by asitemade4u** [sissbruecker/linkding#191]
Hi, and bravo @sissbruecker for this excellent product -- I have tried them all...

- As I am collecting bookmarks from my mobile phone and tablet, I rely upon a synced `todo.txt` file (using Syncthing and Simpletask in Android).
- As mentioned in #186 I have developed a procedure that parses the `todo.txt` file and imports both bookmarks and tags (and tags in bookmarks) into Linkding's database. So far, all good and straightforward.

I would like now to **automatically download the description for each imported bookmark in batch** or through an instruction, just like when you add a new bookmark and that Linkding queries the original website and injects the description into its record.
Is that possible? 

NB. Currently, I have to:

1. enter each record in Linkding
2. wait for some time for the description to be injected
3. validate the record
4. wait again for the record to be saved

**Comment by kzshantonu** [comment]
@asitemade4u hi. I have a workaround for you for the time being. You can import your txt file into raindrop.io (free). Raindrop SHOULD automatically grab titles and subtitles. Then export an HTML and import that into linkding

**Comment by sissbruecker** [comment]
@asitemade4u While your solution is clever, very few people would actually work like that (modify the database yourself), so there's a very low incentive to implement something like this. However there is a semi-related ticket to scrape bookmark title and description after running the bookmark import (https://github.com/sissbruecker/linkding/issues/43), which I would find more valuable. So for your case you would have the option to change your script to produce a Netscape HTML bookmarks file, and then import that through the UI. Of course that would require a manual step. To make this automatic I would suggest to use the REST API to insert bookmarks instead, and then open a new issue to request that adding/modifying bookmarks through the REST API should trigger scraping of the website's title and description.

**Comment by sissbruecker** [comment]
I just double-checked and the REST API actually triggers the scraping already - it's what the extension uses after all.

After some thought I don't think I want to support use-cases around modifying the database manually. If you want to automate something around linkding, then the REST API is the way to do it. While it wouldn't be too much effort to add a CLI command, I don't see much value in adding, and then maintaining that. Likewise I can't see any other reason to manually trigger this process from the UI, except that it doesn't yet trigger automatically for imported bookmarks, which would be covered by #43. I'll close this for now.

**Comment by asitemade4u** [comment]
OK, I agree with you and I will definitely use the API.

**Comment by sissbruecker** [comment]
Cool, also if you come up with a script for importing text files over the REST API, feel free to share it here, or open a PR to add it to the [Community](https://github.com/sissbruecker/linkding#community) section.

**Comment by asitemade4u** [comment]
Of course I will.
I use Insomnia which provides a straightforward way to exchange REST API scripts
