### ISSUE TITLE
[improvement] Search bookmarks without tags

### ISSUE THREAD

**Issue by asitemade4u** [sissbruecker/linkding#192]
I like to tag collected bookmarks in batch, by theme.
It would help a lot to be able to search all Linkding **records that have not been tagged yet**.

**Comment by asitemade4u** [comment]
More generally, it would be IMO a good idea to allow **plugins** in Linkding.
I understand your _legitinate_ desire to keep Linkding simple and fast. However it is lacking some functions that could be supplemented by plugins -- to name a few:

- tag management: merge tags, display tags as a cloud
- search improvements: search non-tagged entries
- imports from other platforms: here Linkding is really lacking as most users IMO DO NOT come from standard browser bookmarks but from other bookmark management platforms

**Comment by sissbruecker** [comment]
Opened a PR to address this: #226 

Also created a separate Docker image that can be used for testing the new feature before merging.

**Comment by asitemade4u** [comment]
THX! Will test it right away

**Comment by asitemade4u** [comment]
It works great, THX.
I now have to deal with the tagging of 53 pages of entries...
