### ISSUE TITLE
CSS Stylesheet presented as text/plain

### ISSUE THREAD

**Issue by derekslenk** [sissbruecker/linkding#2]
I am running linkding behind a Traefik reverse proxy and the stylesheets won't load over https because:

> The stylesheet https://linkding.url.tld/static/index.css was not loaded because its MIME type, “text/plain”, is not “text/css”.

**Comment by derekslenk** [comment]
Nvm, seems to be a traefik issue.

**Comment by bl1nk** [comment]
Could you add how you solved it? I was able to find [#3131](https://github.com/containous/traefik/issues/3131) without a workaround or fix.

**Comment by derekslenk** [comment]
I am hoping this gets into the 2.0 tag of Traefik soon. I haven't dug in to see what branches the fix is in yet

**Comment by derekslenk** [comment]
I am kind of bummed since I really want to use Linkding in production...it fits my needs perfectly and I just need to be able to access it from multiple locations. Maybe I throw an nginx server in there somewhere

**Comment by sissbruecker** [comment]
If it helps someone - I had the same issue when using [Caddy](https://caddyserver.com/) as reverse proxy. My Caddy configuration that fixes it looks like this:

```
linkding.myserver.tld {
  proxy / localhost:9090 {
    transparent
  }
  mime {
    .css text/css
  }
}
```

**Comment by derekslenk** [comment]
I do not think changing the mime type is possible in traefik. Can't it be done in the container? The proper way is to return the mime type anyways...

**Comment by sissbruecker** [comment]
@derekslenk Good catch, the issue was actually the uwsgi configuration / missing mime support in the Docker container. I updated the Docker image to add mime support, that seems to fix it for me.

**Comment by derekslenk** [comment]
I will definitely check that out in a bit. I had started looking at the code but didn't get far enough
