### ISSUE TITLE
Checking all in bulk edit only selects first page

### ISSUE THREAD

**Issue by gingerbeardman** [sissbruecker/linkding#208]
I expected checking the top box, selecting all items, to operate on all pages of links.

However, it only operates on the first page.

I have 24 pages of links matching this search.

<img width="705" alt="Screenshot 2022-02-22 at 22 01 57" src="https://user-images.githubusercontent.com/49612/155226992-a80e5b84-3211-49b4-95eb-f5b495466f28.png">

**Comment by gingerbeardman** [comment]
I ended up doing this (removing a tag) through admin interface

**Comment by sissbruecker** [comment]
I think this could be very surprising for users if bookmarks that are currently not visible are modified as well. And it would not be possible anymore to just select a single page, which can be useful to iteratively do something.

Django Admin actually uses a separate action for this, which seems like the right way to go about this.

![Bildschirmfoto 2022-05-14 um 02 39 46](https://user-images.githubusercontent.com/357820/168404252-58a7ce21-d185-47af-8d6c-70840a3ab463.png)

**Comment by gingerbeardman** [comment]
That would work for me.
