### ISSUE TITLE
Group Management

### ISSUE THREAD

**Issue by dojo90** [sissbruecker/linkding#214]
I have not been able to find any information about creating groups etc. yet.

Was that in the UI or backend currently only as a placeholder for future extensions?

![grafik](https://user-images.githubusercontent.com/17551597/155691554-bc2ef68f-1e4f-4c7c-9613-7b2c59b5e4f9.png)

**Comment by sissbruecker** [comment]
This is just a default entity that comes with the authentication system of the framework that linkding uses. It has no practical use, apart from differentiating admin users from regular users.
