### ISSUE TITLE
Share Bookmarks between users

### ISSUE THREAD

**Issue by dojo90** [sissbruecker/linkding#215]
I am currently looking for a solution to manage links from the internet with my girlfriend.

I am thrilled with the performance and the existing integration of Firefox/Chrome! A big praise from my side! 🎉👍

What I am currently missing is the ability to share links between multiple users. Is this feature already included or planned for the future?
Currently we would both have to use the same account. 🤔

**Comment by sissbruecker** [comment]
That's not possible at the moment, but I agree that sharing bookmarks with individual users can be useful, moreso than having publicly visible bookmarks (#70 ). For the most part the application is currently designed to be used by individuals, and my assumption is that the overwhelming majority of use-cases are just that - a single installation is used by a single person.

No plans to work on this for now, but people can always vote (👍) on tickets to give an indication what to focus on when adding new features.

**Comment by petersem** [comment]
@sissbruecker 
Please add url sharing.

This would be very useful, especially if it could be done for shared groups or links.
