### ISSUE TITLE
admin interface bookmarks search

### ISSUE THREAD

**Issue by kzshantonu** [sissbruecker/linkding#216]
Hi, what's the best way to search all URLs of a single domain? Wildcard didn't seem to work

**Comment by sissbruecker** [comment]
The admin view searches the URL, so you can just enter the domain name:

![Bildschirmfoto 2022-03-01 um 20 36 24](https://user-images.githubusercontent.com/357820/156236582-f68c5a12-4ff2-4cd8-a2f3-b45353ff5d6a.png)

There are no wildcards or any other smart things in the search mechanism AFAIK, it's just a simple contains filter.
