### ISSUE TITLE
[Enhancement] - Adding email support via smtp to allow users to create their own accounts

### ISSUE THREAD

**Issue by JohnFawkes** [sissbruecker/linkding#217]
Would it be possible to add support for users to create their own accounts instead of admins having to do it. or just adding a register button like the demo

**Comment by sissbruecker** [comment]
The main problem with public registration is how you would prevent random people on the internet from registering accounts on your self-hosted application? Even if this would be a configurable option, I can see how people might not think of that aspect and just configure it anyway, which opens up ways for abuse.

In #42 I proposed adding an invitation workflow instead, where an admin can invite users per mail. The admin still has to take action here, but it's less weird than them having to define a user name and password.

**Comment by sissbruecker** [comment]
I'll close this in favor #42. I think in a first step adding support for SMTP is overblown, sharing the invite URL manually would be a lot easier, and quicker than having to configure an SMTP server first.
