### ISSUE TITLE
[Feature Request] Search while typing

### ISSUE THREAD

**Issue by DUOLabs333** [sissbruecker/linkding#223]
As the user types, searches should automatically be run. It's best to make it toggleable in "Settings".

**Comment by sissbruecker** [comment]
Did you notice that the search input will provide you with a menu of search results that you can select, or do you have a problem with that.

In general linkding generates its HTML by rendering templates on the server, which means what you see in the browser is mostly going to be static, and any UI update requires a page refresh. For some interactive parts (auto-complete, and search) linkding uses some Javascript components to provide quick feedback without a reload. It's very unlikely that this paradigm is going to change, as it is simple to maintain and mostly works very well for the use-cases that linkding has. Closing this for now, if you have an issue with the search input not providing helpful results, please file an issue for that.

**Comment by DUOLabs333** [comment]
Yeah, I ended up patching it to add more configurable options for auto-complete and left it at that.

**Comment by sissbruecker** [comment]
@DUOLabs333 Care to share, or do you have a fork? I think search is one of the top features, so if there is an opportunity to enhance it, I'm willing to take a look.

**Comment by DUOLabs333** [comment]
It's not that much of an improvement --- I just added options to search by title, by URL, by description, or by all three (the default).

**Comment by DUOLabs333** [comment]
It seems autocomplete doesn't kick in before 3 characters.

**Comment by sissbruecker** [comment]
Just noting that this is intended, and a common behavior for searching. Otherwise you get lots of irrelevant stuff.

**Comment by DUOLabs333** [comment]
What if the title is only two characters long? Maybe offer a setting for it, with 3 as the default?
