### ISSUE TITLE
Mass deleting leads to a bad request 400 error

### ISSUE THREAD

**Issue by aashish108** [sissbruecker/linkding#225]
I am trying to mass delete a few thousand bookmarks but it does not work and leads to a bad request 400 error! What can I do pls? I know I can reset the DB but surely there must be a way to manage bulk edits?

Cheers

**Comment by sissbruecker** [comment]
I assume you are trying to do this through the Admin UI? I had the same issue recently while trying to bulk delete several thousand entries. Not sure why it happens, might be a memory or timeout issue.

One solution I can think of is to delete the bookmarks in batches, by trying to apply a filter that only returns, let's say a few hundred bookmarks.

**Comment by aashish108** [comment]
Yeah via the admin UI. I was actually batch deleting then realised the futility of it considering I have 3000 bookmarks to delete!

**Comment by sissbruecker** [comment]
Tried this on a locally running server with ~2000 bookmarks, which works (very fast actually). So I figure this is either a performance issue, or a timeout issue. I don't see this as a major use-case, and the feature comes from the Django Admin anyway, so I'll close this for now.

**Comment by zbyna** [comment]
I was successful in deleting  5600 bookmarks at once.  It seems that it is not a performance or a timeout issue.  There is [DATA_UPLOAD_MAX_NUMBER_FIELDS](https://docs.djangoproject.com/en/2.2/ref/settings/#data-upload-max-number-fields) in Django settings. 

I modified the original container and created a new image with updated setting ```DATA_UPLOAD_MAX_NUMBER_FIELDS=10000```  Deleting was working after container had been created from modified image.  Is it possible to enable customise this value in linkding settings?
