### ISSUE TITLE
Automatically update README.md towards Docker Hub

### ISSUE THREAD

**Issue by GioF71** [sissbruecker/linkding#228]
It would be nice to synchronize the documentation from your README.md file available on GitHub towards Docker Hub, automatically.
There is a GitHub Action available for this task: [here](https://github.com/meeDamian/sync-readme).
I see you are using GitHub Actions already, although not for building images as far as I understand. In case you want to build images automatically on every push to the main branch, synchronizing the README.md might remove a manual task.
Let me know if you would like me to provide a PR for an initial draft of the implementation (both automatic build and documentation synchronization).

Thank you for the great software you have built, I use it basically everyday

**Comment by sissbruecker** [comment]
Thanks for the offer, but I think the current setup is fine. Having automated builds is not really necessary, if there is something to release I usually follow up on that. Having some blurb on Docker Hub, and a link to the repo would be nice, but syncing the README is a bit overblown - most people engage through Github anyway.
