### ISSUE TITLE
[cosmetic] Batch Operations

### ISSUE THREAD

**Issue by asitemade4u** [sissbruecker/linkding#237]
Batch operations are great but the GUI could be improved: 

1. Select entries
2. Click the **Batch Operations** icon (which is not too clear as it looks to me like a printer...)
3. Select entries to modify

Say you want to add a new, existing tag:
1. You enter the tag in the **Tags** field
6. then, quite naturally, you click the **Add** link
7. it WON'T WORK because **the cursor has to be out of the **Tags** field for it to work**

I understand the programmatic logic (a field is validated only when exited) but in that case it IS exited when clicking on the **Add** link...

**Comment by sissbruecker** [comment]
>     1. You enter the tag in the **Tags** field
> 
>     2. then, quite naturally, you click the **Add** link
> 
>     3. it WON'T WORK because **the cursor has to be out of the **Tags** field for it to work**

I can not reproduce this. Can you share a screencast? In general there is no validation on the field, so I can't see what would be blocking the add button.

**Comment by sissbruecker** [comment]
Closing as stale
