### ISSUE TITLE
Add a search box to select tags

### ISSUE THREAD

**Issue by asitemade4u** [sissbruecker/linkding#239]
Whan one has defined a lot of tags, the tag list in the right sidebar becomes unmanageable.
It would be practical to add a search box that would allow selection the tags in the sidebar.
Again, as previously described in #227, the search should be performed on **parts** of the tags, not only on their first letters.

**Comment by sissbruecker** [comment]
I would prefer to keep the tag list server-side rendered. You can get auto-complete for tags in the existing bookmarks search field. Just type a `#` and then start typing a tag name. I'd rather consider improving that than adding another search field / auto-complete.

Not convinced about searching for parts of tags, that could actually make it harder to find something if you have lots of tags. I'll keep #227 open and see if there is interest.

**Comment by asitemade4u** [comment]
Let's agree to disagree on that one ;o))
Far from making it more difficult to search, it limits the number of choices.
If you know the product, please have a look at digiKam (a photo management application) which deals with tags in a very good way IMO>
