### ISSUE TITLE
Exact date added on hover

### ISSUE THREAD

**Issue by clach04** [sissbruecker/linkding#240]
Any interest in making the exact date of the bookmark being added available on hover? This matches a few sites (for example GitHub issue comments) and something I'm personally interested in.

Quick hack:

    diff --git a/bookmarks/templates/bookmarks/bookmark_list.html b/bookmarks/templates/bookmarks/bookmark_list.html
    index 5fa410c..fcd72f0 100644
    --- a/bookmarks/templates/bookmarks/bookmark_list.html
    +++ b/bookmarks/templates/bookmarks/bookmark_list.html
    @@ -36,7 +36,7 @@
                             <a href="{{ bookmark.web_archive_snapshot_url }}"
                                title="Show snapshot on web archive" target="{{ link_target }}" rel="noopener">
                             {% endif %}
    -                        <span>{{ bookmark.date_added|humanize_relative_date }}</span>
    +                        <span title="{{ bookmark.date_added }}">{{ bookmark.date_added|humanize_relative_date }}</span>
                             {% if bookmark.web_archive_snapshot_url %}
                             <span>¦</span>
                             </a>
Screenshot:

![image](https://user-images.githubusercontent.com/424032/161407860-612f7ce9-d42d-4ff0-863f-4399c4e35103.png)

**Comment by sissbruecker** [comment]
Mhh not really, I can imagine that there might be a more useful purpose for the title attribute on the title element in the future, for example showing the full title in case it's cut off like in the screenshot you posted. Frankly I don't see the use-case, bookmarks get old really fast, and I assume most people are not interested whether they added this bookmark after lunch.

You can configure the date display to show an absolute date, though it only formats an actual date if the bookmark is older than a week.

**Comment by clach04** [comment]
Thanks @sissbruecker  I some how missed the "Bookmark date format" setting of "Absolute" in settings. Also my suggestion above does NOT work if Absolute setting is used 😆 

Of course now I more questions ;-)
