### ISSUE TITLE
Add managed hosting option to docs

### ISSUE THREAD

**Issue by m3nu** [sissbruecker/linkding#245]
Over at [PikaPods.com](https://www.pikapods.com/), we are on a mission to make great open source apps, like Linkding more accessible and simpler to get started with.

We already offer Linkding in our “app store” and reception has been pretty good from the start.

So I wanted to check if there is interest in adding PikaPods as additional deployment option in the documentation. This would help an even wider audience to benefit from the project. We also offer revenue sharing and sponsorships to enable users to support the projects they use without much friction.

Looking forward to hearing your opinion on this. Thanks for the consideration!

**Comment by sissbruecker** [comment]
@m3nu I'm interested in this, I think self-hosting still has a high barrier of entry, and I'm open to making the app more accessible. I have just restructured the docs, and added a section for managed hosting options: https://github.com/sissbruecker/linkding#managed-hosting-options. We could mention PikaPods there as well.

For public disclosure, I don't intend to make profit with this project, if I choose to participate in the revenue sharing I would commit to donating the proceeds from that.

I feel it makes sense to discuss this personally, feel free to reach out using the following mail address: 588ex5zl8@mozmail.com

**Comment by m3nu** [comment]
Great! Just added my PR. Hope the style is suitable.

Will send my other comments by email to keep this issue focussed.
