### ISSUE TITLE
Http Shortcuts not working with provided json file 

### ISSUE THREAD

**Issue by aashish108** [sissbruecker/linkding#247]
Hey all! I filled the correct variables as the docs in this repo said with instance url, tag and api token for the HTTP shortcuts app on android but I get this error, does anyone know what it's complaining about pls? The error is chopped off. The LinkDing app works though. Not sure if HTTP Shortcuts app is the issue tbh. 

![Screenshot_20220512-112916_HTTP Shortcuts](https://user-images.githubusercontent.com/7046226/168051210-eaa48173-d5a6-4852-8538-8b282c04fa66.jpg)

**Comment by sissbruecker** [comment]
It looks like validation of the HTTPS certificate failed. Are you hosting linkding with HTTPS / a valid certificate? If not, then the app, or Android itself might block the request because the connection is not considered secure.

**Comment by aashish108** [comment]
> It looks like validation of the HTTPS certificate failed. Are you hosting linkding with HTTPS / a valid certificate? If not, then the app, or Android itself might block the request because the connection is not considered secure.

I checked and its all valid. No SSL issues when opening the link on Android via chrome nor on desktop. Yeah, it's https. The cert I bought. I am stumped lol.

**Comment by aashish108** [comment]
Ok I fixed it! I had to reimport my SSL certificate and add a cert I missed! Cheers for the help.
