### ISSUE TITLE
Increase limit on bookmark URL length

### ISSUE THREAD

**Issue by hirusi** [sissbruecker/linkding#25]
I tried to add a URL but got:

> Ensure this value has at most 200 characters (it has 265).

This seems pretty low as clean URLs even without tracking/marketing parameters can often go beyond 200 chars. No such complaint was made for any link at the time of import so it does seem to work (or does it trim such URLs while importing?)

Would request for an increased limit on bookmark URL length.

**Comment by sissbruecker** [comment]
@hirusi Good catch! The model did not specify a limit, however Django applies a default limit of `200`. Increase the limit to `2048` for now. Removing the limit would also be possible but is a larger change with setting up a custom URL field including validation.
