### ISSUE TITLE
Deploy instructions for fly.io

### ISSUE THREAD

**Issue by fspoettel** [sissbruecker/linkding#251]
Thank you very much for this nice app! :100: 

I have written down instructions for deploying linkding to [fly.io](https://fly.io). I have also integrated [litestream](https://litestream.io) for automatic database backups to cloud storage.

Instructions and code can be found [here](https://github.com/fspoettel/linkding-on-fly).

**Comment by sissbruecker** [comment]
Nice job! I was planning to restructure the docs a bit, and will definitely fit this in somehwere.

BTW did you notice this: https://github.com/sissbruecker/linkding-fly-io. I'm currently using this to run the linkding demo instance. It actually works with 256GB, bit I think I reduced the number of threads / processes in the uWSGI config to get it stable. Looks like some instructions are already outdated, like the minimum volume size. Also nice to see that you now can get SSH access to your container.

**Comment by fspoettel** [comment]
Oh wow, I could have saved myself some work! :stuck_out_tongue: I'll give that config change a try, would be nice to take advantage of the free VMs this way. Thanks!

**Comment by sissbruecker** [comment]
I restructured the docs a bit, and added a section for managed hosting options, mentioning your project: https://github.com/sissbruecker/linkding#managed-hosting-options
