### ISSUE TITLE
date formatting question

### ISSUE THREAD

**Issue by clach04** [sissbruecker/linkding#254]
Is there anyway to control the date display format?

From https://github.com/sissbruecker/linkding/issues/240#issuecomment-1126579769 I'm now using absolute date formats in the settings - but I'd like ISO format dates, i.e. 2022-05-14.

I poked around https://docs.djangoproject.com/en/4.0/ref/settings/#date-format and the best I can come up with is hacking the base.py:

    diff --git a/siteroot/settings/base.py b/siteroot/settings/base.py
    index ca522e8..eac955d 100644
    --- a/siteroot/settings/base.py
    +++ b/siteroot/settings/base.py
    @@ -122,6 +122,10 @@ USE_I18N = True
     USE_L10N = True

     USE_TZ = True
    +USE_L10N = False ## clach04 hack, hopefully force usage of SHORT_DATE_FORMAT https://docs.djangoproject.com/en/4.
    0/ref/settings/#date-format
    +SHORT_DATE_FORMAT = 'Y-m-d'  ## clach04 hack
    +DATE_FORMAT = 'Y-m-d'  ## clach04 hack
    +

     # Static files (CSS, JavaScript, Images)
     # https://docs.djangoproject.com/en/2.2/howto/static-files/

I'm sure there is a better way.

**Comment by sissbruecker** [comment]
That looks correct, the bookmark date display is using Django's `SHORT_DATE_FORMAT`: https://github.com/sissbruecker/linkding/blob/master/bookmarks/utils.py#L34

If I remember correctly by default Django uses a format the matches the locale that was detected from the request, so it should be localized. The is no user setting for the date format ATM, so modifying the Django settings is the best way to do it.

If you want to override it you don't necessarily have to modify the base settings file. There's also an option to mount a `custom.py` settings file into the container, which will then automatically be picked up by the application: https://github.com/sissbruecker/linkding/blob/master/siteroot/settings/custom.py. The mount path should be something like `/etc/linkding/siteroot/settings/custom.py`.

**Comment by sissbruecker** [comment]
Closing as answered
