### ISSUE TITLE
Suggestion: Fetch Favicon to all bookmarked website

### ISSUE THREAD

**Issue by M4NH3X** [sissbruecker/linkding#257]
Hello there,
This is a suggestion to add favicon to bookmarked website. Currently it's plain and all text info, adding favicon will help us recognize the bookmarked website right away.

**Comment by 0x9394** [comment]
if someday this feature is added, pls make it optional.

**Comment by sissbruecker** [comment]
Resolved with https://github.com/sissbruecker/linkding/pull/390
