### ISSUE TITLE
Enhancement: return to same page we were on after editing a bookmark

### ISSUE THREAD

**Issue by hirusi** [sissbruecker/linkding#26]
I am retrospectively trying to add tags to all my bookmarks. Once I reached page 2, edited a bookmark, and saved it, I was redirected back to the homepage (page 1). I'm having to manually go back to page 2 and edit the next bookmark.

A good UX would be to go back to the same page we were on before hitting the edit button.

**Comment by hirusi** [comment]
This appears [to be configured here](https://github.com/sissbruecker/linkding/blob/master/bookmarks/views/bookmarks.py#L73). Since we don't know what page we were on when we opened the edit form, this might involve either checking the user history at the server level (redirect to last known bookmark index page with pagination) or by attaching a new parameter in the form data itself.

Both solutions look to be rather odd, but I'm thinking out loud here. 🤷‍♀️

**Comment by sissbruecker** [comment]
@hirusi Thanks, this is a very sensible request. I implemented a solution where the app redirects to the filtered / paged view after editing or deleting a bookmark.

The technical solution was a bit involved, but in general the bookmark index view simply passes a `return_url` param to the edit / delete views. These views can then use that param to redirect to that URL after executing their logic.

**Comment by sissbruecker** [comment]
@hirusi Also feel free to test this a little bit, I had to make quite a few changes around several redirects.

I'll try to make a Docker release now.
