### ISSUE TITLE
Getting title not working for articles from nytimes.com

### ISSUE THREAD

**Issue by ahuse** [sissbruecker/linkding#262]
When adding articles from the [New York Times](https://www.nytimes.com/international/), the title of the article is not fetched.
They are using the `<title>`-tag, but with a `data-rh="true"` addition. Maybe this breaks something?

So far, nytimes.com is the only website where I have noticed this behavior.

**Comment by sissbruecker** [comment]
Many of the larger websites have a bot-detection that prevents automated access to the page content. I added some measures to circumvent bot-detection in #263 , seems to work for the page that you linked.

**Comment by ahuse** [comment]
Just updated and, yes, it works. Thanks for quick fix!
