### ISSUE TITLE
Select results with keyboard

### ISSUE THREAD

**Issue by danielyrovas** [sissbruecker/linkding#266]
I currently use LinkDing as my new tab page and its working pretty nicely, however there a few things that I've thought could be improved. Currently there is no keyboard selection (that I could find) for either saving a bookmark (in firefox with the addon) or selecting and opening the results on the search page. It would be awesome if hitting a key (such as `CTRL-1`, `CTRL2`..) could open the first few results.
Additionally I thought it could be cool to be able to directly query a search engine (perhaps by prefixing the search with a specific letter or hitting (e.g.) `g` instead of `s` to focus the search bar.

**Comment by kencx** [comment]
Regarding opening links on the page with keys, you could use a browser extension like [Vimium](https://github.com/philc/vimium) or [Tridactyl](https://github.com/tridactyl/tridactyl).

**Comment by sissbruecker** [comment]
Shortcut for saving a bookmark with the extension: Alt+Shift+L
The extension also allows to search bookmarks by typing `ld` followed by a space in the browser's address bar, results can be navigated with keyboard from there.

I'll leave this open as a possible enhancement to make search results in the app navigatable.
