### ISSUE TITLE
Update API method requires URL?

### ISSUE THREAD

**Issue by bachya** [sissbruecker/linkding#267]
The API [docs](https://github.com/sissbruecker/linkding/blob/master/docs/API.md#bookmarks) for updating a bookmark say:

> ### Update
>
> ```
> PUT /api/bookmarks/<id>/
> ```
> 
> Updates a bookmark. Tags are simply assigned using their names.
> 
> Example payload:
> 
> ```json
> {
>   "url": "https://example.com",
>   "title": "Example title",
>   "description": "Example description",
>   "tag_names": [
>     "tag1",
>     "tag2"
>   ]
> }
> ```

This seems to indicate that as long as the bookmark ID is provided in the URL, any/all of those payload parameters can be altered. However, when I attempt to update, say, a title of an existing bookmark:

```sh
curl -X "PUT" "http://127.0.0.1:8000/api/bookmarks/BOOKMARK_ID/" \
     -H 'Accept: application/json' \
     -H 'Authorization: Token REDACTED' \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{ "title": "TEST" }'
```

...I get the following response:

```json
{
  "url": [
    "This field is required."
  ]
}
```

I would expect that in this case, the bookmark would retain all its original values and be updated only with the new title. Am I incorrect there? Is it architecturally expected that I need to provide all parameters in this call, even if their values aren't changing?

**Comment by sissbruecker** [comment]
It looks like `PUT` is always a full update, and you should use `PATCH` for a partial update. However the current API implementation does not support `PATCH`, as it always tries to access all fields when a model is updated, which results in key errors if you don't provide all these fields: https://github.com/sissbruecker/linkding/blob/master/bookmarks/api/serializers.py#L47-L52

**Comment by bachya** [comment]
Got it. So, I should plan on first retrieving the bookmark (to get its existing values), then doing an update?

**Comment by sissbruecker** [comment]
That, or submit a PR for adding `PATCH` support 🙂

**Comment by bachya** [comment]
I'm unclear – add a separate API route that combines `PATCH` support with this use case? Or modify the existing `update` route to use `PATCH` instead?

IMO, the `update` route should not require a complete data set, so I suggest the latter. I'll work on a PR, and we can discuss it there.
