### ISSUE TITLE
Add API call to get linkding version

### ISSUE THREAD

**Issue by bachya** [sissbruecker/linkding#272]
Now that I've created [`aiolinkding`](https://github.com/bachya/aiolinkding) and [`linkding-cli`](https://github.com/bachya/linkding-cli), I'd like to be able to enforce minimum linkding versions (so that I can notify users if one of those packages requires a newer version than what they have). To that end, it'd be useful to have a simple API call that gets the currently running version.

I attempted a PR for this, but apologies, Django REST Framework is too opaque for my simple mind to understand. 😂

**Comment by kencx** [comment]
I can probably get started on this.

**Comment by sissbruecker** [comment]
Closing as resolved with https://github.com/sissbruecker/linkding/pull/392
