### ISSUE TITLE
Just a moment... title?

### ISSUE THREAD

**Issue by sprklinginfo** [sissbruecker/linkding#275]
Hi again, 
First day on Linkding after I run it from a docker. I added 4 or 5 bookmarks from extensions in Chrome and Firefox. All links are added successfully except one link with the title 'Just a moment...' . It sent me the bookmarked page correctly but the title seemed not to be fetched. Is this a bug I should raise?
I tried in chrome and the page I bookmarked is: Just a moment... https://linuxhandbook.com/nginx-reverse-proxy-docker/

I deleted and re-bookmark again and it still shows this placeholder title. I waited around 10-15 minutes to see there are some background work will fix it. Any reason it could not get the title? Thanks again.

**Comment by sissbruecker** [comment]
See https://github.com/sissbruecker/linkding/issues/118, closing as duplicate
