### ISSUE TITLE
[Enhancement] Don't refresh/fetch metadata everytime users edits saved bookmark

### ISSUE THREAD

**Issue by M4NH3X** [sissbruecker/linkding#283]
Noticed every time I edit any bookmark, linkding is fetching url and try to update metadata. It would be best if there is an opt-out option for this as I manually update the title/description etc. and will likely never be changing in the future.

This will also be helpful for users who don't want to unnecessary send requests and having an option to enable/disable will make both parties happy.

**Comment by sissbruecker** [comment]
Certainly makes sense to only refresh if the URL changes, otherwise you'll probably want to keep the old metadata.
