### ISSUE TITLE
"docker-compose down" always times out

### ISSUE THREAD

**Issue by kriswilk** [sissbruecker/linkding#284]
When I run `docker-compose down`, the SIGTERM sent to the container appears to be ignored. Instead, I have to wait 10 seconds (the default timeout) until a SIGKILL is sent to forcefully shut it down.

It's frustrating when I stop (or restart) a number of services and see that linkding is the only one that doesn't shut down right away. Can this be fixed?

**Comment by sissbruecker** [comment]
It can definitely be fixed if someone can figure out what's preventing the container from shutting down. Feel free to investigate.

**Comment by mckennajones** [comment]
@sissbruecker @kriswilk I opened a small PR to address this #368
