### ISSUE TITLE
Run Linkding without docker

### ISSUE THREAD

**Issue by amit510** [sissbruecker/linkding#288]
I was wondering if it is possible to run linkding without the docker, be able to run it in Proxmox LXC Debian 10? Any instructions? 

Thanks in advance.

**Comment by wahlm** [comment]
Why not using docker with Proxmox? Here is a note from [Linux_Container](https://pve.proxmox.com/wiki/Linux_Container):

> If you want to run application containers, for example, Docker images, it is recommended that you run them inside a Proxmox Qemu VM. This will give you all the advantages of application containerization, while also providing the benefits that VMs offer, such as strong isolation from the host and the ability to live-migrate, which otherwise isn’t possible with containers.

But still there are some instructions to install docker in a LXC: [setup-and-install-docker-in-a-proxmox-lxc-container](https://thehomelab.wiki/books/promox-ve/page/setup-and-install-docker-in-a-promox-lxc-conainer)

**Comment by amit510** [comment]
I may give that a try, thanks.

**Comment by noboevbo** [comment]
I still find the initial question interesting, a docker setup is not always possible, for example when the server is running *BSD. Theoretically, one should be able to reproduce the manual deployment using the Dockerfile, in principle there are some build steps of Django that can be implemented with appropriate venvs even without Docker. Also the NPM steps etc. should not be a major problem. Am I missing a step here that could be problematic with a manual installation?
