### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by fil0sik** [sissbruecker/linkding#303]
I installed linkdink in docker. Everything is fine, but how to teach it to run via https?
(debian 11/apache)

**Comment by sissbruecker** [comment]
In general that is not part of the functionality of the Docker image. Instead you would usually add a proxy server in front of linkding, and then configure SSL in the proxy server. As you mentioned that you are already using Apache, you could take a look there. Other good choices for proxy servers would be nginx or Caddy. I use the later one, as the configuration is dead simple and it integrates with Lets Encrypt.
