### ISSUE TITLE
[Feature request] Tag categories/folders

### ISSUE THREAD

**Issue by ngoomie** [sissbruecker/linkding#314]
When using Linkding for bookmarks falling under many different topics, the amount of tags can get a bit unwieldy and make the tag sidebar feel a bit disorganized. As an example, I have tons of bookmarks on linguistics, and a bunch on programming (though this doesn't even cover everything ofc), and I like to be decently verbose with my tags, categorizing linguistics and programming bookmarks based off of what language(s) they apply to if applicable, as well as what specific topic they cover (i.e. I have tags like "writingsystems", "soundchange" and "grammar" among others for linguistics, and tags like "webdev" and "databases" for programming). Being able to have different categories or folders for tags if one desired would help a lot in making things feel neater, especially if the folders were collapsible. I personally don't even really want or need anything like nested categories or folders, just one level would be enough. Thank you very much for your time, even if this gets decided against!

**Comment by sissbruecker** [comment]
Thanks, it's an interesting idea to manually categorize tags. There's an[ existing issue](https://github.com/sissbruecker/linkding/issues/285) to add further categorization features, let's continue the discussion there.
