### ISSUE TITLE
[linkding eco system] linka! an app to search bookmarks in linkding more smoothly

### ISSUE THREAD

**Issue by cmsax** [sissbruecker/linkding#315]
[Linka! repository on GitHub](https://github.com/cmsax/linka)

Based on linkding's API, it includes following features:

- fulltext search
- instantly open search results
- multi-keywords and substract/exclude mode support
- PWA

Demo Gif:

![Demo Gif](https://raw.githubusercontent.com/cmsax/linka/main/screenshot/demo.gif)

It uses`MIT` license like linkding as well, I hope it will help us to search bookmarks more efficiently~

**Comment by gil** [comment]
That looks great! 😀

**Comment by sissbruecker** [comment]
Feel free to open a PR to add your project to the [community section](https://github.com/sissbruecker/linkding#community) of the README.
