### ISSUE TITLE
500 when trying to delete bookmarks

### ISSUE THREAD

**Issue by cmhobbs** [sissbruecker/linkding#317]
I had v1.8.0 installed with `db.sqlite3` living inside the container.  I copied the database out of the container and moved it to a local folder.  I downloaded the installation/update script, changed the volume to point to the new location, and ran the script.  Everything seemed to upgrade fine and now I'm on v1.13.0.  All features work with the exception of deleting a link.  It simply throws a 500 error without any other information.  

The only output from `docker logs linkding` when I click "Confirm" after delete is this: 

`[pid: 14|app: 0|req: 35/68] 172.17.0.1 () {62 vars in 1167 bytes} [Fri Aug 12 19:45:46 2022] POST /bookmarks/action?return_url=%2Fbookmarks => generated 145 bytes in 43 msecs (HTTP/1.0 500) 7 headers in 223 bytes (1 switches on core 0)`

Using the Django Admin link provided on the Settings page, I'm able to delete links with no problem at all.  I was able to reproduce this behaviour in `v1.12.0` and `v1.11.0` but I didn't try 9 or 10.

**Comment by cmhobbs** [comment]
When I downgraded back down to `v1.8.0`, I was able to delete bookmarks again but I couldn't add any (I suspect that errors on adding was due to migrations in later versions).  I get the same 500 when trying to delete bookmarks in versions `1.9.0`-`1.13.0`.  All other features are fully functional and I can still delete bookmarks via Django Admin.

**Comment by sissbruecker** [comment]
Sounds strange, deletion in general works with the latest version, so there must be some issue with the database.

I would give debugging this a shot if you can provide me a corrupted database.

**Comment by cmhobbs** [comment]
Your comment about the database made a lot of sense so I moved exported my bookmarks, created a fresh database, and imported my bookmarks.  Both before and after the import, I was once again able to delete items from the linkding ui.

I'm a little concerned about personal information potentially being in the thousands of bookmarks in my database so I'd rather not send one along.  I greatly appreciate you being willing to give that a try, though.  I think this issue can probably be considered resolved so I'll go ahead and close it.

Thanks so much for your time and thanks for linkding!
