### ISSUE TITLE
Allow automatic creation of the initial superuser

### ISSUE THREAD

**Issue by max-tet** [sissbruecker/linkding#322]
Right now, [an interactive command must be run](https://github.com/sissbruecker/linkding#user-setup) to create the initial superuser. In some deployment settings, this is awkward. In particular, this prevents a comfortable fully automated one-click install like on [Portal](https://docs.getportal.org/).

It would be great, if we could provide the username of the initial superuser as an environment variable. E.g.

* `LD_SUPERUSER_NAME`
* `LD_SUPERUSER_PASSWORD`

The second variable could be optional. If omitted, no password would be set and the user can only be authenticated with proxy authentication.

**Comment by sissbruecker** [comment]
Yeah, that sounds reasonable. Gave it a try in #323.

**Comment by max-tet** [comment]
Hey, that was quick!
The pull request is not merged yet. Is there a docker image tag for the pull request that I can use? Or need I build the docker image myself to try it?
