### ISSUE TITLE
Mass deleting leads to a bad request 400 error

### ISSUE THREAD

**Issue by zbyna** [sissbruecker/linkding#325]
This was mentioned in https://github.com/sissbruecker/linkding/issues/225 and sorted out as ``` performance issue, or a timeout issue``` .

It seems that it is not a performance or a timeout issue.  There is [DATA_UPLOAD_MAX_NUMBER_FIELDS](https://docs.djangoproject.com/en/2.2/ref/settings/#data-upload-max-number-fields) (Default: 1000) in Django settings. 

After having modified this setting ```DATA_UPLOAD_MAX_NUMBER_FIELDS=10000```  I was successful in deleting 5600 bookmarks at once. Is it possible to allow customizing this value in[ linkding options](https://github.com/sissbruecker/linkding/blob/master/docs/Options.md#list-of-options)?

**Comment by sissbruecker** [comment]
The setting controls how many form parameters may be received from the browser in a GET or POST request. The admin view does not use that many parameters. When you click the link for selecting all results, it just toggles a single hidden input (1 form parameter), it does not add several thousand parameters to the form. The actual items are then determined on the server during request execution, based on the search query.

I would guess that it was just coincidence that you got it working. Apart from that you can customize settings by mounting a custom settings file into the Docker container at the path `<linkding-root>/siteroot/settings/custom.py`.

**Comment by zbyna** [comment]
It seems your guessing could be successfully questioned. I am able to repeat deleting of several thousands records from admin interface every time I need it. It means no coincidence in my opinion. Same behavior is described here: https://stackoverflow.com/questions/55921865/django-admin-deleting-all-records-bad-request-400#55926091 . 
Yes it is possible to mount custom setting to container as described here: https://www.howtogeek.com/devops/how-to-mount-or-symlink-a-single-file-in-a-docker-container/, but it is a little bit extreme solution from my point of view.  Anyway thanks for reply.

**Comment by sissbruecker** [comment]
I double checked, the problem is actually with the confirmation page after you have selected to delete all bookmarks. That one can indeed send more than a thousand params, which results in an error. Still think that customizing the settings is good enough, though I would accept a PR for adding an option for this to linkding.

**Comment by zbyna** [comment]
I appreciate your double-checking! I will prepare a PR for sure, but I need some time for getting acquainted with the inners of Django.
