### ISSUE TITLE
[feature request] More space for description or custom css

### ISSUE THREAD

**Issue by mike2003** [sissbruecker/linkding#326]
When there are a lot of tags, the description is not visible. It does not fit on the same line as the tags. Now it looks compact, but useless. You need to provide a choice to the user in some way. This can be done through my css.

**Comment by hacdias** [comment]
I think this is quite a valuable idea. Either just an option to remove the `truncate` class from the description, or custom CSS altogether.

**Comment by sissbruecker** [comment]
Removing the `truncate` class reduces the readability significantly, as now every bookmark has a different height. Plus some descriptions can get very long.

How about an option that just puts the description into a separate line? Could also try to make this the default on mobile as it's a common problem there.

**Comment by mike2003** [comment]
"has a different height" no problem in css

**Comment by Fivefold** [comment]
I could also imagine something like a toggle through a button (e.g. an `Expand `option next to `Edit Archive Remove`) or by clicking on the description to remove the truncation. That way users could have both the compact layout and the full description when and where they actually want it.

If we can agree on some form of UX I could make a PR if you like @sissbruecker

**Comment by maxalentix** [comment]
I currently use Shaarli and I am considering using Linkding especially since it uses SQLite. 
Shaarli allows for very long multi-line descriptions, and I like this feature.  In Shaarli, the description and tags are on separate lines. Yes, each link then has a different height, but I don't mind that.

**Comment by Fivefold** [comment]
As a workaround I made a quick script that will remove the truncation of all description fields, at least on desktop browsers. You can add this to your linkding e.g. via [Tampermonkey](https://www.tampermonkey.net/)

```javascript
    const bookmarks = document.querySelectorAll(".bookmark-list div.description");
    bookmarks.forEach(bookmark => {
        bookmark.classList.remove("truncate");
    });
```

**Comment by jdaviescoates** [comment]
Just chiming in to say that I'd also like an option in the settings to display full descriptions. Thanks! :pray:

**Comment by jdaviescoates** [comment]
> As a workaround I made a quick script that will remove the truncation of all description fields, at least on desktop browsers. You can add this to your linkding e.g. via [Tampermonkey](https://www.tampermonkey.net/)
> 
> ```js
>     const bookmarks = document.querySelectorAll(".bookmark-list div.description");
>     bookmarks.forEach(bookmark => {
>         bookmark.classList.remove("truncate");
>     });
> ```

That's awesome, thank you :pray: :heart:

**Comment by jonatasbaldin** [comment]
Hi there, popping this up here.

We could have setting to enable/disable the description truncation, the description can be very useful!

Or a setting to customize the truncation size.

What do you think?

**Comment by jonathan-s** [comment]
@jonatasbaldin This is more or less what #624 intends to do.
