### ISSUE TITLE
Translation to another languages

### ISSUE THREAD

**Issue by AmadeusGraves** [sissbruecker/linkding#329]
Linkding is a perfect tool, the only problem is that isn't translated, in fact I think this is its main problem, people from other languages are not interested in supporting this project because it is not available in their language and they don't have the possibility to add it.

And it's easy to support translations, there are third-party software that make it easy for you.
https://www.smartcat.com/blog/top-translation-software-tools/

**Comment by AmadeusGraves** [comment]
when the internationalization is ready I will help with the translation into Spanish.

**Comment by AmadeusGraves** [comment]
And sorry my english its not ok but i try mi best. And i have to say, very nice work!

**Comment by AmadeusGraves** [comment]
Hi! I found this tool for translation. Its free so you can use it as much as you want.

https://www.reddit.com/r/selfhosted/comments/x75l0o/tolgee_localization_platform_opensource/

**Comment by sissbruecker** [comment]
Let's keep the discussion around localization in one issue: https://github.com/sissbruecker/linkding/issues/309
