### ISSUE TITLE
Behind a Reverse Proxy (NginxProxyManager)

### ISSUE THREAD

**Issue by danmed** [sissbruecker/linkding#338]
I'm having issues getting this running behind NginxProxyManager..

I have it set up with SSL to link.domain.co.uk

if i visit that URL then i get nothing.. however if i append /login to the end i get the login page.. but when i log in i then get a "Not Found" page..

I know it's something stupid i'm missing but any guidance would be appreciated!

**Comment by sissbruecker** [comment]
I can't really help with this, and it seems no one from the community can provide feedback. Closing.

**Comment by Snake16547** [comment]
stuck in the same boat!
Anybody had luck with nginx proxy manager?
Documentation is horrible

**Comment by Snake16547** [comment]
> stuck in the same boat!
> 
> Anybody had luck with nginx proxy manager?
> 
> Documentation is horrible

And it was just a slow dns-update problem -_-
