### ISSUE TITLE
Github API rate limit exceeded

### ISSUE THREAD

**Issue by BelieveOP5** [sissbruecker/linkding#341]
when opening settings page, i get error log like this:

<img width="779" alt="截屏2022-09-13 19 47 49" src="https://user-images.githubusercontent.com/16416594/189893272-e22879fb-0492-40f9-9f4e-3e99c82cd5d9.png">

and i find the error come from here:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/16416594/189893579-05e940ca-ecbd-46fa-8c88-d9886f718f0b.png">

finally, when i enter the request api into browser, i find it is Github API rate limit exceeded:

> `{"message":"API rate limit exceeded for 212.107.29.67. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}`

i think it'd better use another way to get latest release version. In addition, i use specific version instead of latest tag in docker, is it necessary to get latest release information in such a situation?

**Comment by sissbruecker** [comment]
That could definitely use some better error handling.

> i think it'd better use another way to get latest release version. 

How would you get the latest version without making a request against an API?

**Comment by BelieveOP5** [comment]
> How would you get the latest version without making a request against an API?

maybe a version file in project, and get it through github raw file url? it's my humble opinion.
i think you may have a better idea.

**Comment by Laptop765** [comment]
You can probably use `GitHub API Conditional requests` which don't count towards rate limiting.

https://docs.github.com/en/rest/overview/resources-in-the-rest-api#conditional-requests
