### ISSUE TITLE
Authentication proxy not working

### ISSUE THREAD

**Issue by RichyHBM** [sissbruecker/linkding#343]
Hello, I have followed the docs to setup an authentication proxy to not need to login, but it doesnt seem to do anything.

My env file looks like:
```
...
LD_SUPERUSER_NAME=admin

LD_ENABLE_AUTH_PROXY=True
LD_AUTH_PROXY_USERNAME_HEADER=HTTP_REMOTE_USER
LD_AUTH_PROXY_LOGOUT_URL=https://authelia.my.domain/
```

I am using Authelia + traefik and have confirmed the header is passed using https://code.mendhak.com/docker-http-https-echo/ with output:
```
{
  "headers": {
    ...
    "remote-email": "admin@home.local",
    "remote-groups": "admins,admin,dev",
    "remote-name": "admin",
    "remote-user": "admin",
    ...
  },
  ...
}
```

I have tried both using the `LD_SUPERUSER_NAME` and not using it but creating a user with the create user command, both cases just take me to the login page when I bring docker up and access linkding

**Comment by sissbruecker** [comment]
Did a quick test locally by setting up the env file, configuring:
```
LD_ENABLE_AUTH_PROXY=True
LD_AUTH_PROXY_USERNAME_HEADER=HTTP_REMOTE_USER
```
and then running `docker-compose up`. For setting the `Remote-User` header I'm using a browser extension. With that setup remote authentication works fine for me. Also found out that you don't have to configure a user, Django creates users automatically when using remote authentication.

So I would guess that this is something specific with your setup. The config you posted looks fine. How did you configure Traefik to pass the headers to linkding?

**Comment by RichyHBM** [comment]
For goodness sake, I had just forgotten to add the authelia middleware to linkding, silly mistake

**Comment by moookino** [comment]
@RichyHBM  can you share labels you're using for docker compose? I've same issue. Authelia is working as auth provider for other service, but with linkding leaves me on login page and w/o admin access even I've it defined in env
