### ISSUE TITLE
Server scraping can fail for large pages

### ISSUE THREAD

**Issue by karli2000** [sissbruecker/linkding#345]
When i try to archive this page linkding runs into a timeout and is unable to bookmark it, tried it with the chrome extension and on linkding itself, will timeout after 60 seconds:
https://instances.vantage.sh/

Running linkding 1.15.0 on a dedicated server in Docker using cloudflared tunnel to access it remotely, works fine for every other page.
Any idea what the issue could be?

PS: I love linkding!

**Comment by karli2000** [comment]
I guess i found the issue: the machine where it was running only had 512MB ram, upgraded it to 1GB and now i can archive this link.

**Comment by sissbruecker** [comment]
Yeah, the website delivers an HTML document that is 5 MB in size, which the server-side scraper doesn't handle very well. The scraper will first load the full HTML, and then parse it into an actual DOM structure, which requires more memory the larger the HTML document is.

The scraper could be improved, for example:
- only parse the contents of the `head` tag, as that is the only part of the document that is queried for metadata
- do not parse the document into a structure, instead use regex to extract metadata
- do not load the full document

Regarding memory usage, you should be absolutely fine with 512 MB, this is very much an edge-case. The linkding demo instance is running on fly.io with just 256MB, which is borderline, but usually working fine.
