### ISSUE TITLE
[feature request] Adding sort option for bookmarks 

### ISSUE THREAD

**Issue by IMR707** [sissbruecker/linkding#347]
As I currently see, the default sorting is the newly created ones will be listed on the top. 

I often update the older link to keep it up to date. I usually done this when I was reading manga on Mangaplus or watching anime in Bilibili. As more newer bookmarks are added, the older ones will pushed behind further and further. This makes navigating to it quite annoying, especially for often updated and visited links.

Having sort option will help a lot for this kind of use. I think for a starter, having an option to sort by create date (the current default), update date, and title should be enough.

**Comment by sissbruecker** [comment]
There's an existing issue for adding a sort option, added your comment there: #188
