### ISSUE TITLE
feature request: add traefik configuration example

### ISSUE THREAD

**Issue by FieldOfRice** [sissbruecker/linkding#351]
Trying to acces linkding behind traefik fails, my docker-compose.yml is as follows, but unable to gain access through /bm, maybe i need to add something to the .env file:
<pre>
version: '3'

services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    env_file:
      - .env
    expose:
      - "9999"
    restart: unless-stopped
    networks:
      - traefik_traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:/bm;ReplacePathRegex:^/bm/(.*) /$$1"
      - "traefik.docker.network=traefik_traefik-net"
      - "traefik.port=9999"

networks:
  traefik_traefik-net:
    external: true
</pre>

and this are the contents of .env:
<pre>
# Docker container name
LD_CONTAINER_NAME=bookmarks
# Port on the host system that the application should be published on
LD_HOST_PORT=9999
# Directory on the host system that should be mounted as data dir into the Docker container
LD_HOST_DATA_DIR=./.__DATA
# Can be used to run linkding under a context path, for example: linkding/
# Must end with a slash `/`
LD_CONTEXT_PATH=

# Username of the initial superuser to create, leave empty to not create one
LD_SUPERUSER_NAME=admin
# Password for the initial superuser, leave empty to disable credentials authentication and rely on proxy authentication instead
LD_SUPERUSER_PASSWORD=secret
# Option to disable background tasks
LD_DISABLE_BACKGROUND_TASKS=False
# Option to disable URL validation for bookmarks completely
LD_DISABLE_URL_VALIDATION=False
# Enables support for authentication proxies such as Authelia
LD_ENABLE_AUTH_PROXY=False
# Name of the request header that the auth proxy passes to the application to identify the user
# See docs/Options.md for more details
LD_AUTH_PROXY_USERNAME_HEADER=
# The URL that linkding should redirect to after a logout, when using an auth proxy
# See docs/Options.md for more details
LD_AUTH_PROXY_LOGOUT_URL=
</pre>

**Comment by sissbruecker** [comment]
I can't provide support for configuring proxy servers. If someone comes up with a good configuration, feel free to open a pull request to add it to the [community section](https://github.com/sissbruecker/linkding#community).
