### ISSUE TITLE
Can't deploy linkding to Docker Swarm cluster

### ISSUE THREAD

**Issue by bitcanon** [sissbruecker/linkding#355]
I'm trying to deploy **linkding** to my Docker Swarm cluster. In this setup I have the issue of making the database available on all cluster nodes.

There are a few options available:
1. Place the sqlite database on a network storage (such as NFS).
2. Force the application to run on a specific node (and run database on **local storage**, on the node itself).
3. Use another database.

I tried option 1 and 2. 

**Option 1** doesn't work for some reason, I only get HTML 500 errors on login. When reading up on the issue it seems that sqlite and NFS doesn't work well together due to file locking.

**Option 2** works but defeats the purpose of running a cluster, since the application fails, if the node running the application fails.

So my question is if it is possible to switch over to using mySQL or MariaDB instead via environment variables in the docker-compose file?

_I've had a quick look in the source code of the application and from what I can see this is not possible as of now?_

**Comment by sissbruecker** [comment]
Other databases are not supported at the moment. There is a linkding fork that works with Postgres: https://github.com/RoGryza/linkding-postgres

In a similar fashion with a bit of fiddling it should be possible to configure other databases by customizing the Django settings as is done in the fork.

**Comment by bitcanon** [comment]
Thanks for your reply. I think I might have a look into the Postgres fork and see how that works.
