### ISSUE TITLE
[Feature Request] Allow excluding tags from search

### ISSUE THREAD

**Issue by jacobgkau** [sissbruecker/linkding#357]
Currently, I can search for combinations of multiple tags. However, it would also be good to be able to exclude a tag from a search. For example, if I have two bookmarks:

- Bookmark 1: tag1, tag2
- Bookmark 2: tag1, tag3

I should be able to search e.g. "#tag1 -#tag2" and have only Bookmark 2 returned.

**Comment by sissbruecker** [comment]
Seems to be a duplicate of #296?

**Comment by jacobgkau** [comment]
Hmm. I saw that before I opened this, but the wording confused me. Reading it again, I think you're right.

**Comment by sissbruecker** [comment]
I'll update the linked issues' title to the one you proposed here, feel free to add any clarifying comments to that issue.
