### ISSUE TITLE
duplicated link check request

### ISSUE THREAD

**Issue by lilarcor** [sissbruecker/linkding#363]
enhancement request : check duplicated link

**Comment by sissbruecker** [comment]
The application checks for duplicate URLs, and updates the existing bookmark instead of creating a new one. Is there a problem with that feature?

**Comment by karlhorky** [comment]
> The application checks for duplicate URLs, and updates the existing bookmark instead of creating a new one. Is there a problem with that feature?

There is a problem with the behavior between import and regular bookmark editing - import doesn't normalize / deduplicate in same way as editing a bookmark does:

- https://github.com/sissbruecker/linkding/issues/1372
