### ISSUE TITLE
Description Field is Truncated

### ISSUE THREAD

**Issue by maxalentix** [sissbruecker/linkding#364]
On the main (/bookmarks) page, the description field for each bookmark entry is truncated so that it only occupies one line.
Many of my descriptions span multiple lines. Is there a way to display the entire description which may span many lines?
I am using the latest docker image.

**Comment by sissbruecker** [comment]
Seems like a duplicate of https://github.com/sissbruecker/linkding/issues/326, please add your concerns there.
