### ISSUE TITLE
[Feature Request] Add REST API of bookmarks export

### ISSUE THREAD

**Issue by cs-qyzhang** [sissbruecker/linkding#367]
It will be great to have a method to export/backup bookmarks in text file (json,html...), then i can use crontab to export my bookmarks and upload them to my cloud provider's OSS periodically in case of server failure. I saw this discussion in #37, but it seems hard to do it now.

**Comment by rem7** [comment]
yeah, this would be a great option to backup without the need of installing SQLite. Even if its just the regular html export.

**Comment by virtadpt** [comment]
Same.

**Comment by sissbruecker** [comment]
I think the easiest thing would be to be able to run the backup through the Docker container. It should be possible to run the SQLite export in the Docker container via `docker exec`, store the result in a folder that is mounted to the host system, and then grab the file from there. Not sure how to access the Sqlite binary in the container though.

**Comment by sissbruecker** [comment]
Using the REST API doesn't seem to make a lot of sense. The API only returns bookmarks for a single user, and then you'd also need a way to import whatever you saved from the API.

Closing this in favor of https://github.com/sissbruecker/linkding/issues/454
