### ISSUE TITLE
[Feature Request] Link shortening

### ISSUE THREAD

**Issue by SteveDinn** [sissbruecker/linkding#370]
It seems like an obvious thing to me to integrate bookmark management with link shortening, but I haven't found a particular FOSS project that does both. 

How difficult would it be to assign a unique short link code for each bookmark (either generated or user-specified), and redirect everything from say, `https://linkding.example.com/l/[LINK_CODE_HERE]` to the URL of the actual bookmark?

Apologies if this has been discussed before, but I couldn't find it when searching.

Thoughts?

**Comment by sebw** [comment]
I'm sorry, not trying to be snarky but how `https://linkding.example.com/l/[LINK_CODE_HERE]` can be considered short or shorter?

What's the actual use case? You'd like those links to be public and shareable to the world?

Maybe an integration with an external service (such as bit.ly) would be more appropriate?

**Comment by sissbruecker** [comment]
Good questions, now that I think about it I'm also not sure about the use case. Another issue is that bookmarks are inherently considered to be private, so just exposing all of them through a URL isn't an option.

**Comment by dahamsta** [comment]
> I'm sorry, not trying to be snarky but how `https://linkding.example.com/l/[LINK_CODE_HERE]` can be considered short or shorter?

Not OP. It's not short, but it could easily be shorter. And some people have short domains, I have 2 letter domains in 2 letter TLDs, for example.

I'm not sure of the use case myself, but [YOURLS](https://yourls.org/) is an excellent shortener with an API, that would be the route I would suggest if it were to go ahead.

**Comment by kzshantonu** [comment]
@SteveDinn my guess is you're looking for non-private bookmarks management with link shortening. Try [Shlink](https://shlink.io).

Any link you add is also a short link. Custom titles. Custom tags. Good search. Very handy
