### ISSUE TITLE
[Feature Request] Add unread option to the HTTP Shortcuts integration

### ISSUE THREAD

**Issue by jimmerricks** [sissbruecker/linkding#377]
It would be great to be able to mark a link as unread when saved using HTTP Shortcuts. I had a go a doing this, but could not work out which of the variables to use (a binary checkbox would have been the obvious choice but I don't think there is one).

**Comment by sissbruecker** [comment]
This was a community contribution, I have no experience with configuring / using it myself. Willing to accept PRs that add this.

**Comment by kzshantonu** [comment]
@jimmerricks I'm creating a v3 of the integration. This new version will filter out anything that is not a link, and only share the link directly to the API. Useful for apps that share other things with the link (like description or title). 

Then it will ask a multiple choice question:

Tagged, untagged and default tag.

If tagged is selected, the user can enter a comma separated list of tags.

Default tag will tag it with a single predefined tag.

What you want can easily be done with multiple choice questions. If you need help, let me know

**Comment by jimmerricks** [comment]
This sounds great. I look forward to your update and will follow up with you afterwards if I can't work things out.

**Comment by kzshantonu** [comment]
@jimmerricks so you'd like the unread option in addition to tagged/untagged/default-tagged? Am I understanding this correctly?

**Comment by kzshantonu** [comment]
Or perhaps like this?

1. tagged
2. untagged and unread
3. default-tagged

**Comment by jimmerricks** [comment]
It would be nice to include the unread option, but I think you should make this in the way that makes the most sense to you. Linkding gives a lot of options for saving links. The more of these that you incorporate into the HTTP Shortcuts integration, the less efficient it becomes to use.

**Comment by kzshantonu** [comment]
Aight I've simplified a lot. Test it for me before I submit a PR please: 

https://gist.githubusercontent.com/kzshantonu/f067bac4ba67e3918d857c3b20201b1b/raw/24dda9a051b8d06b2bad00ba6b8f831480fc6e94/linkding_v3.1.json

modify `linkding_instance` and `linkding_api_key` variables

**Comment by jimmerricks** [comment]
Works for me and looks to be a good compromise between features and ease of use. My only suggestion is to make the toast feedback a little more user friendly.
