### ISSUE TITLE
Unclosed <script> in bookmark description/title leads to faulty export and import

### ISSUE THREAD

**Issue by Fivefold** [sissbruecker/linkding#396]
When switching between two linkding instances where I exported all bookmarks and imported them in the second instance I noticed the following issue: 

1. When there is a `<script>` tag in the website bookmark description or title this gets exported without any escaping (not sure if the Netscape HTML format allows this) when exporting. 
2. When importing the same file, linkding will import all bookmarks from the top until that bookmark with the `<script>` tag in the description. Then it silently skips this and any following bookmarks.
3. The user won't be notified of this, i.e. it says `x bookmarks were successfully imported.` where `x` is the number of bookmarks until the offending one.
4. I didn't test `<script>` in linkding tags but think they should be fine since they are in quotes in the exported HTML. 
5. When the `<script>` tag gets closed within the title/description no bookmarks gets skipped but everything within title/description from the opening `<script>` on including the tag will get omitted.
6. I also tested an unclosed `<b>` and it's the same behaviour as directly above.
7. `<a>` in the description confuses the importer as such that it is used for the linkding link instead of `<DT><A HREF...>`

The website that made me aware of this is https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts
When creating a link using the linkding extension and auto-fetching the description it will create a bookmark like this upon export:

```html
<DT><A HREF="https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#connection-based_messaging" ADD_DATE="1639773243" PRIVATE="0" TOREAD="0" TAGS="">Firefox Extension Content scripts</A>

<DD>A content script is a part of your extension that runs in the context of a particular web page (as opposed to background scripts which are part of the extension, or scripts which are part of the web site itself, such as those loaded using the <script> element).
```

**Comment by sissbruecker** [comment]
Yeah, the implementation of the exporter is very naive at the moment, and does not handle escaping of titles and descriptions. That part should definitely be fixed. Not sure about making the importer handle nested tags in title and description, I haven't seen an actual use-case for that.

**Comment by Fivefold** [comment]
> Not sure about making the importer handle nested tags in title and description, I haven't seen an actual use-case for that.

I agree. Just escaping should be fine. Tags in title/descriptions should be a very rare occurence anyway.
In the mdn web docs example above the <script> tag is clearly intended to be interpreted as text, and not as an actual tag.
