### ISSUE TITLE
Login: CSRF error after login

### ISSUE THREAD

**Issue by joel72265** [sissbruecker/linkding#399]
Login is successful but then the error is shown below

Error: Forbidden (403). CSRF verification failed. Request aborted.

Followed steps https://todoist.com/help/articles/csrf-token-error-messages but still got the error message.
Tested on both Chrome 109.0.5414.75 and Firefox 106.0.1

linkding:latest on docker

**Comment by sissbruecker** [comment]
See:
- https://github.com/sissbruecker/linkding/issues/340
- https://github.com/sissbruecker/linkding#reverse-proxy-setup
- https://github.com/sissbruecker/linkding/blob/master/docs/troubleshooting.md#login-fails-with-403-csrf-verfication-failed

**Comment by joel72265** [comment]
you are correct, the first link resolved the issue. Thank you
