### ISSUE TITLE
Is there any mobile application?

### ISSUE THREAD

**Issue by mwolfaardt** [sissbruecker/linkding#40]
Is there any mobile application for Android?

**Comment by sissbruecker** [comment]
@mwolfaardt As far as I know there are no companion apps. For me the website works very well on mobile.

**Comment by nishantbb** [comment]
@sissbruecker Is it possible to use the bookmarklet with a mobile web broswer?

**Comment by sissbruecker** [comment]
@nishantbb AFAIK that is not possible. I think on mobile the best experience would be to hook into the sharing mechanism, so that sharing a URL from the browser provides the option to share to linkding. It looks like the is an [API](https://web.dev/web-share-target/) for that but it seems to be specific to the combination of Chrome **and** Android.

**Comment by sissbruecker** [comment]
Currently playing around with an iPhone and there is a pretty cool alternative using app shortcuts. Basically:

**In the shortcuts app:**
- create new shortcut
- go to shortcut details, enable to option to show the shortcut in share menu
- from the available share input types only select "URL"
- add Safari action "Display website in Safari" (paraphrasing, not sure how it's called in english)
- for URL enter your linkding instance URL and specifically point to the new bookmark form, then add  the shortcut input variable from the list of suggested variables after the URL parameter. Visually it should look something like this: `https://linkding.mydomain.com/bookmarks/new?url=[Shortcut input]`, where `[Shortcut input]` is a visual block that was inserted after selecting the shortcut input variable suggestion
- save, give the shortcut a nice name + glyph

**Then from Safari:**
- browse to the website that you want to share
- click the share button
- your new app shortcut should now be available as share action
- select the app shortcut
- this should open a new Safari overlay showing the add bookmark form with the URL field prefilled
- after saving the bookmark you can close the overlay and continue browsing

**Comment by WasabiPizza** [comment]
> Currently playing around with an iPhone and there is a pretty cool alternative using app shortcuts.

Could you share a screenshot of the shortcut? I’m trying to replicate it but I’m having some difficulties. Thanks!

**Comment by sissbruecker** [comment]
@WasabiPizza Sure, it's in German though:

![Add Bookmark](https://user-images.githubusercontent.com/357820/113057982-00483000-91ae-11eb-8a62-87132253eb1a.png)

Here's a screenshot of how to insert the variable / placeholder into the URL string:

![Add Bookmark 2](https://user-images.githubusercontent.com/357820/113058906-0e4a8080-91af-11eb-9c30-798cc0c5feff.png)

**Comment by WasabiPizza** [comment]
@sissbruecker Thank you very much! I got it working.
