### ISSUE TITLE
Demo is unavailable

### ISSUE THREAD

**Issue by severinkaelin** [sissbruecker/linkding#408]
Hello
First of all, thanks for this great project.

I've noticed that the demo instance mentioned in the README is currently not available: https://demo.linkding.link/

There seems to be no A DNS record:
![image](https://user-images.githubusercontent.com/39438642/214210381-68faad20-fd35-4b6a-ab0a-4e7ee268ad10.png)

Will the demo be made available again or did you intentionally shut it down?

**Comment by sissbruecker** [comment]
I had to recreate the demo setup, and have only configured an AAAA name record. The hoster I'm using does not provide a IPv4 address (anymore?), so it seems I'm not able to set an A name record.

The demo is reachable for me from several devices, and at least the AAAA name record is detected by a DNS lookup:
<img width="1303" alt="Bildschirmfoto 2023-01-24 um 09 08 41" src="https://user-images.githubusercontent.com/357820/214241130-2dc515a7-b30c-4bcb-9334-a0341c31c1d7.png">

Maybe you could check from a different device, or using a different DNS provider?

**Comment by severinkaelin** [comment]
> I had to recreate the demo setup, and have only configured an AAAA name record. The hoster I'm using does not provide a IPv4 address (anymore?), so it seems I'm not able to set an A name record.
> 
> The demo is reachable for me from several devices, and at least the AAAA name record is detected by a DNS lookup: <img alt="Bildschirmfoto 2023-01-24 um 09 08 41" width="1303" src="https://user-images.githubusercontent.com/357820/214241130-2dc515a7-b30c-4bcb-9334-a0341c31c1d7.png">
> 
> Maybe you could check from a different device, or using a different DNS provider?

@sissbruecker Thanks for your reply. I've been in a IPv4-only network, so it makes sense now.

Would you consider adding a IPv4 address again? IPv6 adoption has been increasing over the past years but is still just below 50% worldwide: https://www.google.com/intl/en/ipv6/statistics.html#tab=ipv6-adoption

In many countries, IPv6 use is only in the single-digit percentage range or not present at all: https://www.google.com/intl/en/ipv6/statistics.html#tab=per-country-ipv6-adoption

I am aware that the demo instance is a voluntary service on your part. However, if an IPv4 address can be added at a reasonable cost, this might be worth considering in terms of the accessibility of the demo to the community.

I look forward to hearing your take on this.

**Comment by sissbruecker** [comment]
Did take a closer look, and it seems the hoster I'm using (fly.io) does not provide a dedicated IPv4 address (for free) anymore. More context here: https://community.fly.io/t/announcement-shared-anycast-ipv4/9384

I understand your concerns, but at this point I have no incentive to invest anything in the demo. It's just intended as a convenient way to try out the app. If it doesn't work, then you'll have to spin up your own instance, which is just less convenient.

**Comment by severinkaelin** [comment]
> Did take a closer look, and it seems the hoster I'm using (fly.io) does not provide a dedicated IPv4 address (for free) anymore. More context here: https://community.fly.io/t/announcement-shared-anycast-ipv4/9384
> 
> I understand your concerns, but at this point I have no incentive to invest anything in the demo. It's just intended as a convenient way to try out the app. If it doesn't work, then you'll have to spin up your own instance, which is just less convenient.

@sissbruecker I understand. Let me know if you'd think a demo with IPv4 would be a value-add for the community / attracting new users and potential contributors. I'd be happy to support the project and sponsor the IPv4 costs for a year.

**Comment by sissbruecker** [comment]
Sure and thanks. I'll close the issue for now.

**Comment by claudio4** [comment]
@sissbruecker Apologies for reopening a closed issue, but I believe that providing a demonstration can greatly aid adoption (convenience is a powerful thing). Moreover, I have a solution that is cost-free, sustainable in the long run, and straightforward to implement. Place Cloudflare in front of the demo. By enabling the Cloudflare proxy for a record, it will handle both IPv4 and IPv6, even if your original setup only supports IPv6.

**Comment by satoshinotdead** [comment]
What about changing the actual state of the issue?

The projects seems to be very good! And we like to try :)

**Comment by tarocjsu** [comment]
╭╴IP:192.168.1.103 at  ~ on  mast… ( )
╰─ nslookup demo.linkding.link
伺服器:  UnKnown
Address:  192.168.1.127

名稱:    demo.linkding.link
Address:  2a09:8280:1::a:cd73

DNS look like know the domain match IPv6 address, but the Chrome browser program still cannot connect to the IPv6 address ?

**Comment by tarocjsu** [comment]
No update ?

**Comment by tarocjsu** [comment]
Or this project already dead ?

**Comment by rgilm123** [comment]
> Or this project already dead ?

Just use an ipv6 proxy to see the demo site like this one:

http://www.ipv6proxy.net/go.php?u=http%3A%2F%2Fdemo.linkding.link%2Flogin%2F%3Fnext%3D%2Fbookmarks&b=1
