### ISSUE TITLE
Search doesn't match against tags unless use #

### ISSUE THREAD

**Issue by adamshand** [sissbruecker/linkding#409]
Hello,

Currently, linkding searches don't include tags unless you explicitly include the #. 

For example, I just added a link with a tag `interviewing`, but if I search for `interviewing` it doesn't show up (it does show up if I search for `#interviewing`).

It would be very helpful for me if tags were searched along with all the other fields.

Even better than that would be if:

- searching for `interviewing` returns links which have interviewing in any field (including tags)
- searching for `#interview` only returns links which have the tag `interviewing`

This seems more explicit and obvious to me, by default searches return all matching results.  If you only want to restrict searches to only tags, use the # prefix.

Thanks again for linkding, I use it every day!

See also: https://github.com/Fivefold/linkding-injector/issues/8

Cheers,
Adam.

**Comment by nickludlam** [comment]
I'd also love this as either a straight default, or an option I can turn on. I just had an issue where a keyword I searched for was in the tag, but not the title or description, so I thought I had lost the URL

**Comment by mckennajones** [comment]
Opened a small PR to add support for this. Ended up being a one-liner.

**Comment by mckennajones** [comment]
@sissbruecker has a better approach on his [feat/search_tags_without_hash](https://github.com/sissbruecker/linkding/compare/feat/search_tags_without_hash) branch, so closed my PR in favor of that.
