### ISSUE TITLE
Timeout server side problem

### ISSUE THREAD

**Issue by Haze-sh** [sissbruecker/linkding#410]
When I try to send bookmarks to linkding using a script it does give a timeout error after sometime. I believe the issue is because linkding closes connection when it faces big number of requests. How can I evaluate this more? or how could it be changed?

Relevant: bachya/aiolinkding#34

**Comment by negatendo** [comment]
I don't know for sure if this is being caused by linkdig, but it's never a bad idea to throttle your own scripts by putting a wait timer between the calls, or better yet having it wait for a few minutes and retry after catching the timeout error.

**Comment by sissbruecker** [comment]
When creating a bookmark, linkding tries to scrape the metadata for that website which can take up to several seconds. If you send 1000 bookmarks at once you'll likely end up with timeout errors. As such, bulk creation needs to take that into account and either create the bookmarks in sequence, or at least throttle it.
