### ISSUE TITLE
Importing .url files (IE Favourites)

### ISSUE THREAD

**Issue by nodecentral** [sissbruecker/linkding#424]
Hi, sorry if I missed this,

I have folders full of old Internet explorer favourites (stored as .url files)
Is there a way for me to import them all into Linkding ?

**Comment by sissbruecker** [comment]
There is no feature in linkding to do so, and it doesn't look like something that I want to add. I would recommend to search for tools that can convert such a file into the Netscape HTML format. If for example Chrome or Firefox support importing .url files that should be trivial, as both of them support export in the Netscape format.

**Comment by nodecentral** [comment]
Thanks @sissbruecker, I completely understand..

If it's of interest, I came across a few posts on this, one of which was https://gist.github.com/GeoffreyPlitt/43e251364182f12c8d7f.

Who knows, it might be something to consider as new a bit of new functionality on your product's roadmap, if only to help and tempt those of us who still have folders full of bookmarks that use these .url files..
