### ISSUE TITLE
Search seems to be case-sensitive

### ISSUE THREAD

**Issue by kzshantonu** [sissbruecker/linkding#425]
In my opinion it's unnecessary and can lead one to believe they didn't bookmark something months later even if they did

**Comment by sissbruecker** [comment]
You didn't specify which characters you are using, so I'm assuming this concerns non-ASCII characters. Case-insensitive search currently only works with ASCII characters due to a limitation in SQLite: https://github.com/sissbruecker/linkding/issues/181

**Comment by Koellewe** [comment]
I'm experiencing case-sensitive search, even with ASCII characters. See screenshots below:

![Screenshot_20230220_192358](https://user-images.githubusercontent.com/14095706/220169164-74e5528d-7014-4b12-8f4c-73e6fc4f73cd.png)

![Screenshot_20230220_192419](https://user-images.githubusercontent.com/14095706/220169225-82f2e0be-f06c-49cb-b1b1-11e746f006b6.png)

Running docker image `sissbruecker/linkding:latest` (pulled this morning: `sha256:a4f26359eea93ba932e2560880aab5faec2027dfc63646e1f1c8f841d6ef57fe`)

**Comment by sissbruecker** [comment]
Did double-check this, and can not reproduce this with either SQLite or Postgres. I'd be willing to take a look at a backup of a SQLite DB if you can provide one for reproduction.

**Comment by sissbruecker** [comment]
Nevermind, can reproduce it with Postgres. It seems the search currently uses a case-sensitive condition, which is automatically converted to a case-insensitive one in SQLite.

**Comment by sissbruecker** [comment]
https://github.com/sissbruecker/linkding/pull/432

**Comment by Koellewe** [comment]
Thanks @sissbruecker!

**Comment by kzshantonu** [comment]
Oh yes sorry I forgot to mention I was on postgres
