### ISSUE TITLE
Linkding iOS Shortcut to log bookmarks

### ISSUE THREAD

**Issue by nodecentral** [sissbruecker/linkding#430]
Hi

I’ve been trying to follow the guide to create a shortcut in iOS (https://github.com/sissbruecker/linkding/blob/master/docs/how-to.md) but it’s not working for me, it also looks like the shortcut options have changed so the guide is not reflecting what’s there today.

By any chance could someone post (link to) a working iOS Shortcut as I’m keen to see how well that works - many thanks

**Comment by nodecentral** [comment]
Also, just a thought - with the url used, is it possible with the shortcut to have the option to be prompted for other attributes e.g.
`http://192.168.102.134:9091/bookmarks/new?url=http://google.com&tags=Search&title=Testing`

And maybe submit (post) it too without the need for the web page to come up ?

**Comment by exen904** [comment]
I just built this, it works for me, but still opens Linkding to ask for saving/etc. Which I actually don't even mind, as I can then attach tags etc. 

![image](https://github.com/sissbruecker/linkding/assets/59537420/c535fcd6-08f5-41a5-8948-2ddbd27c053c)

**Comment by andrewdolphin** [comment]
Regarding automatic posting I've created the attached shortcut. It uses the API so you need to enter both your own URL and API token (from the settings tab in Linkding) in two places.

It also pulls current Tags from the server and allows you to tag the url when you share. It doesn't currently allow you to add a new tag.

It works for me but is shared without any guarantees!

https://www.icloud.com/shortcuts/97a516940fb64d039446eba1ed616b9d

**Comment by sissbruecker** [comment]
@andrewdolphin Could you please:
- Create a Github Gist (or similar) explaining how to set up the shortcut, as in how to install it and set up the necessary variables
- PR the Gist into the [Community](https://github.com/sissbruecker/linkding#community) section

**Comment by sissbruecker** [comment]
Updated the [how-to](https://github.com/sissbruecker/linkding/blob/master/docs/how-to.md#create-a-share-action-on-ios-for-adding-bookmarks-to-linkding) with a pre-made shortcut that uses the add bookmark form. Alternatively, the shortcut by @andrewdolphin, which uses the linkding API, is now listed in the community section.
