### ISSUE TITLE
[Feature Request]: Save Bookmarks, View options

### ISSUE THREAD

**Issue by joel72265** [sissbruecker/linkding#433]
Thank you for a wonderful project.

Some feature request suggestions; 

- Drag and Drop a link to the Linkding page to create a bookmark
- Option in Settings: General, to save bookmarks with/without description automatically
- View: hide tags, description ..... on the Main page

**Comment by sissbruecker** [comment]
Please create one issue per feature request, and try to provide more details - some of your points are too vague to make sense of.

**Comment by joel72265** [comment]
ok, yes I can do that. I am still getting use to github
