### ISSUE TITLE
Please allow spaces in tag names

### ISSUE THREAD

**Issue by xteaun** [sissbruecker/linkding#444]
Please allow spaces to be used in tag names. To separate different tags in the input form commas should be used instead of spaces.

**Comment by kzshantonu** [comment]
While this sounds like a good idea, it actually is not. Me (and many others) for example already have it set in my muscle memory that tags are just like pinboard tags (which I'm sure linkding is heavily inspired from) hence cannot allow spaced tags. Just use underscore as spaces. It also would break many community-developed apps
