### ISSUE TITLE
enable https OR force https connection to http 

### ISSUE THREAD

**Issue by toxinliquid** [sissbruecker/linkding#445]
how can we enable https ? i need to redirect https to http.

**Comment by LancealotSeven** [comment]
''ŸØÛ/COUŁD/JUZZ'//,',',AKE//Å//WHOŁE//DOUŁE//DÅŽŽH''//ÅZ'//ÏN//HTTPS//--//HTTP//--//DØ//ÏHH//DHÅX//WWÅŸ//

**Comment by negatendo** [comment]
I serve linkding through an nginx reverse proxy which uses https. 

- [Nginx Configure HTTPS](https://nginx.org/en/docs/http/configuring_https_servers.html)
- [Nginx Reverse Proxy](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/)

**Comment by sissbruecker** [comment]
As mentioned above, best practice is to configure a reverse proxy in front of linkding, where you enable HTTPS and configure a redirect from HTTP to HTTPS
