### ISSUE TITLE
Make tags case-insensitive

### ISSUE THREAD

**Issue by Export33** [sissbruecker/linkding#45]
hi,
first of all, i really like your service and get used to it.

**behaviour**
tags are case-sensitive. but due to the highlight/capitalization the first letter is uppercase while the tag itself maybe not. having the same tag lower-case and capitalized shows the tag also twice.

![image](https://user-images.githubusercontent.com/25232960/103247833-8a42eb80-4968-11eb-9236-9bdfc756d85b.png)

**expected behaviour**
tags should be case-insensitive. this would

* show the same tag only once
* make tagging easier especially when on mobile

**Comment by sissbruecker** [comment]
Yep, that makes a lot of sense. The solution will probably just ensure that assigning and searching for tags always uses lower-case, but will not clean up existing duplicates.

BTW you can manage tags in the admin view (`/admin`), so there's an option to remove duplicate tags at least.

**Comment by Export33** [comment]
Sounds good. Duplicates are no problem.

Thanks for the tip with the admin view, havent seen this before.

**Comment by sissbruecker** [comment]
Started working on this. While I wanted to store all tags as lowercase first, it occurred to me that maybe people want to preserve casing for their tag names - depending on your language it might be normal for certain words to start with an uppercase letter for example.

So instead I went with an approach where creating a new tag will preserve the casing as is, while search and assigning existing tags will ignore casing and use whatever is already in the database:
- creating a tag `Book` will store it as `Book` in the database (preserve casing)
- a search for `#book` or `#BOOK` will look for `Book`
- assuming `Book` already exists in the database, assigning the tag `book` or `BOOK` will actually assign `Book`

Makes sense?

**Comment by Export33** [comment]
Hey,

it makes sense and i like it.
You may want to link the `/admin` panel in the settings later so users get aware of the editing function for existing tags.

As a side note - which tag do you use for existing duplicates (`book`, `Book`) - the first?

**Comment by sissbruecker** [comment]
> As a side note - which tag do you use for existing duplicates (book, Book) - the first?

I'm not sure, and I'm also not sure if the behaviour would be deterministic - it depends on the database logic. I would guess that yes, it takes the tag that was created first.
