### ISSUE TITLE
Documentation incomplete?

### ISSUE THREAD

**Issue by SekoiaTree** [sissbruecker/linkding#451]
The documentation for the admin page seems quite incomplete:
![image](https://user-images.githubusercontent.com/51149447/232023795-f7a3f5e0-2672-477d-8bd3-aa8f934ea9c8.png)

Of these, only "Bookmarks", "Users", and "Tags" are documented.

What are tasks? What do they do? Toasts? What's the difference between a feed token and a token?

**Comment by sissbruecker** [comment]
The admin docs were a contribution by a community member. I don't intend to maintain those personally, but PRs for improvements are welcome. 

Tasks are background tasks that are either scheduled (`Tasks`) or have been completed (`Completed tasks`). There currently are tasks for creating snapshots of bookmarks on the Internet Archive Wayback Machine, and for loading favicons.

`Tokens` are authentication tokens for accessing the API. `Feed tokens` are authentication tokens for accessing RSS feeds. Both are generated on demand when a user opens the `Integrations` settings page.

**Comment by SekoiaTree** [comment]
Alright, thanks!
