### ISSUE TITLE
Make backups easier

### ISSUE THREAD

**Issue by sissbruecker** [sissbruecker/linkding#454]
Everyone should do backups of their linkding database, however the current options are not straightforward:
- You can export manually through the UI - does not work automatically
- You can use an SQLite installation from the host system to export a backup - requires you to download SQLite first
- You can export everything through the REST API - requires advanced scripting, can only access bookmarks of single user, also need to restore backup somehow

This could be easier. One option I can think of is to utilize the SQLite binary that already exists in the Docker container to create the backup, and store the backup file in a mounted Docker volume. With that, users could just run a single command line prompt against the container to create the backup and store it on the host system. Then transfer the file to long-term storage. A more advanced version could be to create backups automatically on a schedule, so that you would only have to take care of the transfer part yourself.

**Comment by virtadpt** [comment]
You can just copy a SQLite database somewhere, though.  It's a single file.

**Comment by sissbruecker** [comment]
That gives you a good chance to backup a corrupted database in case the file is modified by the application while you are copying it. The database should be [locked](https://www.sqlite.org/backup.html) before copying the file, using the SQLite binary seems to be easiest way to do so.

**Comment by bjzhush** [comment]
you can also use dropbox script to backup sqlite files automatically

**Comment by lewis262626** [comment]
A backup to some form of object storage (whether S3, BlackBlaze B2, Minio) etc would be welcome

**Comment by MaxRies** [comment]
@lewis262626 This is nicely implemented in the fly.io integration with lite-stream. Works like a charm.
https://github.com/fspoettel/linkding-on-fly
I'm sure you could use this for backing up your database. It would be handy to integrate this in the webapp, instead of configuring it via docker environment variables.

**Comment by pettijohn** [comment]
Litestream for sqlite is a great option, I use it for this and a few other things I self-host. I'd also love a command line to export to HTML, maybe accept user as an argument or dump all with one file per user. Nothing beats plain text files for backups!

**Comment by l0b0** [comment]
For reference, Pinboard provides https://pinboard.in/export/format:html/, https://pinboard.in/export/format:json/, and https://pinboard.in/export/format:xml/ links for logged-in users, so it's really easy to back up the content in a version-control-friendly fashion.

(I'm not a linkding user, but would probably be if this were implemented. This was the first feature I checked for after hearing about this project.)
