### ISSUE TITLE
add an archive function

### ISSUE THREAD

**Issue by Export33** [sissbruecker/linkding#46]
hi,
it would be cool if links could be archived an therefore not being shown in the main list.

**use case**
i like adding links which are 

* noteworthy
* on my todo list

after finishing my task the links on my todo list should disappear from the main list while not being deleted. i still want to find them if i have to check on them later on.

**behaviour**
links can only be removed from the list. once removed, they are deleted and can never be found again

**feature request**
Add an button to archive a link. Archived links are shown in a seperate list. the tag list should remain the same but filter only on the archived links.

_Bookmark view_

* you can switch to the `Archive` view
* links can be `Archive`d
* search an tags work only for the main list

![image](https://user-images.githubusercontent.com/25232960/103248863-dbed7500-496c-11eb-86cc-67dad96e9cdf.png)

_Archive view_

* you can switch back to the main `Bookmarks` view
* links can be `Restore`d to the main bookmark list
* search an tags work only for the archived list

![image](https://user-images.githubusercontent.com/25232960/103249059-b4e37300-496d-11eb-9c85-3ca50e414dce.png)

**Comment by sissbruecker** [comment]
Thanks for the detailled description. I agree that this would be a desirable feature. I would probably change the link styles - the highlighted button should still be _Add bookmark_ as this is the primary action IMO. But those are details.

Also this needs to be accounted for in the REST API.

**Comment by Export33** [comment]
Sounds good.

Yes, the API should should be supported. Nice to have one btw.

**Comment by Export33** [comment]
Thanks for the implementation. Especially for completing this request this quick. This will help in my daily work.

You may want to add a `Bookmarks` Button to switch back to the "Bookmarks" view. While this is possible by clicking on the linkding logo it may be more intuitive for new users.

![grafik](https://user-images.githubusercontent.com/25232960/107986803-179bd700-6fcd-11eb-91d7-a41a6ce10f48.png)
