### ISSUE TITLE
Layout suggestions, Visibility options

### ISSUE THREAD

**Issue by joel72265** [sissbruecker/linkding#460]
please see some usability suggestions

1) bulk edit button to the left since Search button is used more
2) a clear button would be nice too
3) if we are able to hide tags, there will be more bookmarks per page. Hide Descriptions will make the page look cleaner
![linkding03](https://user-images.githubusercontent.com/118885352/234858878-5a2e53f7-67a2-4adc-8b11-2909cd9663e9.jpg)

**Comment by sissbruecker** [comment]
I don't want to move the bulk edit button.

Hiding the tag list is covered here: https://github.com/sissbruecker/linkding/issues/205
Clearing search is covered here: https://github.com/sissbruecker/linkding/issues/194
