### ISSUE TITLE
Enhancement: Run container as non-root

### ISSUE THREAD

**Issue by zigzampow** [sissbruecker/linkding#469]
It'd be great if we could get this setup so we can grab the image from docker and have it run as non-root.

FWIW I know I'm a newer docker-user, so this may be easy on my end, it'd just be great if it was default to not run as root.

**Comment by sissbruecker** [comment]
If you want to run Docker rootless, you'll have to configure Docker to do so: https://docs.docker.com/engine/security/rootless/

The Docker image should already support running as non-root: https://github.com/sissbruecker/linkding/pull/138
