### ISSUE TITLE
Unavailable to access in bridge network.

### ISSUE THREAD

**Issue by mailliwal** [sissbruecker/linkding#487]
Hi,

Below is the docker compose content to deploy linkding. I have modified default port to 8082.

linkding available to access via port 8082 under macvlan network, but failure in bridge network (Even default port 9090).

May I know any part I was missed ?

Thanks

=====================

version: '3.9'

services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    volumes:
      - /volume1/docker/linkding:/etc/linkding/data
    environment:
       TZ: "Asia/Taipei"
       LD_SUPERUSER_NAME: admin
       LD_SUPERUSER_PASSWORD: P@ssw0rd
       LD_SERVER_PORT: 8082
       LD_DISABLE_URL_VALIDATION: true
       LD_DISABLE_BACKGROUND_TASKS: true
    restart: on-failure:5
    network_mode: bridge

**Comment by sissbruecker** [comment]
Sorry, I don't provide any support for setting up specific configurations.
