### ISSUE TITLE
Memory usage increasingly slowly over time (memory leak?)

### ISSUE THREAD

**Issue by gingerbeardman** [sissbruecker/linkding#488]
I just noticed after a reboot memory usage was half (164MB) what it was before the reboot (306MB) which was greater than the amount I last rememver (~220MB)

So I am wondering if it's normal for it to grow over time, or if there's a memory leak somewhere?

figures as reported by Docker

![Screen shot 2023-06-16 at 10 36 45 2](https://github.com/sissbruecker/linkding/assets/49612/eaede628-8c84-4717-9057-a979e8aff233)

**Comment by MaxRies** [comment]
I noticed this, too. I have a linkding running on fly.io, and the container frequently crashes because it consumes too much memory. I cannot trace the memory increase to any actions that I take, it crashes randomly even during the night when I'm most certainly not using it.

**Comment by gingerbeardman** [comment]
My server was rebooted yesterday so I can't give a growth since the screenshot above.

But if you're running linkding in docker you can ssh in to your server and run `docker stats` and sit for a few minutes and watch memory use rise a percent. I watched mine go from 3 to 4%

Could the leak be in the docker container setup?

```
98836a445da1   linkding       0.02%     121.9MiB / 2.944GiB   4.04%     3.83MB / 189MB    0B / 0B     0
```

**Comment by gingerbeardman** [comment]
3 hours later it's up 70MB to 192MB, so early estimates for the leak are ~20MB/hour.

**Comment by gingerbeardman** [comment]
Closing this, is seems to vary for me. If it's still an issue for anybody else feel free to open a specific issue.
