### ISSUE TITLE
fail2ban support

### ISSUE THREAD

**Issue by b1ggi** [sissbruecker/linkding#489]
Would be nice to have fail2ban support in swag for linkding, some log that can be used for unsuccesful attempts

maybe this can be partly used: 

https://github.com/HerraLampila/django2ban

**Comment by yieldhog** [comment]
Second this, would love to see log/fail2ban support

**Comment by matthiasbaldi** [comment]
is/should this part of a "normal" software, or should you solve that via a ingress/reverse proxy.
i.e. https://traefik.io/traefik/ then https://plugins.traefik.io/plugins/628c9ebcffc0cd18356a979f/fail2-ban

**Comment by yieldhog** [comment]
I personally use a reverse proxy, nginx proxy manager (NPM), however, I've found that there have been repeated login attempts on other self-hosted platforms I use.

Traefik is overkill for (most) people's purposes in my opinion. Being able to simply spin up a docker container with fail2ban to block repeated attempts works well. Paperless-ngx is an example out of the box they support it simply by providing a log file with attempts and instructions to filter (https://github.com/paperless-ngx/paperless-ngx/wiki/Using-Security-Tools-with-Paperless-ngx#fail2ban)

Similar with Vaultwarden (https://github.com/dani-garcia/vaultwarden/wiki/Fail2Ban-Setup)

It's a security enhancement/nice to have

**Comment by Fischmuetze** [comment]
Imho fail2ban should be part of the reverse proxy configuration. Reason is that the reverse proxy have to filter IPs of login attacks - not the host behind. Linkding should provide a qualified log file that mark unauthorised logins / login fails ... this log can provide by the OS via rsyslog to each target and can parse there.  This is e.g. the way to handle login fails via fail2ban for nextcloud.

**Comment by sonor3000** [comment]
On Tue, Jan 30, 2024 at 02:06:55AM -0800, Fischmuetze wrote:
>   Linkding should provide a qualified log file that mark
>   unauthorised logins / login fails ... this log can provide by the OS via
>   rsyslog to each target and can parse there. This is e.g. the way to handle
>   login fails via fail2ban for nextcloud.

IMHO no container should log to a logfile but to STDOUT and STDERR instead, 
this is bad practice.

**Comment by marc0janssen** [comment]
This is how I "fixed" the fail2ban, it is not fool proof (in other words, you keep logging in and out you will also get banned, but hey who does that?""

I use fail2ban in [SWAG](https://docs.linuxserver.io/general/swag/).

### linkding.conf in filter.d
`# A fail2ban filter for unauthorized log messages

[Definition]

failregex = ^<HOST>.*"(GET|POST|HEAD) \/login\/.*".(200).*"https:\/\/.*\/login.*$
`

### Add this to jail.local
`[linkding]
enabled  = true
port     = http,https
filter   = linkding
logpath  = /config/log/nginx/access.log`
