### ISSUE TITLE
Add a dark mode

### ISSUE THREAD

**Issue by dev-kittens** [sissbruecker/linkding#49]
It would be nice if this included a dark mode.

I will likely PR this at some point (since it's the one thing between now and me using linkding), though I'm not familiar with Django so we'll see~
Otherwise I could skip making it a config setting and just do it in CSS (using `prefers-color-scheme`)... what would be preferred here?

**Comment by sissbruecker** [comment]
> Otherwise I could skip making it a config setting and just do it in CSS (using prefers-color-scheme)... what would be preferred here?

Not sure about this. Recently I used a website that detected that I use dark mode in macOS and switched automatically, but then had awful styles that were hard to read. IMO a setting is more appropriate to prevent such surprises.

In general I'm OK with the idea. I'm up for making this a setting, if you /someone else can provide a quality stylesheet for a dark mode. Note that the solution would need to integrate into the SCSS system that the application uses - I don't have much experience with theming solutions, so I'm not sure how I would approach this. Probably adding a `.dark-mode { ... }` rule to each `*.scss` file that overrides the necessary bits?

**Comment by sissbruecker** [comment]
Added a dark theme and a setting to switch the theme between light/dark/auto. Default is auto which uses prefers-color-scheme to determine the theme.

**Comment by Export33** [comment]
The dark themes looks great. Thank you!

**Comment by joel72265** [comment]
Thank you for the dark theme. 

If someone can share the hex# code of the colors used in the dark theme, I could possibly suggest colors for a possible alternate theme.
