### ISSUE TITLE
Feature request: Public view / ability to view links when not signed in

### ISSUE THREAD

**Issue by blipdrifter** [sissbruecker/linkding#491]
Similar to #123, except instead of removing login entirely, there can still be accounts, as well as an option to let non-registered users view added links in linkding without having to log in. You could also set it up to exclude non-shared or archived links from the public view as well. Would be great for self-hosted public link repositories.

**Comment by ecogit** [comment]
Indeed very practical to share a URL of a tag or search query. 

Like this it also has an advertising effect, as experienced with Pinboard when several friends or business partners signed up as well after they got to know it through such a URL.
