### ISSUE TITLE
Feature request: change behavior of clicking navbar logo

### ISSUE THREAD

**Issue by glottisfaun0000** [sissbruecker/linkding#496]
Linkding is fantastic!

I find myself going deeper into tags and then clicking the logo to go back to /bookmarks, but wishing I could go to /bookmarks?q=!unread without an additional step. I imagine it would be relatively trivial to add a setting to change the href there, or even a field to enter a default search string.

**Comment by Teknicallity** [comment]
@glottisfaun0000 It's possible I'm not fully understanding your request, but it seems like what you want is already a feature. Under the filter dropdown, there is a "Save as default" button. This will not change the URL, but it will change what displays when you go to the home page by clicking the navbar logo.
![image](https://github.com/sissbruecker/linkding/assets/100461662/3b56c209-f0bc-464a-9bfc-0a8ce1700761)
