### ISSUE TITLE
API CREATE doesn't create new bookmark but returns list of bookmarks 

### ISSUE THREAD

**Issue by georg-mayer** [sissbruecker/linkding#498]
Hello, 

i have an instance of linkeding (v 1.19.1) running via docker which works perfectly so far and also the firefox extension works nice. 

I now wanted to add some bookmarks with python and tried the below code. 

Unfortunately what I get back is a "200" response and in the body i get all my bookmarks listed.

I also tried with different URLs, e.g. "https://example.com/api/v1/bookmarks" (also /v2/) - but those give a 404. 

The token and the base url work, as i can for example get a list of my bookmarks by sending a get request. 

I assume I am making a mistake somewhere, but I cannot find it and tried now for too long - so if somebody could help me, I would be really happy. 

Here is the code:

```
import requests

LINKDING_URL = "https://example.com/api/bookmarks"
LINKDING_API_TOKEN = "my_token"

# Main script
if __name__ == "__main__":
    title="test"
    url="https://testing.com/test"
    data = {
        "url": url,
        "title": title
    }
    headers = {"Authorization": f"Token {LINKDING_API_TOKEN}"}
    response = requests.post(LINKDING_URL, json=data, headers=headers)
    print(response.status_code)
    print(response.content)
```

Thanks for your help!

Cheers,
Georg

Edit:

I also used this data-structure (as shown in the api documentation) but got the same result:
```
    data = {
        "url": url,
        "title": title,
        "description": "Example description",
        "notes": "Example notes",
        "is_archived": False,
        "unread": False,
        "shared": False,
        "tag_names": [
            "tag1",
            "tag2"
        ]
    }
```

**Comment by sissbruecker** [comment]
Looks like you're missing the trailing slash in the URL:
```
POST /api/bookmarks/
```
