### ISSUE TITLE
Homepage management

### ISSUE THREAD

**Issue by rounakdatta** [sissbruecker/linkding#500]
Hello, love Linkding! I'm just starting to migrate my Pinboard stuff onto here :)

Apart from singular bookmarks, I was wondering, does Linkding also allow collecting homepages of blogs / writers I love?
Lets take an example - say http://paulgraham.com. I'd like to store this as a favourite blog of mine, but don't want any RSS-like capability to notify when a new post arrives. Is this possible currently in Linkding?

**Comment by sissbruecker** [comment]
I'm not sure what you mean. Do you mean that the app should check for new blog articles and automatically add them as bookmarks? Or group articles of the same blog together somehow?

**Comment by rounakdatta** [comment]
My comment didn't clarify that properly, but I meant the latter - grouping articles of the same blog together. Looking at the groups with higher n(item) would indicate them as one's favourite blogs.

**Comment by sissbruecker** [comment]
There is an existing issue to group bookmarks by domain, which is pretty much what you want: https://github.com/sissbruecker/linkding/issues/415

There is also another issue to add more capabilities for manual grouping of bookmarks: https://github.com/sissbruecker/linkding/issues/285

I think I'll close this one in favor of these.
