### ISSUE TITLE
Feature request: Use a git repository as storage backend

### ISSUE THREAD

**Issue by prakhar47b** [sissbruecker/linkding#501]
Since the data is not very sensitive for most people and can be easily dumped in a file, a git repository can be used as a storage backend. A scheduled process can automatically perform a Bidirectional sync with the repository. This will also serve as automatic backup and version control.

**Comment by sissbruecker** [comment]
That doesn't sound very useful compared to just using SQLite and doing backups from that (which you can dump into Git if you want). I also don't understand the purpose of the bidirectional sync part. Anyway, not really interested in this. But sounds like you could do something like this as a 3rd party app via the API, or as I mentioned via SQLite backups.
