### ISSUE TITLE
Mismatch of PORT variable between Dockerfile and env.sample

### ISSUE THREAD

**Issue by fortysix2ahead** [sissbruecker/linkding#502]
That's an easy one ...

The env.sample at [https://github.com/sissbruecker/linkding/blob/master/.env.sample](https://github.com/sissbruecker/linkding/blob/master/.env.sample) says the variable for specifying the port is **LD_HOST_PORT**. However, using this variable does not work because the Dockerfile at [https://github.com/sissbruecker/linkding/blob/master/Dockerfile](https://github.com/sissbruecker/linkding/blob/master/Dockerfile) looks for **LD_SERVER_PORT** ...

**Comment by sissbruecker** [comment]
Those are not equivalent:
- `LD_SERVER_PORT` is the port that the app server within the container is running on
- `LD_HOST_PORT` is the port on the host system that the app is published on

**Comment by fortysix2ahead** [comment]
Oh, didn't see that. I was just looking at env.sample to find out what to put into docker-compose.yaml to change the port. Shouldn't there be a reference to LD_SERVER_PORT in env.sample?

**Comment by sissbruecker** [comment]
Maybe. Then again it has potential for confusion and it's an option that is probably rarely used, from what I remember you only need this with certain container solutions that have a shared port range.

**Comment by fortysix2ahead** [comment]
True. I am using it on a dev/test system where the configuration for a reverse proxy running on Docker is generated and everything that's attached to it is running on port 8080 ...
I'll close this issue!
