### ISSUE TITLE
Change location of checkbox next to bookmarks to save space

### ISSUE THREAD

**Issue by gabrielwhite** [sissbruecker/linkding#508]
With the latest update the checkbox next to bookmarks appears above the bookmark record.

It would be more space efficient if the checkbox was displayed to the left of the favicon.

<img width="690" alt="Screenshot 2023-08-22 at 12 30 04 pm" src="https://github.com/sissbruecker/linkding/assets/955848/41523dce-d856-4a1e-9db8-c2530f074bb8">

**Comment by sissbruecker** [comment]
Clearing your browser cache should fix that.

**Comment by gabrielwhite** [comment]
Thanks!
