### ISSUE TITLE
[Bug] v1.20.0: Bulk edit checkboxes appear when not editing

### ISSUE THREAD

**Issue by joshdick** [sissbruecker/linkding#509]
Just upgraded my Linkding installation from v1.19.1 to v1.20.0.

Linkding is seemingly incorrectly rendering what appear to be unlabeled bulk-edit checkboxes above each bookmark on the main/root bookmarks listing page, when not actually in bulk editing mode.

**Comment by sissbruecker** [comment]
See https://github.com/sissbruecker/linkding/issues/508

**Comment by joshdick** [comment]
I had tried refreshing a few times but had not tried clearing my browser cache, my apologies for the noise!

**Comment by sissbruecker** [comment]
Well, ideally you shouldn't have to. Should be fixed with #510
