### ISSUE TITLE
The configuration of 'Show notes permanently' does not take effect on non logged in sharing pages

### ISSUE THREAD

**Issue by bfansheng** [sissbruecker/linkding#521]
I don't know if this is a problem, or if there should be a separate config to control whether the notes on the sharing page are displayed when not logged in.
1. 
![image](https://github.com/sissbruecker/linkding/assets/16935251/544161aa-7c0b-44eb-b32c-4ca8c80d76a1)

2. 
![image](https://github.com/sissbruecker/linkding/assets/16935251/0fcaf8b4-83a7-4dd9-a927-3b5fa22df304)

3. 
![image](https://github.com/sissbruecker/linkding/assets/16935251/855805f6-52ce-4448-9a96-98db5669988c)

**Comment by sissbruecker** [comment]
It's expected. The setting is configured per user and stored in the user profile. For guest users there is no profile, so a default one is used. The default profile does not have this setting enabled.
