### ISSUE TITLE
share a linkding ios shortcuts for you 

### ISSUE THREAD

**Issue by Yumega** [sissbruecker/linkding#527]
you can save links to linkding by shortcuts.

https://www.icloud.com/shortcuts/9f99f1710407406cac977f866f479f45

you need change the 192.168.11.1:9490 into your own link

**Comment by yieldhog** [comment]
Thanks!

**Comment by andrewdolphin** [comment]
I've shared my own version using the API and allowing tagging:

**Comment by sissbruecker** [comment]
@Yumega  Could you please:
- Create a Github Gist (or similar) explaining how to set up the shortcut, as in how to install it and set up the necessary variables
- PR the Gist into the [Community](https://github.com/sissbruecker/linkding#community) section

**Comment by sissbruecker** [comment]
Nevermind, I've updated the existing [how-to](https://github.com/sissbruecker/linkding/blob/master/docs/how-to.md#create-a-share-action-on-ios-for-adding-bookmarks-to-linkding) with a similar shortcut. Thanks for the inspiration!
