### ISSUE TITLE
Shared bookmarks page displays notes by default

### ISSUE THREAD

**Issue by bfansheng** [sissbruecker/linkding#533]
Shared bookmarks page is a great feature. I use the shared bookmarks page to share my favorite articles with others and my thoughts on them, so I hope my bookmarks notes can be seen directly by others. currently, the notes on the shared bookmarks page are not displayed by default, which may make it difficult for others to notice my notes. I think it might be a good idea to have the notes displayed by default on the sharing page.

**Comment by sissbruecker** [comment]
I think a setting would make sense here, and can think of at least 3 options:
- Show notes collapsed (current default)
- Show notes expanded / permanently
- Do not show notes at all in case you consider your notes private

**Comment by keybits** [comment]
I'd love the option for Notes to be automatically expanded on the Shared Bookmarks page. This would allow me to use Linkding as a 'blogmarks' site like Simon Willison does: https://simonwillison.net/search/?type=blogmark
