### ISSUE TITLE
Discover related links using tags

### ISSUE THREAD

**Issue by sbhal** [sissbruecker/linkding#534]
I have a question concerning the use of linkding in finding "related links." For instance, while browsing amazon.com, I find it would be very handy to use the linkding extension to display camelcamelcamel.com as a related link, consequently aiding in the discovery of related links. I have an abundance of bookmarks, but many are underutilized due to a lack of efficient discovery methods.

I can use tags to categorize links collectively, but it requires manual steps to discover an entire group of links when visiting just one.

**Comment by sissbruecker** [comment]
While discovering links is indeed important, I'm not really sure what you are suggesting here. Feel free to open a new issue with a concrete proposal of how this discovery mechanism is supposed to work, and how it would help the user in specific use cases.
