### ISSUE TITLE
[BUG] "All pages" checkbox in bulk edit mode selects all bookmarks in database

### ISSUE THREAD

**Issue by Totaxe** [sissbruecker/linkding#536]
There is a bug in v1.21.0 with "All pages" checkbox in bulk edit mode. It always selects all bookmarks from the database, but should only select those filtered.
![msedge_51Cm4nPaMP](https://github.com/sissbruecker/linkding/assets/11377001/190316bc-1891-4c91-8cf0-f92a4e1a2c75)
To reproduce:
1. Create a bookmark with a tag and another one without tags
2. Search by the tag
3. Click "Bulk Edit" button
4. Select all search results and click "All pages" checkbox.
5. Select "Archive" and click the "Execute" button
6. All bookmarks have been archived.

Expected behavior: only the bookmark with the tag should be archived.

**Comment by sissbruecker** [comment]
Thanks for reporting this, should be fixed with v1.21.1
