### ISSUE TITLE
manage.py not found

### ISSUE THREAD

**Issue by fethomm** [sissbruecker/linkding#538]
I tried to install Linkding from the apps section of Unraid yesterday. Instructions say: 
`Creating user by using console "python manage.py createsuperuser --username=joe --email=joe@example.com"`.
Instead of letting me set up a password, I got an error saying: 
`python: can't open 'manage.py': [Errno 2] No such file or directory` 
Looking for 'manage.py' on the system with mlocate yielded nothing. Where do I find or how can I provide it?

**Comment by sissbruecker** [comment]
Unfortunately I can't help with that, as I only maintain the app itself and the Docker image. It definitely works with the Docker image. I would suggest to check with Unraid support or their community.

**Comment by fethomm** [comment]
Thanks for your swift answer, unfortunately the sent me here. :)

**Comment by sissbruecker** [comment]
Heh, OK. Well the only thing I can think of is that you need to run that command in the Docker container, not directly on the host system where you have installed Unraid. Assuming that Unraid uses the Docker image, then `docker ps` should return a list of containers, one of which is the linkding one. Then run the command mentioned [here](https://github.com/sissbruecker/linkding#user-setup), replacing `linkding` with the name of the container you got from the previous command (which might also be `linkding`).
