### ISSUE TITLE
Does not work with neon.tech

### ISSUE THREAD

**Issue by Cologler** [sissbruecker/linkding#539]
Neon offers a managed Postgres database.

I was trying to run a linkding instance (by the docker-compose) and connect to the Neno database, but I got a lot of error messages `Endpoint ID is not specified`.

I found the document from https://neon.tech/docs/guides/django:

> Django uses the `psycopg2` driver as the default adapter for Postgrs. If you have an older version of that driver, you may encounter a `Endpoint ID is not specified` error when connecting to Neon.

**Comment by fivehanz** [comment]
I am using Neon, it works fine. I am using these env vars.

```
LD_DB_ENGINE=postgres
LD_DB_DATABASE=
LD_DB_USER=
LD_DB_PASSWORD=
LD_DB_HOST=--endpoint--.us-east-2.aws.neon.tech
LD_DB_OPTIONS={"options": "--endpoint--"}
```

**Comment by Cologler** [comment]
> I am using Neon, it works fine. I am using these env vars.
> 
> ```
> LD_DB_ENGINE=postgres
> LD_DB_DATABASE=
> LD_DB_USER=
> LD_DB_PASSWORD=
> LD_DB_HOST=--endpoint--.us-east-2.aws.neon.tech
> LD_DB_OPTIONS={"options": "endpoint=--endpoint--"}
> ```

Good job 👍. What I tried before was `LD_DB_OPTIONS={"endpoint": "--endpoint--"}`.
