### ISSUE TITLE
Configure bookmarks per page

### ISSUE THREAD

**Issue by Strubbl** [sissbruecker/linkding#545]
Is it anyhow possible to adjust the number of links being shown per page? My list of tags is so long, that i could easily get more links listed.

please see [my screenshot](https://github.com/sissbruecker/linkding/assets/97055/2faffe71-6eec-4940-87f8-e181ea031eae) for what i mean.

**Comment by krzysztofjeziorny** [comment]
As far as I can tell it's hard-coded here:

https://github.com/sissbruecker/linkding/blob/e83d519cab9b4ace997d9cdc385a1ff133e8be2f/bookmarks/views/partials/contexts.py#L13

**Comment by sdkane** [comment]
Is this something that might get merged in the near future? It seems like krzysztofjeziorny has resolved the issue and it just needs a style check and merge?
