### ISSUE TITLE
API - /api/check_url?url= with token authetification

### ISSUE THREAD

**Issue by Export33** [sissbruecker/linkding#55]
Hi,

the `/api/check_url?url=` API works only with the cookie authentification and not with the token.
Can you make it public? I´m working on a browser addon and could need it.

**Comment by sissbruecker** [comment]
@Export33 Makes sense, this endpoint was written before introducing the REST API. I'll get to it at some point. 

Meanwhile I have written a small extension myself: https://github.com/sissbruecker/linkding-extension. There I simply avoided the issue for now by just using the title from the current tab and ignoring the description. This approximates the saved bookmark reasonably well.

**Comment by Export33** [comment]
nvm. i wrote a method whick checks the existing api and it´s working for me.

i may publish it when i have some more free time. i will also check your implementation ;).
