### ISSUE TITLE
RSS feed error: Control characters are not supported in XML 1.0

### ISSUE THREAD

**Issue by Strubbl** [sissbruecker/linkding#552]
The RSS feed /all gives a server error 500.

`docker-compose logs` shows the following output:

```
linkding  | 2023-10-12 20:15:49,872 ERROR Internal Server Error: /linkding/feeds/asdfghjkll/all
linkding  | Traceback (most recent call last):
linkding  |   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
linkding  |     response = get_response(request)
linkding  |   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
linkding  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
linkding  |   File "/opt/venv/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 48, in __call__
linkding  |     feedgen.write(response, "utf-8")
linkding  |   File "/opt/venv/lib/python3.10/site-packages/django/utils/feedgenerator.py", line 233, in write
linkding  |     self.write_items(handler)
linkding  |   File "/opt/venv/lib/python3.10/site-packages/django/utils/feedgenerator.py", line 246, in write_items
linkding  |     self.add_item_elements(handler, item)
linkding  |   File "/opt/venv/lib/python3.10/site-packages/django/utils/feedgenerator.py", line 289, in add_item_elements
linkding  |     handler.addQuickElement("description", item["description"])
linkding  |   File "/opt/venv/lib/python3.10/site-packages/django/utils/xmlutils.py", line 20, in addQuickElement
linkding  |     self.characters(contents)
linkding  |   File "/opt/venv/lib/python3.10/site-packages/django/utils/xmlutils.py", line 27, in characters
linkding  |     raise UnserializableContentError(
linkding  | django.utils.xmlutils.UnserializableContentError: Control characters are not supported in XML 1.0
linkding  | [pid: 19|app: 0|req: 64/145] 172.30.0.1 () {52 vars in 1050 bytes} [Thu Oct 12 20:15:49 2023] GET /linkding/feeds/asdfghjkll/all => generated 145 bytes in 610 msecs (HTTP/1.0 500) 8 headers in 279 bytes (1 switches on core 0)
```

**Comment by sissbruecker** [comment]
I could use some more info which specific string is causing this issue. From some quick testing, control characters like newlines (`\n` probably) seem to work. Just removing all control characters would actually remove newlines, which seems wrong.

**Comment by Strubbl** [comment]
I found the issue with the help of a [script](https://github.com/Strubbl/remove-control-characters/blob/main/rcc.py). It was the character `` which was part of the description of a bookmark of mine. 

Since this is [not going to be fixed in Django](https://code.djangoproject.com/ticket/30635), i would propose to sanitize the RSS feed items in linkding. I did not use the solution for sanitizing which was given in that Django ticket, but i used the unicodedata module, which can be used to identify the category of the character. The category starts with a `C` when it is a control character.

**Comment by sissbruecker** [comment]
Thanks for looking into it. I'll try to take a look at this sooner rather than later. Maybe stripping all control characters is a reasonable compromise for now. As mentioned above that would also strip newlines, but that is maybe not a big deal. Or a separate condition could avoid stripping specific characters.

**Comment by Strubbl** [comment]
No hurry. I just added the separate condition for the newline. I hope there note many more control characters which shall be kept.
