### ISSUE TITLE
Unraid - Using Cloudflare tunnel unable to get to show 

### ISSUE THREAD

**Issue by saladin1980** [sissbruecker/linkding#553]
EDIT: redoing the below command just noticed an error loading as Label NOT as a env..

Have attempted to manually do the -e commands in console to load and still unable to get to work on the domain listing
Getting bad gateway 502 

Unclear if this is an issue or not but still unable to get this function as the system does not appear to be allowing it through even if set the docker env..

`docker run -d --name='linkding' --net='bridge' -e TZ="America/New_York" -e HOST_OS="Unraid" -e HOST_HOSTNAME="MediaBox" -e HOST_CONTAINERNAME="linkding" -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:9090]/' -l net.unraid.docker.icon='https://raw.githubusercontent.com/A75G/docker-templates/master/templates/icons/linkding.png' -e LD_CSRF_TRUSTED_ORIGINS='https://linkding.saladins.io' -p '9090:9090/tcp' -v '/mnt/user/appdata/linkding/':'/etc/linkding/data':'rw' 'sissbruecker/linkding'`

![image](https://github.com/sissbruecker/linkding/assets/627222/ef293ac0-7314-4267-ba29-451d41f38faa)

**Comment by sissbruecker** [comment]
That seems like an Unraid or Cloudflare problem. I can not help with either of those.
