### ISSUE TITLE
[Feature request] Sync bookmarks: Local Browser <> LinkDing Server

### ISSUE THREAD

**Issue by FlexMcMurphy** [sissbruecker/linkding#556]
I like having a bunch of bookmarks organised in bookmark folders available from my browser bookmark bar.

Linkding is nearly perfect but the one feature I want the most is to **Sync** bookmarks between my browsers regardless of the browser and the OS I am in. I actually want a "local" copy of the bookmarks within each browser in case my LinkDing server is down for some reason.

LinkDing... either working from the browser plugin or from the WebUI to the server.... should be able to single click Sync a folder of bookmarks (that could contain sub-folders of bookmarks) onto a local browser bookmark bar. In fact it should be possible to sync in both directions.

Thank you.
Flex

**Comment by sissbruecker** [comment]
No plans to implement any kind of synchronization in linkding itself, but there is an opportunity for someone to build a 3rd party app / extension to do this by using the REST API.

**Comment by amol-** [comment]
@FlexMcMurphy 

FYI https://mastodon.social/@inlinestyle/115259348289539656 was just announced and might do what you are looking for.
I tried it and have been using it, there are some improvements that need to be done but more or less it does what I needed.
