### ISSUE TITLE
dock version future request

### ISSUE THREAD

**Issue by lilarcor** [sissbruecker/linkding#557]
Hi,
Is that possible to add uid and gid ENV for dock version? The current version is using 33.

Thanks.

**Comment by matthiasbaldi** [comment]
do you already tried just changing the user and group over the `docker run` oder `docker compose` params?

**Comment by sissbruecker** [comment]
For the Docker container you should be able to configure it as mentioned above. For the uwsgi server running within the container it's not possible AFAIK - did you want to configure those specifically?

**Comment by sissbruecker** [comment]
Closing as stale
