### ISSUE TITLE
Feature Request: URL Shortener

### ISSUE THREAD

**Issue by in03** [sissbruecker/linkding#559]
Hey! Great software.

I've been using Linkding and the injector and browser extension for the past few months. Super useful.
I was wondering if a URL shortener would be possible to implement?

If I bookmark an awfully long URL, it would be cool to be able to generate a shorter URL for it that I can share and embed as need be.
For example, if I have a deep link to a OneNote document I want easy access to:

```url
https://mydomain-my.sharepoint.com/personal/me_my_full_domain/_layouts/OneNote.aspx?id=%2Fpersonal%2Fmy_my_full_domain%2FDocuments%2FCaleb%20%40%20Domain%20Word%20Another&wd=target%28New%20Section%20Group%2FInbox.one%7CD8233762-0500-4250-BE3F-485EC0B688BE%2F%29
onenote:https://mydomain-my.sharepoint.com/personal/my_my_full_domain/Documents/Me%20@%20My%20Full%20Domain/New%20Section%20Group/Inbox.one#section-id={D8233762-0500-4250-BE3F-485EC0B688BE}&end
```

That would be much nicer as

```url
linkding.mydomain.com/one-note-document
```

or even a UUID

```url
linkding.mydomain.com/8bb5f944
```

Any thoughts on this?
New to Django, but happy to help out if I can get some pointers!

**Comment by sissbruecker** [comment]
No plans to add that, I would suggest to use a separate tool to generate shortened URLs.
