### ISSUE TITLE
feature request: search as you type / incremental

### ISSUE THREAD

**Issue by qwertz098** [sissbruecker/linkding#572]
Thx for sharing your work with us. 

My suggestion, as i am used to it from other services. Think many other too.

Preferable as an option in settings.

**Comment by sissbruecker** [comment]
This is somewhat challenging to add with the current architecture of the software. For now there are no plans to add this. For alternatives I would suggest to check how the search autocomplete works, or try the browser extension which has a `ld` shortcut for searching bookmarks from the browsers address bar.
