### ISSUE TITLE
Support for custom uri (chrome:// and others)

### ISSUE THREAD

**Issue by webysther** [sissbruecker/linkding#576]
The current browser api support custom uri for some applications and internal links, will be nice to support add this kind of link:

![image](https://github.com/sissbruecker/linkding/assets/750007/b0fae6a6-52f8-4941-87f4-871e2084cc66)

**Comment by sissbruecker** [comment]
This has the same root cause as https://github.com/sissbruecker/linkding/issues/206, please check there for a workaround.
