### ISSUE TITLE
Feature Request: List Sharing

### ISSUE THREAD

**Issue by stonesbg** [sissbruecker/linkding#577]
It would be nice to be able to create lists as a seperate item.

This would simply be a name, description and list of links.  This way you could then share this list externally.

The use case is when writing reference articles it would be nice to embed the linkding shared link which contains the external references.  The added benefit is if you have the archive.org option selected you can get a point capture of that document in case links move in future.

This could be very useful for presentations, conference links

**Comment by jonathan-s** [comment]
@stonesbg One possible solution for this could be to make tags shareable, at the end of the day a tag is a list of links.

**Comment by sissbruecker** [comment]
I think this is already possible:
- Tag all bookmarks with a specific tag
- Search for that tag
- Use bulk edit to mark all bookmarks as shared
- Go to the shared view, search for same tag
- Copy URL and share that with external users
