### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by FIGBERT** [sissbruecker/linkding#58]
I looked into creating a PR for this one, but I'm not sure how to go about it. The current project logo appears to be a [Spectre](https://github.com/picturepan2/spectre) link icon made in CSS, and I couldn't find any `.svg` or raster image version to make into a favicon.

This is a bit of a convenience feature, but it would definitely improve the overall look as I have mine pinned in the Bookmarks bar.

**Comment by sissbruecker** [comment]
Thanks for the reminder, I wanted to do this for ages. After two hours of fiddling with the Affinity pencil tool I got some reasonable result. For now I only added a large PNG and referenced that through a HTML meta tag. That should suffice for most browsers/platforms.
