### ISSUE TITLE
Tag completion doesn't work with newer tags

### ISSUE THREAD

**Issue by alscaldas** [sissbruecker/linkding#580]
Hello. Is there a maximum number of tags possible? I'm asking because I noticed that I haven't been able to use tags completion when adding bookmarks if the tag in question was recently created. Completion with older tags works normally.

Since I have a huge number of tags (in fact it's more than 1400, with 2 different users) I imagine if I reached some limit, or something.

**Comment by hypebeast** [comment]
Yes, it looks like that there is a limit which is set to 1000.

See https://github.com/sissbruecker/linkding/blob/227cfdb0633efe98cab9468af87a9c6e1c8380cd/bookmarks/frontend/components/TagAutocomplete.svelte#L25

Does something to speak against it to increase the limit? I guess from a performance perspective there should be no big difference if we set it to 2000 or even something higher.

**Comment by alscaldas** [comment]
Hey @hypebeast, thank you for taking the time to look into this issue!

I have 2 questions:

Wouldn't it have any sort of performance impact in the daily usage of the tool? I mean... something that was planned to be used with 1000 items now would have 5000, and all...

I use the docker version of linkding. I'd just have to update it or would any further change be needed?

**Comment by hypebeast** [comment]
Hey @alscaldas.

> Wouldn't it have any sort of performance impact in the daily usage of the tool? I mean... something that was planned to be used with 1000 items now would have 5000, and all...

Yes, good question. First, my feeling is that the performance impact of loading e.g. 5000 instead of 1000 is reasonable and should not influence the performance so badly. If you assume in average 10 characters per tag then you will end up with 50K instead of 10K. Which should be fine. But this approach is of course not infinite scalable. If we want to support a lot more tags then we need to think about a different solution. This would mean we need to get the tags on-the-fly, instead of caching the tags in the beginning.

> I use the docker version of linkding. I'd just have to update it or would any further change be needed?

Yes, as soon as the change is released with a new version and if there is a new docker image version, you just need to update your docker image. No other change required.

**Comment by jlhg** [comment]
Would it be better to create an autocomplete API for tag completion instead of loading all tags at first?

**Comment by hypebeast** [comment]
Yes, it would be better. This is the option which would work also with a lot of tags without the need to define an upper limit for the number of tags fetched from the backend. This upper limit can always too low for some installations.

**Comment by alscaldas** [comment]
I noticed you guys altered the number of autocomplete tags and I've just tested it (docker installation). Well, it works ok on the main account. Thing is I have two accounts (I separate personal and work stuff) and noticed the changes won't replicate on my second account. Is it maybe something I'm doing wrong?

Btw, sorry if I should have opened a new issue instead of reopening this one.

**Comment by sissbruecker** [comment]
How do you switch between accounts? Where are you using the tag auto complete - via the bookmarklet?

**Comment by alscaldas** [comment]
Hey @sissbruecker 

I do appreciate you taking the time to look into this issue. 

In fact i don't switch between accounts... I use 2 different Firefox profiles (firefox -P profile1, firefox -P profile2) and most of the time I keep them both open and logged. As for the way I use auto completion, I add all my bookmarks using the main linkding panel (not via bookmarklet). 

So, if I use my user 1, add a new bookmark and create a new tag, when I add another bookmark and start typing that newly created tag it auto completes as desired.

But when doing the same procedure using my user 2 auto complete doesn't work.

Before your intervention it wasn't working in neither accounts with newly created tags.

Btw, I've just noticed that I have 1537 tags total. Account 1 has 235 (this one works fine) and account 2 has 1302 (this one doesn't work).

**Comment by sissbruecker** [comment]
Well, your first account wouldn't have run into the 1000 tag limit even before the change. I just tested creating over a thousand tags, and can confirm that autocomplete still works with newer tags, so for some reason the change is not effective for you. To clarify, you are not using the browser extension, but add bookmarks through the linkding website? As mentioned in the PR, the browser extension has not been updated yet to increase the limit. Also double-check on the settings page that you are indeed running version 1.24.0

**Comment by alscaldas** [comment]
Yeap, I confirm that I'm using version 1.24.0. I've updated yesterday via docker.

And although I installed the browser extension to test a while ago all my bookmarks are added through the linkding website.

**Comment by sissbruecker** [comment]
Maybe you need to do a hard refresh / clear your browser cache, I can see that the cache busting for the JS bundle doesn't work properly.

To double-check that this is effective, you can take a look in the network tab in your browsers dev tools and verify that the following request uses `limit=5000`:
![Bildschirmfoto 2024-01-28 um 22 55 29](https://github.com/sissbruecker/linkding/assets/357820/12d20705-c2aa-4a1f-8dde-b389c328565d)

**Comment by alscaldas** [comment]
Hey @sissbruecker 

It worked when I cleared the browser cache (that now that I think of it should have been my first option, before reopening an issue) :)

I do appreciate your help!
