### ISSUE TITLE
Suggestion: Retain only one tag in tag links in the bookmark list page

### ISSUE THREAD

**Issue by jlhg** [sissbruecker/linkding#584]
Since the multiple tag filtering function has been implemented in the right panel, I'd like to suggest that the tag links under each bookmark retain only one tag. This way, I can quickly search from scratch.

Here is my commit: https://github.com/jlhg/linkding/commit/19b8985dfb609f7f886f4d12cd0be916cfae5be1. If you agree, I can create a PR.

**Comment by sissbruecker** [comment]
I think having a different behavior between tag links in bookmarks and the tag cloud would be confusing. Maybe there could be an option to change the behavior globally (add or replace). Feel free to open a specific issue for that.
