### ISSUE TITLE
 importing bookmarks in this format ，folder information will be lost, resulting in chaos

### ISSUE THREAD

**Issue by zhenruyan** [sissbruecker/linkding#586]
I haven't received a similar issue request, but it supports importing bookmark files in directory format

---- github save
\\--  golang.com
\\ --  xxxx.com
\\--  doc.com
---- host
\\--  vhost.com
\\--  phphost.com

When importing bookmarks in this format, folder information will be lost, resulting in chaos

**Comment by sissbruecker** [comment]
Seems like a dupe of https://github.com/sissbruecker/linkding/issues/69, there are some workarounds mentioned there.
