### ISSUE TITLE
password randomly stopped working

### ISSUE THREAD

**Issue by jpcapone** [sissbruecker/linkding#590]
HI I have been using linkding for quite some time but today I went to login and i randomly got "Your username and password didn't match. Please try again."

I have the username and password cached in my browser so i am 100 sure that its right.  Any suggestions or work arounds?

`docker exec -it linkding python manage.py createsuperuser --username=joe --email=joe@example.com`
i found the command to re create the user but all of my passwords are gone.  I am not 100% sure how this happened but I have to assume its something on my end....

Is there a backend way to import the bookmarks from a text file or something so i can recreate them en masse?

**Comment by sissbruecker** [comment]
It sounds like you didn't mount the data folder to your host system. Did you use the `-v` option to start the linkding container as described [here](https://github.com/sissbruecker/linkding#using-docker)?

**Comment by jpcapone** [comment]
> It sounds like you didn't mount the data folder to your host system. Did you use the `-v` option to start the linkding container as described [here](https://github.com/sissbruecker/linkding#using-docker)?

I did mount the drive.  I can still see the directory on the host.  Thats why i was surprised that the username and password didn't work.  Any suggestions?  I had a lot of good stuff in there - LOL!

**Comment by sissbruecker** [comment]
> Is there a backend way to import the bookmarks from a text file or something so i can recreate them en masse?

Not really, in the settings there is only an import for the Netscape bookmark HTML format which most bookmarking services use. If you have your bookmarks as a text file, you could consider writing a script to convert those into the HTML format so that you can import that. Otherwise I can only recommend to do backups.
