### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by Nietzscheanman** [sissbruecker/linkding#593]
Hello,

Apologies if this is not the right format, I am completely new to selfhosting, linkding and github but eager to learn.

1. I was trying out unraid and am running linkding there.
2. I managed to set up an account and can add and retrieve bookmarks via the browser extension etc. Great!

**Problem: a week or two later I tried to log back into the linkding webui to play around with it some more but forgot the password - is there any way to recover it?**

Thanks!

**Comment by thany** [comment]
Looks like you can add another (temporary) superuser in the CLI:

https://github.com/sissbruecker/linkding#user-setup

In unreaid, click the icon and select "Console", then you can use that command to create a new user:
```
python manage.py createsuperuser --username=joe --email=joe@example.com
```

I haven't tested this myself, but it's probably possible to set a password for your user, when logging in with that new (temporary) superuser.

**Comment by sissbruecker** [comment]
As suggested, creating a new superuser and using that to reset the password on the other account is probably the easiest solution.
