### ISSUE TITLE
[Feature request] Link to Internet Archive

### ISSUE THREAD

**Issue by Superanton** [sissbruecker/linkding#596]
I think it would be handy to have a link to archive.org right under every bookmark like this:

<img width="539" alt="Bildschirmfoto 2023-12-29 um 16 35 59" src="https://github.com/sissbruecker/linkding/assets/803655/81817685-e243-4cae-9de4-06aa57602fe4">

**Comment by jonade** [comment]
I believe this is already the standard behaviour:
![image](https://github.com/sissbruecker/linkding/assets/666707/09a04786-89f1-4870-bc4b-eb8245746f05)

**Comment by Superanton** [comment]
That's right. However, I have not activated the function that links are automatically sent to the Internet Archive and then the link isn't there.

I have imported a lot of old links and would find it useful if there was also a link to the Web Archive, although Linkding has not sent the link to archive.org. For example, to the [overview page of the URL](https://web.archive.org/web/20240000000000*/google.com).

**Comment by sissbruecker** [comment]
If the Internet Archive feature is enabled then importing bookmarks will schedule background tasks to create IA snapshot links. So you could export your bookmarks and then import them again.
