### ISSUE TITLE
[Feature Request] Show bookmark ID

### ISSUE THREAD

**Issue by Sissing** [sissbruecker/linkding#600]
I would love an option to show the bookmark ID on the front end. I see this number is unique and not reused. This would help me to create a "link" between handwritten notes in a notebook and my stored bookmarks in linkding. On top, you should be able to enter the bookmark ID in the search field to find the bookmark quickly.

I'm, of course, not fully aware of the architecture of linking, but any other short ID that's linked to the bookmark would help too.

**Comment by jonathan-s** [comment]
@Sissing This might help you for the time being. If you hover over the edit field of a bookmark you'll see the unique id of the bookmark. 

<img width="335" alt="Screenshot 2024-01-20 at 20 40 32" src="https://github.com/sissbruecker/linkding/assets/2124818/589ce979-af31-4d77-9784-cc24f3548100">

**Comment by sissbruecker** [comment]
No plans to add this.
