### ISSUE TITLE
[Feature request] Local snapshots, snapshot querying, nested tags, folders, and more.

### ISSUE THREAD

**Issue by Opening-Button-8988** [sissbruecker/linkding#604]
I experimented with this application for a few hours and I have some thoughts. I used other bookmark apps such as Shiori, but I found their features to be very lacking. Linkding looks really promising but there's a few **really** essential features missing. I don't think I can quite use it yet in its current state.

### Page Caching
Snapshots should be saved locally as the default snapshot method, with wayback machine as alternative method (user should have choice of both). Local snapshots have two options; 
1. text-only (saves disk-space), 
2. full webpage including images and CSS. Users can select either but not both (which of course would be redundant). 

My reasoning:
- would make querying bookmarks using locally cached content (snapshots) possible. Shiori does this. This is the big missing feature that's stopping me from using Linkding instead of Firefox bookmarks. I don't know what I'm talking about, but I recently discovered `jq`, which might be something Linkding could implement so we can query our bookmarks?
- viewing pages on wayback machine is usually slow and generates unnecessary traffic/congestion because pages can be cached locally instead. There may be use cases for it, but local cache should be the primary method.

As a possible addition to this feature, local snapshots can optionally include a local snapshot of the homepage of the saved page, which could provide context for the bookmark (if this option is enabled, bookmarking `https://website.com/some_page` would also save `https://website.com`. 

### View options / structure:
- Option to switch to nested tags (tag within a tag). Provides a more robust visual interface to find and query bookmarks more easily. It makes more sense to my brain. Example: Standard Notes.
- Option to switch to folders for bookmarks. In addition to their tags, they can be placed in custom folders, and folders can be nested in other folders (tree structure). Example: Firefox bookmarks. Note, personally I like both nested tags and folders, I would probably use nested tags but I would like the option to choose.
- Compact views. I have thousands of bookmarks, thumbnails take up a lot of space, too many pages. Toggle to hide thumbnails?

### Other stuff
- Archiving should be repurposed to mean bookmarks that have a locally saved snapshot. It makes logical sense to me that archived means something that has been cached locally.
- more robust appearance settings. Wider UI and different themes.
- tags should be comma-separated instead of space-separated
- functional export, and more export formats (I noticed this is apparently being worked on).
- add tags to multiple bookmarks at once

I might've suggested something that's already been suggested, or already implemented. With the number of features I've listed and the detail I've given, I hope you can give me a pass for that. Thank you.

**Comment by sissbruecker** [comment]
Closing as I think most of those are covered by existing issues.

**Comment by grand-lotus-iroh** [comment]
Hey @Opening-Button-8988 — Do you know if nested tags (tag within a tag) was ever integrated? Did you find a solution?
