### ISSUE TITLE
Description is obscured by many tags

### ISSUE THREAD

**Issue by jonathan-s** [sissbruecker/linkding#605]
If you have many tags for a link the description will be completely obscured by the tags. It would be better to have the description on it's own row. 

<img width="660" alt="Screenshot 2024-01-19 at 13 05 47" src="https://github.com/sissbruecker/linkding/assets/2124818/16ced8d7-00d6-420c-bd09-4b6828e9a870">

**Comment by sissbruecker** [comment]
Should be a duplicate of https://github.com/sissbruecker/linkding/issues/326
