### ISSUE TITLE
Android - > share with (maybe via https://http-shortcuts.rmy.ch/ )

### ISSUE THREAD

**Issue by MrColumbo** [sissbruecker/linkding#608]
If i get it right there is still no easy way to share a URL from Android with lingding, right? I thought that HTTP Shortcuts could be maybe used for that purpose. 

Oh - i see it already exist but it is not mentioned here, right?

https://github.com/sissbruecker/linkding/blob/master/docs/how-to.md#using-http-shortcuts-app-on-android

**Comment by sissbruecker** [comment]
Not sure what the actual question is, but the docs that you linked should explain how to set up a shortcut in HTTP shortcuts. If you feel that something could be explained better consider opening a PR to improve the docs.

**Comment by danielyrovas** [comment]
Hey @MrColumbo are you interested in testing an Android app to solve this? I have written a small unofficial client for LinkDing [here](https://github.com/danielyrovas/linklater).
You can install it directly from the releases or using [Obtainium](https://github.com/ImranR98/Obtainium).
