### ISSUE TITLE
Tasks and Toasts

### ISSUE THREAD

**Issue by quistuipater** [sissbruecker/linkding#610]
I've been using Linkding for six months and it's great. Very happy with it.

But ...

I know what toasts are but how are they used in Linkding?

Same for tasks ... what are they in Linkding and how can they be used?

**Comment by sissbruecker** [comment]
Some info about tasks: https://github.com/sissbruecker/linkding/issues/451#issuecomment-1511705236

Toast are a mechanism to show messages to users at certain points. Have only used them once so far for informing users that the default for an option had changed after an upgrade. That was likely before you started using the app.

So in general those are internal things that are not relevant to bookmarking, but that the app needs to store somewhere.
