### ISSUE TITLE
Progress Indicator while the db is busy

### ISSUE THREAD

**Issue by bphenriques** [sissbruecker/linkding#611]
Hello, 

Thank you for the project! I am importing and assigning tags to my Firefox bookmarks. Albeit I am usinga 7200rpm hard-drive, some operations do seem slow (not too slow), specially when doing operations in bulk (using the default settings).

Would be great seeing some progress indicator in the page and perhaps block some input elements while that is happening (ideally these would queue). For example, noticed that the some operations are not successful due to `sqlite3.OperationalError: database is locked`. Most times, I have to wait until the items with checkbox disappear while I clear the `!untagged` queue.

I am somewhat conflating two issues, but perhaps this context is helpful.

**Comment by sissbruecker** [comment]
Which linkding version are you using? I made a change some time ago to prevent lock errors, but maybe it's not effective.

Slow is subjective - like how slow? Less than a second, multiple seconds? You could check the network tab in your browsers dev tools to get a concrete measurement. You could also take a look at the linkding demo instance for comparison, which is reasonably snappy, but also uses faster storage than a hard drive.

Loading indicators can be tricky, if an operation only takes a fraction of a second for users with faster hardware they are more annoying than helpful. Not totally against them, but requires some consideration and maybe a more complex implementation to only show them after a delay. Apart from that there is potential for performance improvements for bulk operations, which could be more valuable to spend time on.

**Comment by bphenriques** [comment]
> Which linkding version are you using? I made a change some time ago to prevent lock errors, but maybe it's not effective.

I started up today so it should be the `latest`.

> Slow is subjective - like how slow? Less than a second, multiple seconds?

3-4 seconds. 

<img width="1512" alt="image" src="https://github.com/sissbruecker/linkding/assets/4727729/48df4503-f747-4280-996c-bff4bad187ee">

https://github.com/sissbruecker/linkding/assets/4727729/c52cf182-a538-4733-b8de-d78ac7559116

> Loading indicators can be tricky, if an operation only takes a fraction of a second for users with faster hardware they are more annoying than helpful. Not totally against them, but requires some consideration and maybe a more complex implementation to only show them after a delay. Apart from that there is potential for performance improvements for bulk operations, which could be more valuable to spend time on.

I do agree. No need for loading indicator if they are fast. In my case, it was slightly annoying as I had to wait for the previous bulk update to complete before I moved on to a different batch (another suggestion is to have in-line tag edit). 

Nothing out of the ordinary in the logs. I am running in a NAS 923+ with 7200rpm disks if helpful. Apart from the usual, I added `user: "${PUID}:${GUID}"` in my `compose.yml`.

**Comment by sissbruecker** [comment]
Thanks, that is a lot slower than I'd like it to be, especially when only selecting a few bookmarks. I can only guess it's related to the hard-drive, a similar operation takes a fraction of a second on the demo instance (uses NVME drive I believe), and maybe half a second on the Raspberry Pi 3b I use for hosting.

I started toying around with some performance improvements related to bulk operations, maybe I can release those over the weekend. Didn't spend much time on optimizations for those as SQLite is really fast, but I guess only if you use an SSD or flash drive.

The database lock issue I'll have to keep in mind, that might require some more time to debug.

**Comment by bphenriques** [comment]
Thank you. I am available if you need me to make more tests. The database lock didn't happen while I recorded the video but it did happened while I was trying to edit multiple bulks in sequence.

Coicidently I might receive some SSD this week and I can provide you feedback once I migrate my docker volumes over there. I can hold-off the upgrade if it helps you, however you might be able to get raw numbers by benchmarking locally.

TBH, I never thought hard drives could be this slow. I guess we all got used to SSD.

**Comment by bphenriques** [comment]
Migrated to SSD and it is so much faster. I dont notice any delay (~250ms in web dev tools).

In any case, it is up to you how you want to handle this ticket. I don't know how many self-hosted setups use regular hard-drives and this ticket's feedback seem useful (perhaps warn if the disk is too slow?).

**Comment by sissbruecker** [comment]
For now I've made improvements to the bulk tag performance, can reconsider adding a loading indicator if someone else has problems.
