### ISSUE TITLE
Using pip-compile to generate full requirements

### ISSUE THREAD

**Issue by jonathan-s** [sissbruecker/linkding#615]
Right now I'm not entirely sure what the status of the requirements.txt file actually is. It looks like we're trying to keep dependencies locked so that an update of a dependency won't inadvertently break the project. 

Manually ensuring that each dependency is up to date can be a bit cumbersome especially if you commit to keeping track of transitive dependencies. I think a step in the right direction would be to use `pip-compile`, that way you'll only need to keep track of and update the top-most dependencies. 

https://github.com/jazzband/pip-tools/

**Comment by sissbruecker** [comment]
Currently taking a look at pip-tools, being able to list app dependencies only, and having comments where transitive dependencies come from should make things easier. I guess dependabot should still be able to work with this setup, and will continue to suggest changes to the requirements files directly.

**Comment by sissbruecker** [comment]
Something like this: https://github.com/sissbruecker/linkding/pull/618

**Comment by joshuadavidthomas** [comment]
Yep, dependabot works just fine with a setup revolving around `pip-tools`. That's what I use on any Django project I work on. Example dependabot PR: https://github.com/joshuadavidthomas/joshthomas.dev/pull/250
