### ISSUE TITLE
minor ui nitpicks

### ISSUE THREAD

**Issue by WasabiPizza** [sissbruecker/linkding#62]
Hi, first of all thank you for making linkding! I've been looking for a while for a selfhosted alternative to pinboard.in and I think I finally found one.

I just wanted to comment on two minor issues:
1. The search bar and button on mobile don't look like they do on desktop, is this intentional? Because it doesn't look good in my opinion.
2. Always on mobile, the hamburger menu can't be closed once it has been opened. I have to click on a link or on the search bar to hide it.

Thanks!

**Comment by sissbruecker** [comment]
@WasabiPizza Thanks for reporting this, I'll definitely look at this when I find the time. Meanwhile, can you please elaborate on 1., maybe with a screenshot on your device? Personally I can not see any issue when using dev tools or my mobile device.

**Comment by WasabiPizza** [comment]
Sorry I should have added a screenshot in the first place. Anyway here’s how it looks on my iPhone on Safari, strangely if I choose responsive in the dev tools the search bar looks fine.

![3178A0E2-EB6B-4752-A3B6-F32BB48E0975](https://user-images.githubusercontent.com/54906581/107125432-4f5a9e80-68aa-11eb-8bfa-06aa4a78e5cf.jpeg)

**Comment by sissbruecker** [comment]
Thanks, looks like mobile Safari has some very specific opinions on how `<input type="search">` should be displayed. I think I'll change it to a regular input and add some aria role instead.

**Comment by sissbruecker** [comment]
Fixed the searchbox styles and added Javascript for closing the mobile dropdown menu in case the browser does not trigger blur events on outside clicks.

**Comment by WasabiPizza** [comment]
Thank you! I have just updated and the search box looks very nice now!

Not sure about the menu though, now it can be closed by tapping anywhere on the screen but the menu itself. Not sure if it is the indented behavior but I guess reporting it doesn’t hurt.

**Comment by sissbruecker** [comment]
@WasabiPizza You're welcome 🙂. Yes the menu behaviour is intented.
