### ISSUE TITLE
[Feature Request] Add the ability to re-order bookmarks

### ISSUE THREAD

**Issue by Jay-Andrade** [sissbruecker/linkding#631]
My usage of Linkding is setting my homepage to the URL for a set of commonly-used tags. I use this homepage everyday and get used to the order the bookmarks are in. When I want to add a new bookmark it adds to the top of the list which throws me off. I am wondering if it'd be possible to add the ability to re-order bookmarks for this reason.

**Comment by sissbruecker** [comment]
Understandable, but honestly linkding isn't a great fit for this use case at the moment. It's a bookmark manager, not a dashboard, and I don't think that mixing bookmark and dashboard functionality in the same view would result in a good UX. I might add a dedicated dashboard view or something to linkding at some point (could use a dashboard myself), but for now I'd recommend you to check out some of the great open source dashboards that are out there.

**Comment by Jay-Andrade** [comment]
I'm using it as more of a hybrid between the two and it works well for me with my current usage. I don't frequently need to adjust the 'ranking' of bookmarks and would be happy to do some manually tinkering if that could be a solution without cluttering up the UI. Right now I'm just deleting the bookmark and re-adding it to get it to show up at the top of the list and am only doing this once a month or so. If you have any ideas please let me know. If not, I appreciate you getting back to me and really appreciate you creating and maintaining this fantastic project.

**Comment by GD2021** [comment]
I'll reconsider and add the dashboard
