### ISSUE TITLE
can I user https://demo.linkding.link/bookmarks and its token to test API

### ISSUE THREAD

**Issue by matthewxu** [sissbruecker/linkding#639]
can I user site:https://demo.linkding.link/bookmarks and its token to test API;
when I use IOS client from  https://github.com/amoscardino/linkthing, it shows wrong settings.

**Comment by sissbruecker** [comment]
I have used the demo installation with the browser extension previously and can confirm that it works. Note that the demo installation only supports IPv6 addresses, so maybe the app, or your network, has problems resolving those.
