### ISSUE TITLE
Editing tags of a link does not work

### ISSUE THREAD

**Issue by Strubbl** [sissbruecker/linkding#643]
When i edit a link, the changes are not saved.

1. Go to /bookmarks
2. Select any link and hit "Edit"
3. Add some tags to that link
4. Hit "Save"
5. Link is not saved, but only the form is reloaded - even with my added tags. I would have expected that the changes are saved and that i get back to /bookmarks.

I use linkding version 1.24.0. The browser console shows no obvious error.

**Comment by jonathan-s** [comment]
I think you'll have to provide more around your setup for me to be able to say anything, since I have the application running on my end and it works as expected.

**Comment by Strubbl** [comment]
Thank you for the feedback. I am using the docker-compose setup. I just redid my setup and it fixed this issue and i have no idea why. Sorry for the noise .
