### ISSUE TITLE
User authentication using LDAP

### ISSUE THREAD

**Issue by wachtell** [sissbruecker/linkding#645]
Thank you for linkding 😃
I wondered if there is any possibility to user authenticate using Active Directory or LDAP?

**Comment by sissbruecker** [comment]
Currently linkding only allows you to configure an authentication proxy, if that proxy supports those, then yes. Otherwise this is tracked in https://github.com/sissbruecker/linkding/issues/177.

**Comment by wachtell** [comment]
Thank you!
