### ISSUE TITLE
logout button method GET which is no allowed (405)

### ISSUE THREAD

**Issue by mathos77** [sissbruecker/linkding#646]
Hi,

Running the :latest tag today, the logout button does a GET of /logout/, and DevTools shows a `405: Method not allowed` 

<img width="865" alt="image" src="https://github.com/sissbruecker/linkding/assets/19706662/ed2f39cf-95fb-4d92-b12a-243845773b5c">

Is this a known issue, not seen it in the open.

Plain setup here with just postgres as a DB backend, running in Podman.

Kind regards, Math

**Comment by sissbruecker** [comment]
Thanks, must be due to updating Django to a new major version. Should be fixed with #648

**Comment by mathos77** [comment]
Works like a charm, and the fix speed !!!! 
*bows*
