### ISSUE TITLE
Bug: Two equal tags with different capitalisation lead to 500 server errors

### ISSUE THREAD

**Issue by mattofr** [sissbruecker/linkding#65]
When some bookmarks have tag 'freebsd' and another has a tag 'FreeBSD', than adding new bookmarks with either the tag 'freebsd' or 'FreeBSD' returns a Server Error (500)

**Comment by sissbruecker** [comment]
I already noticed this, its very likely that this was introduced with #45 . In the meantime you can fix this by removing the duplicate tag in the admin. At least in my case one of the tags was unused and was thus easy to delete.

At least #45 should ensure that it's not possible anymore to create duplicates with different capitalization.

**Comment by mattofr** [comment]
Thanks ! In the admin I deleted the tag 'freebsd' and now I can use the tag 'FreeBSD' again, without 500 errors :)
