### ISSUE TITLE
Default new links to unread?

### ISSUE THREAD

**Issue by wzzrd** [sissbruecker/linkding#669]
Hey, I use linkding a lot to collect articles that I want to read later. Kind of like Pocket or Wallabag or something like that. Would it be possible to have a setting to make "Mark unread" default to true when adding new links? Or does that exist and did I just miss it?

**Comment by sissbruecker** [comment]
At the moment only with the browser extension, which has a setting for this. I'd be fine with a contribution that adds an option for this to linkding itself.

**Comment by grand-lotus-iroh** [comment]
![1pf-1me](https://github.com/sissbruecker/linkding/assets/1291364/b2f7807a-77c2-493c-b051-ec935f1c2bb6)

Grab it here — https://chromewebstore.google.com/detail/linkding-extension/beakmhbijpdhipnjhnclmhgjlddhidpe
