### ISSUE TITLE
Do not create multiple queued tasks for snapshots

### ISSUE THREAD

**Issue by mpraeger** [sissbruecker/linkding#673]
After installing the `latest-plus` docker image and queuing a couple of snapshots I've noticed that clicking on "Create HTML snapshot" multiple times will result in multiple snapshots being queued:

![linkding_multiple_snapshots](https://github.com/sissbruecker/linkding/assets/27342388/5c2022f2-0864-45e4-99f3-667897fcabf4)

That's probably not what what one wants in this case; a check should be made and no further tasks should be queued when an existing one is found for this bookmark.

**Comment by sissbruecker** [comment]
Sounds reasonable. It should be possible to keep multiple snapshots in general, but you're right that queuing multiple of them doesn't make sense.

One thing I definitely want to add is that the UI updates when the snapshot is done. I have a hunch it could be confusing at the moment if people sit there and wait for it to complete even though the UI doesn't even support that.
