### ISSUE TITLE
Add option to create snapshots for existing bookmarks

### ISSUE THREAD

**Issue by nadir-ishiguro** [sissbruecker/linkding#676]
Hi,
I just gave the new snapshot feature a try and it's wonderful. Thank you very much.

I'm wondering if there's a plan to add an option to create snapshots for multiple or all existing snapshots.

**Comment by johnmaguire** [comment]
Absolutely loving the snapshot feature, huge thanks to everyone who worked on it.

I would also love to see this FR implemented. Perhaps it could be done as one of the bulk actions?

<img width="700" alt="Screenshot 2024-04-10 at 2 13 04 PM" src="https://github.com/sissbruecker/linkding/assets/440033/0c368498-5982-46e9-845b-1d7340479899">

**Comment by nadir-ishiguro** [comment]
> Absolutely loving the snapshot feature, huge thanks to everyone who worked on it.
> 
> I would also love to see this FR implemented. Perhaps it could be done as one of the bulk actions?
> <img alt="Screenshot 2024-04-10 at 2 13 04 PM" width="700" src="https://private-user-images.githubusercontent.com/440033/321358251-0c368498-5982-46e9-845b-1d7340479899.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NzU2NjgsIm5iZiI6MTcxMjc3NTM2OCwicGF0aCI6Ii80NDAwMzMvMzIxMzU4MjUxLTBjMzY4NDk4LTU5ODItNDZlOS04NDViLTFkNzM0MDQ3OTg5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxODU2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjQ3Y2Y5MDBmNWE5ZWM1MjE4YzgyOTdhYmJiNzk5NjA1MTFkNDZiODJhYTNkYjVkMWYyNmZiZWFjODY3NzNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sBWwUmR2z-1NSJ9ln1UP3-H9b2DHgL1Sf0ma5YbN-sk">

That's exactly what I had in mind.

**Comment by sissbruecker** [comment]
I wonder how people would use such a feature. Would they only use it once to create snapshots for bookmarks that were created before migrating to the linkding version that automatically creates snapshots? In that case a button in the settings might be enough, which would only create snapshots for bookmarks that don't have a (successful) snapshot yet.

Or is there a specific use-case where you would specifically want to create new snapshots for a selection of bookmarks, even though they might already have one? Note that a bookmark can have multiple snapshots, so the bulk action should probably always create a new one. But that I feel that's not the intention here.

**Comment by johnmaguire** [comment]
> Would they only use it once to create snapshots for bookmarks that were created before migrating to the linkding version that automatically creates snapshots?

This is the primary reason I'm interested in this feature, and a button in the settings would suffice just fine.

> Or is there a specific use-case where you would specifically want to create new snapshots for a selection of bookmarks, even though they might already have one?

I find this idea interesting, but it's unimportant to me. For this, I'd rather have a schedule (like, re-snapshot pages yearly.) But I'd also probably only want to target specific tags for this.

The only other reason I can imagine wanting to use the bulk action is perhaps to choose specific links after filtering (e.g. maybe there's no point in fetching YouTube pages.)
