### ISSUE TITLE
Promote single-file timeout to env variable

### ISSUE THREAD

**Issue by pettijohn** [sissbruecker/linkding#685]
https://github.com/sissbruecker/linkding/blob/5d8fdebb7c4918c3face9478543ccf86b2db47ef/bookmarks/services/singlefile.py#L27

Can you please promote single-file timeout value to an environment variable? I run linkding on a raspberry pi and sometimes taking a snapshot is sloooow. 

For example:
```
time single-file https://www.hightidestoredtla.shop/products/bullet-ballpoint-pen-light?variant=38
087018184895

real    1m31.228s
user    0m13.667s
sys     0m11.835s
```

In my case I'd like to set a maybe 2 or 3 minute timeout.

**Comment by sissbruecker** [comment]
Sounds like a good idea 👍. Since you already know how it's done, care to make a contribution?

**Comment by pettijohn** [comment]
Weird you want me to help and not just complain? :) Sent a PR. Had to figure out how you're using settings and a quick hot-patch way to test.
