### ISSUE TITLE
You should PR yourself into 'awesome self-hosted'

### ISSUE THREAD

**Issue by derekslenk** [sissbruecker/linkding#7]
Don't know if you are aware of this list: https://github.com/awesome-selfhosted/awesome-selfhosted

I checked out the [requirements](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/PULL_REQUEST_TEMPLATE.md) for PRing your app into the repo and I think you meet all of those applicable check-boxes.

I thought about doing it for you but didn't feel right.

Sorry for creating an issue, only way I can see to get a hold of you.

**Comment by sissbruecker** [comment]
Thanks for the hint, I'll take a look when I find the time. And no worries about communication like this here.

**Comment by snow-jallen** [comment]
I wholeheartedly agree, this is a great project.  :)  Thank you!

**Comment by sissbruecker** [comment]
Created a PR on the list: https://github.com/awesome-selfhosted/awesome-selfhosted/pull/1999
