### ISSUE TITLE
Auto logout

### ISSUE THREAD

**Issue by nirav-mj** [sissbruecker/linkding#700]
Hello,

First of all thank you for the excellent application and all the hard work went in creating this awesome app. Is there a way to enable auto logout option, currently user session remains signed in all day.

Thanks, 
NNS

**Comment by nirav-mj** [comment]
I will try it and will follow-up.
Thank you

**Comment by nirav-mj** [comment]
I'm running it in Docker so 100% sure how to get to the file, I will figure it out. Also, is there any option to find and remove duplicates and/or option not to import duplicates? I can't find it in the documentation.

**Comment by sissbruecker** [comment]
Looks like the import would not detect if the imported HTML contains duplicates. If there's already a bookmark with the same URL in the DB, that will be updated by the import at least. Also when adding bookmarks in linkding you can not create duplicates, it always updates the existing bookmark and will warn you about that.

**Comment by sissbruecker** [comment]
Thanks, but at this point I don't accept donations. You could consider donating to the [Internet Archive](https://archive.org/donate) instead if you make use of the linkding feature that creates snapshots on the IA whenever you save a bookmark.

**Comment by nirav-mj** [comment]
I will once I enable the Archive option. If I missed LINKDING is AWESOME!!
