### ISSUE TITLE
Novice help.

### ISSUE THREAD

**Issue by Mei-jing** [sissbruecker/linkding#71]
Hello, I am a novice, how to deploy linkding to heroku, I tried several times, but failed, I hope the boss can provide a tutorial, thank you very much!

**Comment by sissbruecker** [comment]
@Mei-jing Making this application easy to use and easy to install is important an important aspect of it and I'm aware that the current installation methods are an entry barrier for, well, most people. As such I'm willing to make improvements in that area. I'll keep this topic open until I come up with some ideas on how to do so. This is also an opportunity for someone from the community to help out.

Regarding Heroku specifically: Getting linkding to run on Heroku, especially for free, is probably one of the more complicated setups and not something that I would support. linkding stores it's database on the file system by default, which will be a problem with Heroku dynos which do not have a persistent file storage (AFAIK). 

For now I would suggest to focus on hosting options that allow you to run Docker and have a persistent storage. For example I host the linkding demo instance on a Digital Ocean Droplet for about 5 dollars each month which is reasonable. Of course there are many other options like AWS or Google CloudPlatform.

**Comment by Mei-jing** [comment]
OK, I'll try. Thank you.
