### ISSUE TITLE
ability to configure the default profile used for anon users

### ISSUE THREAD

**Issue by soph-sol** [sissbruecker/linkding#714]
I'd love to have the ability to configure the default profile used for anonymous users, so that when people visit my shared bookmarks page, it's set up to display information in a way that's helpful for the kinds of things I bookmark.

Specifically I'd like to be able to set how many lines of the description are visible, as well as add custom CSS the way I can for my own user profile.

**Comment by bloodripelives** [comment]
This would be great!

**Comment by nuriarita** [comment]
I'd love that!
