### ISSUE TITLE
Suggestion for tag sorting functionality

### ISSUE THREAD

**Issue by GD2021** [sissbruecker/linkding#716]
![image](https://github.com/sissbruecker/linkding/assets/81171294/6013ca23-b668-4453-bfdb-851de967f89f)

I currently have many tags, but they look quite messy. 

For example, I'd like to place ---

图片-放大  图片-压缩   图片-编辑
图片-美化  图片-修复   图片-生成
------------------------------------
视频-编辑  视频-美化 视频-生成

1. Text alignment with consistent line breaks.
2. Adjustable tag sorting positions.
3. Ability to add separators.

1. How can TAGs be manually broken? Automatic line breaks may cause misalignment, appearing unattractive.
2. How can TAG positions be customized? For example, I want to group design or image categories together.
3. Simplified Chinese cannot be sorted alphabetically; currently, English characters must be added before Chinese characters to prevent them from being crowded together.

It is suggested to support Simplified Chinese. From what I understand, the lack of Chinese support has deprived Chinese YouTube bloggers of a reason to recommend it. If Simplified Chinese is supported, I believe it will greatly increase the user base and make the project more influential.

**Comment by GD2021** [comment]
Or it can be made into a directory tree or an alphabetical order:

Example: First Alphabetical Order

A
#apple

B
#bard

C
#cici copilot

Also add a background blur to the tags
![image](https://github.com/sissbruecker/linkding/assets/81171294/d4ccd1dc-99e1-4ea5-b8b9-4fa67e1b868e)


Example: Catalog tree

![image](https://github.com/sissbruecker/linkding/assets/81171294/117cdac9-bdc9-4c79-84ac-44fd75c2a418)

**Comment by bfansheng** [comment]
I also met with the same problem.

**Comment by sissbruecker** [comment]
While I agree that the current tag cloud doesn't work very well for Chinese characters at the moment, I'm not sure that manually curating the way how tags are displayed is the way to go. I think you should keep track of https://github.com/sissbruecker/linkding/issues/285 and see what eventually comes out of that.
