### ISSUE TITLE
"... archiving websites as HTML snapshots"?

### ISSUE THREAD

**Issue by MarcelBigger** [sissbruecker/linkding#719]
In the description, shouldn't this instead read "taking a snapshot of **a single Web page**" or something similar?

Or has _linkding_ Web scraping functionality to specific hierarchical hyperlinked page depths?

**Comment by sissbruecker** [comment]
No it doesn't, it only takes a snapshot of the bookmarked URL.

**Comment by MarcelBigger** [comment]
Yes, that's what I mean. In the README, you should change:

"Automatically archive web**sites**, either as local HTML file or on Internet Archive"

to:

"Automatically archive web**pages**, either as local HTML file or on Internet Archive"
