### ISSUE TITLE
Excessive runtime memory footprint?

### ISSUE THREAD

**Issue by MarcelBigger** [sissbruecker/linkding#720]
Reading about the runtime memory issues got me very worried about the runtime memory footprint of _linkding_ on a typical Windows 10/11 machine. Can you add some information on memory use in the README?

**Comment by sissbruecker** [comment]
From what I understand, the more memory is availabe to a Docker container the more it will use, unless you explicitly run the container with a memory limit. One cause is that the Linux system running in the container will cache accessed files in memory, and it will continue doing that if it still has memory available. So the stats that people report will vary, depending on how much memory is available on their host system, and how much they give to the container.

That being said, I run the base image on a Raspberry Pi with 1GB RAM, of which linkding takes up 230 MB. For the plus image, which runs Chromium for creating snapshots of websites, memory usage can easily spike way beyond that. To run that you should give the container 1GB of memory to be on the safe side.

Not sure if I can document any conclusive stats yet, but I will consider doing so in the future.
