### ISSUE TITLE
URL Validation should be optional

### ISSUE THREAD

**Issue by ohare93** [sissbruecker/linkding#727]
I cannot add a bookmark as it is not valid. 

> Error saving bookmark: Validation error: {"url":["Enter a valid URL."]}

However the bookmark in question is a local environment override specific to my place of employment 😅 It is: `http://octopus/app` which takes one to the deployment application Octopus hosted on premises. So due to local (work VPN) network rules the link does work, but it is not technically a valid url.

### Solution?

Let me ignore this error. Bring up a warning when I hit save on a url like this, but let me save it anyways with another click.

**Comment by sissbruecker** [comment]
https://github.com/sissbruecker/linkding/blob/master/docs/Options.md#ld_disable_url_validation

**Comment by ohare93** [comment]
I don't want to disable the url validation. I like the feature, it is helpful incase one mistypes/miscopied the url in question. I just wish it wasn't so strict and could be overwritten on a case by case basis.
