### ISSUE TITLE
[Feature Request] Display multiple columns

### ISSUE THREAD

**Issue by BadCoder12** [sissbruecker/linkding#738]
I would like the feature to display all the tags or selected tags on the main page.
TAGS1   TAG2
URL       URL
URL       URL
URL       URL

**Comment by sissbruecker** [comment]
Sorry, I don't really understand your request at all. Apart from making it clearer, it would also help to explain how this would be useful.

**Comment by BadCoder12** [comment]
I wanted a way to see multiple tags at the same time in columns. So Column 1 will have TagX and Column2 will have TagY

**Comment by sissbruecker** [comment]
No plans for adding that I'm afraid.

**Comment by BadCoder12** [comment]
In the end, I created a new tag for most used bookmarks and I open that.

**Comment by sissbruecker** [comment]
Thanks, sounds like you wanted a dashboard of some kind. Have you considered just running a dashboard app next to linkding and then duplicating links between both, or keep frequently used links in the dashboard only? I'm kind of curious why people want a dashboard in linkding, and what the benefit would be vs. just using a dedicated app for that.

**Comment by BadCoder12** [comment]
I wanted a easy way to access my "most used" bookmarks. I have 100s and use less than 20 on a day-day / weekly basis and wanted easy access to it. Adding a secondary tag of "MostUsed" and filtering it to that and pining that tab, helped a lot.
Any other bookmark, I just load linkding and search it.
