### ISSUE TITLE
[Documentation Update Request] Add Linklater to 'Community' section

### ISSUE THREAD

**Issue by cameronj86** [sissbruecker/linkding#741]
[Linklater](https://github.com/danielyrovas/linklater) is a new Android client. 

Still in its infancy from the look of things, but personally, the fact that it allows for Android Share instantly makes it more useful than using the Firefox Mobile extension.

**Comment by sissbruecker** [comment]
Feel free to add it, you can edit the README yourself through the Github UI to open a pull request.
