### ISSUE TITLE
X-axis scroll for smaller screens on settings page

### ISSUE THREAD

**Issue by brettinternet** [sissbruecker/linkding#742]
Hello! This is a fantastic project.

I'm noticing x-axis scrolling on smaller screens on the settings pages due to this `:after` block in the settings tab menu: https://github.com/sissbruecker/linkding/blob/fa5f78cf71db68c0bef8447b6e6a6176fcbf3465/bookmarks/styles/bookmark-page.scss#L180-L200

I'm not sure what this CSS block does, but if it shouldn't be removed, could we add `overflow: hidden` to the parent `ul`?

**Comment by sissbruecker** [comment]
This might already be resolved with https://github.com/sissbruecker/linkding/commit/ff334e08884e90150718f7107361bd53e3d79b57. I guess you could verify by adding this as custom CSS.
