### ISSUE TITLE
titles of  some websites  cannot be recognized

### ISSUE THREAD

**Issue by MichaelC001** [sissbruecker/linkding#745]
https://www.zhihu.com/question/657302101
https://www.zhihu.com/question/657354774
https://www.zhihu.com/question/554200932/answer/3498946863
https://www.zhihu.com/question/367357782/answer/3409674587

**Comment by sissbruecker** [comment]
Looks like that site has some sort of bot protection that prevents automated access to the actual page content. Not much I can do here I'm afraid.
