### ISSUE TITLE
Retrieving an user token

### ISSUE THREAD

**Issue by kix2902** [sissbruecker/linkding#756]
I'm thinking on developing a native Android application to allow for an easy function to add links to Linkding from any app.

The problem I'm facing is that retrieving an user token without the user intervention is mainly impossible so I'm here requesting an endpoint to obtain it passing it the login info or a full oAuth2 path.

Thanks in advance.

**Comment by sissbruecker** [comment]
Users would only need to enter the token once when setting up your app. There's a number of native apps already that use an approach like this.

I don't think I want to support a full OAuth workflow and storing authenticated apps or somesuch.
