### ISSUE TITLE
Feature Request: Add Option to enable/disable automatic description when adding a bookmark

### ISSUE THREAD

**Issue by dxnxz** [sissbruecker/linkding#760]
Hi there!

Thanks for your great work. I noticed something:
- open the dialogue to add a bookmark
- paste the link -> description is prefilled
- click the edit button next to description
- remove the text from the textbox
- save the bookmark
- description is still saved

If that is by design, would it be possible to add an option to toggle the automatic description?

Best, 
Deniz

**Comment by sissbruecker** [comment]
Duplicate of https://github.com/sissbruecker/linkding/issues/15
