### ISSUE TITLE
Date and time incorrect

### ISSUE THREAD

**Issue by ados8** [sissbruecker/linkding#764]
I've added the TZ variable to the Unraid docker template but it continues to show the time and therefore date far behind.
At first I thought it was the snapshot system as it might have it's own timezone but even the bookmark adding is out.
Is there a way to set the timezone?

**Comment by watsonbox** [comment]
I tried the same thing with no luck, but [this solution](https://github.com/sissbruecker/linkding/issues/179#issuecomment-986292357) worked by updating `docker-compose.yaml`:

```yaml
volumes:
  - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
  - "./custom.py:/etc/linkding/siteroot/settings/custom.py:ro"
```

I note that there is another proposal to solve this in the app itself: https://github.com/sissbruecker/linkding/issues/722.

After playing with it for a bit, I decided to submit a small fix to get the `TZ` var working  https://github.com/sissbruecker/linkding/pull/765.
