### ISSUE TITLE
Allow configuring `/shared` as default page for unauthenticated users

### ISSUE THREAD

**Issue by thetiny99** [sissbruecker/linkding#776]
(The following content is translated by me using translation engine) 

Hello, I saw LINKDING by chance. No matter from its functions, interface or update stability, I feel like I have found a treasure. Thank you to the developers for their hard work!

The only regret is that LINKDING does not seem to support viewing content without logging in. In other words, you can view bookmarks as a "guest" without adding an account.

This demand scenario still exists:
1) Use LINKDING to build a public website and share bookmarks with a broad audience;
2) Use LINKDING to share public links in organizations, communities, schools, etc.

——LINKDING’s design in terms of privacy and authentication is impeccable. I hope developers can consider the anonymous browsing function. Thank you!

**Comment by jburnham** [comment]
Hi @thetiny99,

I believe this feature already exists in some form and I am providing the steps on how to enable this feature below.

In Settings -> General you can enable public bookmark sharing by checking these two boxes and saving.
- Enable bookmark sharing
- Enable public bookmark sharing

![image](https://github.com/sissbruecker/linkding/assets/254022/b49b2897-f108-4d51-983e-2ae1395b9428)

When you edit a bookmark, you can then enable Share.
![image](https://github.com/sissbruecker/linkding/assets/254022/48e3b2b9-2c19-4f5f-b543-64870544d703)

The https://linkding.example.com/bookmarks/shared page will then show all shared bookmarks without needing a login.
![image](https://github.com/sissbruecker/linkding/assets/254022/782bda4e-b4bf-49b6-bdf5-e4e003fb1114)

This shared bookmark page is linked on the homepage of the app before logging in.
![image](https://github.com/sissbruecker/linkding/assets/254022/d38c4907-dc9f-4237-bc8a-2ca051f584c3)

There are also settings to automatically make imported bookmarks shared which you can see below.
![image](https://github.com/sissbruecker/linkding/assets/254022/c368cb5e-2f8c-483b-953c-9494fb97c46b)

Best of luck and I hope this feature as implemented is acceptable for you.

**Comment by thetiny99** [comment]
> ![image](https://private-user-images.githubusercontent.com/254022/346296315-b49b2897-f108-4d51-983e-2ae1395b9428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMjU5MDUsIm5iZiI6MTcyMDMyNTYwNSwicGF0aCI6Ii8yNTQwMjIvMzQ2Mjk2MzE1LWI0OWIyODk3LWYxMDgtNGQ1MS05ODNlLTJhZTEzOTViOTQyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwNDEzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2I3MjU3NDdjMDZiMGY4YzI3Y2FiMTM0MjYzZTI0MTI0MjI2MGI3NWNiNDcxYTU0NjlkMThhZDk5ZjI2YjRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TBrTb_RZ3RW2gPQ3oIP7Y-tPIgHQPp7lrCwBr6Nkzes)
> 
> When you edit a bookmark, you can then enable Share. ![image](https://private-user-images.githubusercontent.com/254022/346296522-48e3b2b9-2c19-4f5f-b543-64870544d703.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMjU5MDUsIm5iZiI6MTcyMDMyNTYwNSwicGF0aCI6Ii8yNTQwMjIvMzQ2Mjk2NTIyLTQ4ZTNiMmI5LTJjMTktNGY1Zi1iNTQzLTY0ODcwNTQ0ZDcwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwNDEzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjUyMTY2ODgxMTNjMGMxNzYxZmNlMzgzNzYzOTkxNzQ1Zjk3ZTZkZjVjYWU4NzcxMzhhMDVmYjk4Y2I5OTcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4Hf93J8AjbNu-LGoTZzOIprnGCmcQNXL-0UUc6JATjo)
> 
> The https://linkding.example.com/bookmarks/shared page will then show all shared bookmarks without needing a login. ![image](https://private-user-images.githubusercontent.com/254022/346296451-782bda4e-b4bf-49b6-bdf5-e4e003fb1114.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMjU5MDUsIm5iZiI6MTcyMDMyNTYwNSwicGF0aCI6Ii8yNTQwMjIvMzQ2Mjk2NDUxLTc4MmJkYTRlLWI0YmYtNDliNi1iZGY1LWU0ZTAwM2ZiMTExNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwNDEzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWRlMDEyMDNiYWJmNGNmN2JiZDQ0MmE1NzJkY2EyYzJhZWM0NGI4NTY4ZGFhZmZlNTI4OGNiNzY0ZTI2ZWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RZXpA2kmurVTxCkDNd-nB7XSfzAXaTlSxMW_I17NQ2w)
> 
> This shared bookmark page is linked on the homepage of the app before logging in. ![image](https://private-user-images.githubusercontent.com/254022/346296598-d38c4907-dc9f-4237-bc8a-2ca051f584c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMjU5MDUsIm5iZiI6MTcyMDMyNTYwNSwicGF0aCI6Ii8yNTQwMjIvMzQ2Mjk2NTk4LWQzOGM0OTA3LWRjOWYtNDIzNy1iYzhhLTJjYTA1MWY1ODRjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwNDEzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmM0MDViNjU5NjdlZmUzM2FlYjY1NzA3Y2I3M2I3ZTEzODllNmExMjU5MDc0YjE3NmFkNTVjYTZmNmI0NjYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3myl-k0Z7hvXRdCXcEJcSnRRCWh8Tg5xDUnbn3lgNfI)
> 
> There are also settings to automatically make imported bookmarks shared which you can see below. ![image](https://private-user-images.githubusercontent.com/254022/346296789-c368cb5e-2f8c-483b-953c-9494fb97c46b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMjU5MDUsIm5iZiI6MTcyMDMyNTYwNSwicGF0aCI6Ii8yNTQwMjIvMzQ2Mjk2Nzg5LWMzNjhjYjVlLTJmOGMtNDgzYi05NTNjLTk0OTRmYjk3YzQ2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwNDEzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTZiZDZiYmIzMjA0YWM0Y2Q1YThhZmVhZjRhMWE5ZThhMDU5YTczNGQwOTY0MjZkNTQyYjFmNTRhZWQyZjljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BUoeYceSsDuEhiPSfuyL3V1fhF2di-8tZUMTMOWE1EQ)

Thanks for your answer. I did study this page carefully.

But if Linkding is used as a public website, the default login page will appear when visiting the URL, which may cause some confusion to visitors.

Can we make some enhancements to the bookmark sharing page? On the basis of keeping all functions unchanged, introduce the option of "**setting /bookmarks/shared as the default homepage of the website**"? (WordPress also has a similar function)

I looked through the previous issues and found that many people need similar functions. I hope the official will consider it. Thank you!
