### ISSUE TITLE
latest-plus image preview toasting rasppbery pi 4

### ISSUE THREAD

**Issue by fishamic** [sissbruecker/linkding#777]
After using the latest-plus image with Chromium on my Raspberry Pi 4, I am encountering a problem where the system keeps resetting while attempts to generate previews... normally i got this "queued" and "error" in detail info about bookmark . I suspect that the image may be too demanding for the Raspberry Pi, but I haven't been able to find any logs other than the standard information.

**Comment by sissbruecker** [comment]
You could check `background_tasks.log` in the Docker container for further info.

**Comment by sissbruecker** [comment]
Closing as stale
