### ISSUE TITLE
auto tagging

### ISSUE THREAD

**Issue by twonethree** [sissbruecker/linkding#781]
Do you have any plans to support regular expressions in auto -tagging settings?

**Comment by twonethree** [comment]
Is there any way to tag it by dividing it into a specific keyword, not the current domain format? Or do you have a plan to implement?

**Comment by ccxuy** [comment]
Agree, this is a very helpful feature. Maybe set some rules to provide tag options?

**Comment by ben7sys** [comment]
llm integration? ;)

**Comment by sissbruecker** [comment]
I have no plans. Also this isn't a very useful issue. If you want a feature please open a proper issue that describes what you want and ideally how you would image it to work, providing a few examples maybe.
