### ISSUE TITLE
RFI: Suggestions

### ISSUE THREAD

**Issue by anb-apg** [sissbruecker/linkding#786]
Hi!

Is there an autocomplete function like [1]? I actually wanted to point to the duckduckgo-ac-documentation, but I didn't find any...

Cheers

André

[1] https://developers.google.com/cloud-search/docs/reference/rest/v1/query/suggest

**Comment by sissbruecker** [comment]
I'm not quite sure what you're asking for, but there's a bookmark search API that might fit your use case.

**Comment by anb-apg** [comment]
I'd like to integrate it with [Keypirinha ](https://keypirinha.com/packages/websuggest.html) on Windows
