### ISSUE TITLE
Question: Apply Filter / View on open

### ISSUE THREAD

**Issue by Dark-Gizmoa** [sissbruecker/linkding#791]
Just a little question:

is it possible to apply a filter / open a specific view of the bookmarks?
Like: LogIn at instance, View is all bookmarks with tag "randomtag"?

Greetings Alex

**Comment by radiant-tangent** [comment]
From what I understand, you couldn't change the default view at login, but here are some other options.

You could create a bookmark with the query
For example "http://links.spacefoil.net/bookmarks?q=%23randomtag&unread=yes"
or ""http://links.spacefoil.net/bookmarks?q=%23randomtag" if you want unread and read.


You could use a greasemonkey extension (I use violentmonkey on firefox) to insert links on the top of the linkding page for various custom shortcuts
```
// ==UserScript==
// @name         Linkding Utilities
// @version      0.202408031749
// @description  Linkding Utilities
// @grant        none
// @match        http*://links.spacefoil.net/*
// ==/UserScript==


// Append links to header
const createLink = function(title, url){
  const a = document.createElement("a");
  a.setAttribute("href", url);
  a.innerHTML = title;
  a.className = 'quicklinks';
  return a;
}

const logoheader = document.querySelector('header > div:first-of-type > a:first-of-type > h1');
logoheader.appendChild(createLink(" (Random) ","http://links.spacefoil.net/bookmarks?q=%23randomtag"));
```
