### ISSUE TITLE
How to add parameters to the request header

### ISSUE THREAD

**Issue by QYG2297248353** [sissbruecker/linkding#798]
use `/api/bookmarks/check/`

Sorry about that, checked the documentation, and environment variable configuration.
I want to add request headers when requesting partial url: 

`Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7`

I'm wondering if any of you experienced gurus out there can help me out.
I'm installing via Docker-Compose, so I'd like to be able to do this via environment variables

**Comment by sissbruecker** [comment]
This doesn't seem to be a linkding related problem. You should be able to find this information in the documentation of whatever request library / REST client that you want to use.

**Comment by QYG2297248353** [comment]
> 这似乎不是一个与链接相关的问题。您应该能够在您想要使用的任何请求库/REST 客户端的文档中找到此信息。

No, through the browser plugin, the page cannot be correctly recognized and always displays age verification, but accessing it through the browser is normal.
After comparison, if the Accept Language zh CN is missing from the request, this issue will occur.
In particular, using web snapshots, the snapshots of this site are the same age verification.
Calling headless browser in docker I hope to add header

website as javbus.com
