### ISSUE TITLE
Allow hosting on a subdirectory

### ISSUE THREAD

**Issue by cyruz-git** [sissbruecker/linkding#799]
For added security, please allow hosting on a subdirectory (eg: https://linkding.somedomain.com/some_long_ass_sub_directory).

Even if this can be labeled as "security through obscurity", it's an easy method to add a layer of security on top of the service.

For reference, Vaultwarden implements this:
https://github.com/dani-garcia/vaultwarden/wiki/Using-an-alternate-base-dir

**Comment by sissbruecker** [comment]
Should be doable with this setting: https://github.com/sissbruecker/linkding/blob/master/docs/Options.md#ld_context_path
