### ISSUE TITLE
why not add a register page or function?

### ISSUE THREAD

**Issue by VeejaLiu** [sissbruecker/linkding#816]
why not add a register page or function?

**Comment by sissbruecker** [comment]
Technically there is an option, it's used in the demo instance: https://github.com/sissbruecker/linkding/blob/b30486317d835cc70f272983d5981bcfc6aa4cd7/siteroot/settings/base.py#L160-L161

I don't intend to maintain that as a public feature, as most use-cases don't revolve around allowing random people to create accounts. There is [another issue](https://github.com/sissbruecker/linkding/issues/42) for adding an invitation workflow which would make more sense.
