### ISSUE TITLE
Import feature does not recognize Instapaper HTML exports

### ISSUE THREAD

**Issue by noobdealer** [sissbruecker/linkding#827]
When importing bookmarks from Instapaper, the parser does not recognize the ordered lists used by the file.

**Comment by sissbruecker** [comment]
There are no lists or folders in linkding at this point. What you want should be covered by:
- https://github.com/sissbruecker/linkding/issues/285
- https://github.com/sissbruecker/linkding/issues/69

**Comment by noobdealer** [comment]
Oops, I should have clarified a bit more. It doesn't recognize the links inside the lists in the HTML file. My fault.
