### ISSUE TITLE
Support HTTP or socks5 proxy in latest-plus version

### ISSUE THREAD

**Issue by itning** [sissbruecker/linkding#828]
Some websites can only be accessed using a proxy. Failure to access them directly will cause the snapshot creation to fail.

![image](https://github.com/user-attachments/assets/81447b2d-2097-4cc8-b9cd-8cc2299b1fa0)

**Comment by sissbruecker** [comment]
Let's keep this discussion in https://github.com/sissbruecker/linkding/issues/493
