### ISSUE TITLE
Archived bookmarks - no result when searching for a word which is used only as tag

### ISSUE THREAD

**Issue by Export33** [sissbruecker/linkding#83]
# Actual behavoiour 

If you search the archive for a word which is used as `Tag` but not in the `Title` or `Description` the `Tag` is shown in the `Tags` list but not in the results.

## Archive

Before search: There is an entry where the search term matches a `Tag`.

![grafik](https://user-images.githubusercontent.com/25232960/108562672-83997a80-7300-11eb-94d9-c581038103ac.png)

## Search result

No results but an entry in the `Tags` list.

![grafik](https://user-images.githubusercontent.com/25232960/108562568-5ea50780-7300-11eb-8222-11bae750e54e.png)

## Expected behaviour

As in the normal (unarchived) bookmarks list the result should be shown if a searchterm matches a `Tag`.

![grafik](https://user-images.githubusercontent.com/25232960/108563051-205c1800-7301-11eb-82ce-7a6a76278e30.png)

**Comment by sissbruecker** [comment]
Interesting, I can not reproduce this. For me the tag cloud is empty as well - which for me is the expected result. I prefer having a clear disctinction between search terms and tags. But that's a different debate.

To debug this it would help to know in which version this happened and ideally an example database.

**Comment by Export33** [comment]
This took a while to respond because i wanted to anonymize my db first and had no spare time.

While doing so now, i couldn´t reproduce it in `1.6.1`. The disinction works as you expect it. 
In both lists (normal and archive) the entry is only found when using the `#`. The reusult and tags list is empty otherwise.
