### ISSUE TITLE
How to maintain collection, e.g. rename or merge tags?

### ISSUE THREAD

**Issue by pmorch** [sissbruecker/linkding#830]
Forgive me for using an issue for this. If there is a better support channel, please just let me know. I have a question:

How does one go about maintenance tasks such as renaming a tag, merging two tags, or other bulk edits?

I totally understand that the UI doesn't support this.

I was hoping for some JSON export/import functionality so it would be relatively simple to do this with a script, but alas no.

Are these my options?

1. Export Netscape HTML file, modify by script, Import Netscape HTML file
    * Modifying netscape HTML files is not for the faint-hearted.
1. Find some util that can convert Netscape HTML file <-> JSON reliably
    * Any recommendations that can convert bidirectionally and that don't mess up e.g. encoding, weird tags, etc?
1. Stop linkding, modify sqlite file with sqlite CLI, (re-)start linkding
    * Perhaps my best bet?

What would the recommended approach be?

**Comment by sissbruecker** [comment]
You should be able to do this in the UI using the bulk edit feature:
![Bildschirmfoto 2024-09-16 um 14 10 21](https://github.com/user-attachments/assets/5dbbebcb-6062-41c4-9eba-d13b446b92d7)

You can basically filter for the old tag name, bulk add the target tag name, and then bulk remove the old tag name. For just renaming a tag you can also do this in the admin UI. The admin UI also allows to delete tags that you don't need anymore so they don't show up in the auto complete.
