### ISSUE TITLE
Tags don't support spaces?  A tag with a space is never found.

### ISSUE THREAD

**Issue by sunrisepi** [sissbruecker/linkding#86]
Hi there.. So I noticed I imported some bookmarks from Firefox, where I had a tag named **Sage Feeds** in the bookmarks.  When I page through the bookmarks in **LINKDING** I can see the bookmark link there, and it shows a tag **#Sage Feeds**.  Also, in the **Tags** section of **LINKDING** it shows up there in the list as a tag.  If I click on the **#Sage Feeds** link in Tags then nothing  is returned.  Also, if I just search for **#Sage Feeds** in the search bar of **LINKDING** (to search by tag) nothing is returned.  

Example of the bookmark that was imported... 

 `<DT><A HREF="http://rss.news.yahoo.com/rss/sports" ADD_DATE="1256421049" LAST_MODIFIED="1513440582" TAGS="Sage Feeds">Yahoo! News - Sports</A>
`

So it seems a space in a tag is not findable/searchable.. is this a known issue?  Thanks.

**Comment by sunrisepi** [comment]
I think I figured this out myself.  Space can't be permitted in tags, as space is the separator for the multiple tags field.  If that's correct, go ahead and close this out please.  Thanks.  :)

**Comment by sunrisepi** [comment]
closing!

**Comment by xteaun** [comment]
I would suggest to allow spaces in tag names and instead use commas to separate different tags.

**Comment by electricmessiah** [comment]
> I would suggest to allow spaces in tag names and instead use commas to separate different tags.

Isn't this how most software that uses tags already works? Why is LinkDing not using this?
