### ISSUE TITLE
Setting to turn on/off auto-completion of "description"

### ISSUE THREAD

**Issue by gigazine-dev** [sissbruecker/linkding#868]
In v1.35.0, if I leave "description" blank for the REST API `POST /api/bookmarks/`, Linkding will automatically complete it.
However, in my use case, I set "description" only for specific bookmarks and leave it blank for the rest.
Therefore, I am having trouble because the blank "description" is automatically completed.
I understand that this auto-completion is useful in many cases, but could you make it possible to turn this function on and off in the settings?

**Comment by sissbruecker** [comment]
Did you check the API docs on how to accomplish this?

**Comment by gigazine-dev** [comment]
> If the title and description are not provided or empty, the application automatically tries to scrape them from the bookmarked website. This behavior can be disabled by adding the disable_scraping query parameter to the API request.

Oh, I overlooked this.
I had checked the Example payload, so if it had been reflected there I would have noticed...

**Comment by gigazine-dev** [comment]
And I tried using the `disable_scraping` query parameter

> description:	""
> disable_scraping:	true

However, I saw the "Descrition" request is filled... Why?

**Comment by sissbruecker** [comment]
It's a query parameter, you need to add it to the end of the URL `https://linkding.domain.com/api/bookmarks/?disabled_scraping`

**Comment by gigazine-dev** [comment]
Thanks!
I saw the Description keeped empty.
