### ISSUE TITLE
no python application found, check your startup logs for errors

### ISSUE THREAD

**Issue by tmkklivecom** [sissbruecker/linkding#870]
Docker setup
[compose.yaml.txt](https://github.com/user-attachments/files/17255409/compose.yaml.txt)
[env.txt](https://github.com/user-attachments/files/17255456/env.txt)

**Comment by tmkklivecom** [comment]
[env.txt](https://github.com/user-attachments/files/17255450/env.txt)

**Comment by tmkklivecom** [comment]
[linkding.csv](https://github.com/user-attachments/files/17262497/linkding.csv)

**Comment by sissbruecker** [comment]
It says:
```
2024/10/04 10:10:52,stderr,sqlite3.OperationalError: attempt to write a readonly database
```
So the application can not write to the data folder that you are mounting into the Docker container for some reason.

**Comment by tmkklivecom** [comment]
Permissions or docker issue. I set up linkding on another docker and there was no problem
