### ISSUE TITLE
[Feature request] Retrieve webpage title and content from browser instead of server

### ISSUE THREAD

**Issue by ccxuy** [sissbruecker/linkding#873]
Provide option to retrieve webpage title and content from browser instead of server, because sometime the website is maybe block by cloudflare or require login, and linkding plugin could not do anything with it.

**Comment by sissbruecker** [comment]
This is already possible with the latest version of the browser extension. For the bookmarklet there is an open issue here: https://github.com/sissbruecker/linkding/issues/118
