### ISSUE TITLE
when html snapshotting reddit it gets blocked. is there a way to just automatically have a singlefile thing that gets saved automatically get bookmarked instead?

### ISSUE THREAD

**Issue by yellowbikewithbluehandles** [sissbruecker/linkding#876]
As the title says is there a way to have something I singlefile save automatically get taken up my linkding instead? I remember seeing a url validation thing so I'm guessing I have to enable that so I can make it save localfiles as a url but does anyone have any advice to make this as simple as possible instead of having to singlefile the page wait for it to download and then manually drag and dropping into linkding? Thank you!

**Comment by sissbruecker** [comment]
There is no integration with the singlefile extension that I'm aware of. There's an existing issue to make snapshots work with sites that use bot detection so I'm closing in favor of that: https://github.com/sissbruecker/linkding/issues/712

For Reddit specifically configuring a user agent for singlefile might be enough to make it work: https://github.com/sissbruecker/linkding/issues/690.
