### ISSUE TITLE
Chrome plugin: Error saving bookmark: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by ccxuy** [sissbruecker/linkding#881]
Chrome plugin: Error saving bookmark: TypeError: Failed to fetch

**Comment by sissbruecker** [comment]
Please open an issue in the extension repo and provide some more details, such as which URL you tried to bookmark and maybe what your configuration looks like. Otherwise I have no way to figure out what your problem is.

**Comment by ccxuy** [comment]
It seems like this error randomly pops up on different website, but on the same website works just fine after a while. Looks like a network issue, because I am behind a company proxy.
