### ISSUE TITLE
YouTube links not loading the title and description of the video in bookmark form

### ISSUE THREAD

**Issue by rsilvr** [sissbruecker/linkding#889]
Adding a YouTube link in bookmark form never loads the actual title and description of the video, only some stub text. I could reproduce this issue both in a hosted instance running version 1.34.0 and in Linkding's demo instance (https://demo.linkding.link), currently in version 1.36.0.

Interestingly enough, I couldn't reproduce this problem while running the master branch (at [commit 6548e16](https://github.com/sissbruecker/linkding/commit/6548e16baa9823b5d69887cec785cb22f54a4921)) in a dev-container in my machine. It displays as also running version 1.36.0.

![image](https://github.com/user-attachments/assets/2fced275-011a-48f7-bc77-625377e0a31e)
![image](https://github.com/user-attachments/assets/a21ea4f7-7e7d-4cb6-8dee-11f83cd0c1a9)

**Comment by sissbruecker** [comment]
Mhh I can't reproduce this either. But I remember Youtube sometimes returning some generic metadata, so I assume this is just Youtube sometimes preventing access from bots.

In any case, this will probably not be fully solvable with server-side scraping. I'd suggest you use the browser extension for saving such bookmarks, which now supports loading the metadata from the current browser tab. Or wait until the same is supported for the bookmarklet, which should be covered by https://github.com/sissbruecker/linkding/issues/118.

**Comment by zikes** [comment]
I just want to note that I have been experiencing this same issue for some time (a few months, I would estimate) with the browser extension.

Browser: Chromium Version 130.0.6723.116 (Official Build) for Linux Mint (64-bit)
Extension: Version 1.12.1

![Screenshot from 2024-12-05 14-39-21](https://github.com/user-attachments/assets/2211b7bb-0c45-4314-a8f5-d7e01cb6581b)

**Comment by zikes** [comment]
Apologies, I did not see the note about the extension using the server to fetch the info by default. I found the option to enable browser metadata and it now works for me.
