### ISSUE TITLE
[Feature Request] Custom fields

### ISSUE THREAD

**Issue by joeeasterly** [sissbruecker/linkding#890]
Would it be possible for a user to create custom fields? Here are two example use cases I'm thinking of already:

- slug: a shortcode so users can create their own url shortening service, if they have the right kind of setup. For example, if I have linkding installed at links.mysite.com, clicking on https://links.mysite.com/2024genmeeting would redirect the browser to the bookmark that I have saved matching that slug. 
- group: If I want to use linkding to help manage a reference guide service (kind of like a customizable lighter-weight version of Zotero), I could then use the API to create customized pages of bookmarks, without having to worry about some kind of keyword collision with the tags field. The ability to create and use dedicated fields would make something like this that much more powerful.

thanks!

**Comment by sissbruecker** [comment]
A custom field for me would be something were you can dump some random data, and then it is surfaced somewhere in the UI and probably the API. What you want would require integrating those fields with other functionality such as routing and possibly search.

Anyway, I don't think I want to go that far. At the moment I'm not interested in supporting the URL-shortening use-case. Your second use case sounds like you should use tags, or put some other keyword in the description, notes or some other field that is being searched.
