### ISSUE TITLE
Want to be compatible with PostgreSQL

### ISSUE THREAD

**Issue by mzch** [sissbruecker/linkding#9]
I installed linkding manually and accessed top page, then linkding responded `Server Error (500)`.
It seems to happen it when accessing `https://example.com/bookmarks`. When trying `/bookmarks/new`, `/settings`, `/bookmarklet` and `/logout`, linkding showed pages normally.
How can I fix this?

- OS: Debian 10.2
- Python: 3.7.6

**Comment by mzch** [comment]
Sorry, this is my mistake. Using SQLite3, linkding works well.
Can you make linkding be compatible with PostgreSQL/MySQL/MariaDB?

**Comment by sissbruecker** [comment]
It should be possible, but personally I have no motivation to do so. I think the out-of-the-box approach with SQLite is simple and completely adequate.

However I'm open to pull requests that make this work. My guess would be that the DB queries that Django generates for loading bookmarks and tags on the bookmark page are not compatible with PostgreSQL.
