### ISSUE TITLE
Add bookmarks to a queue waiting for connection to linkding instance

### ISSUE THREAD

**Issue by steakhutzeee** [sissbruecker/linkding#99]
Hi,

linkding is working on my NAS and i connect to it with vpn.

So basically i can only add bookmarks to linkding when in my home network.

Could be handy to add some sort of queue in order to save the bookmarks and only upload them when the connection is available to the instance.

Actually i have to connect to vpn anytime i want to save a bookmark.

Hope it's clear.

**Comment by Gatada** [comment]
As LinkDing is a web service, if you cannot connect to it, there is no entity that can manage your bookmark queue.

You will need something on the client side (where you create the bookmarks) to retain the queue. In other words, it sounds like you want an app to interface with LinkDing. To my knowledge, at least on iOS, there currently is no LinkDing native app.

**Comment by steakhutzeee** [comment]
Thank you for your reply.

Actually i use Windows and Android. Is there something that could work this way on these platform?

**Comment by sissbruecker** [comment]
This is not a use-case that I want to support ATM.

Maybe consider exposing only the linkding application on your NAS to the web instead of the whole NAS? That seems like something that should be possible using port forwarding in your router or similar.
